### ISSUE TITLE
Associate license with content

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#100]
Issue:  

It is common and useful to be able to explicitly associate a license or other rights statement with content.  There was an early request and use case provided by Creative Commons, and more recently from @BigBlueHat regarding existing functionality of annotation clients.

Proposal: 

Promote the usage of a license relationship on any resource by including it in the model and JSON-LD serialization.  Given other usage of dcterms in the same space, the obvious candidate is [dcterms:license](http://dublincore.org/documents/dcmi-terms/#terms-license), with a json-ld key of 'license'.  It could be associated with any resource (though not a literal body, of course) and would only apply to the resource that it is associated with.

**Comment by iherman** [comment]
I am fine with this. The document should also remain silent what is the value of that property:-)

**Comment by azaroth42** [comment]
Other than it being a URI, not a string (required by use of dcterms), :+1: to remaining silent. No need to make recommendations about which licenses to use, as that's a business decision.

**Comment by BigBlueHat** [comment]
Assuming the new JSON-LD focused "fork" of the model doc keeps the same [Table of Contents](http://w3c.github.io/web-annotation/model/wd/#respecContents) where would you expect to see the licensing information?

I'm almost wondering if we need a broader "metadata" section about creation, renderer (forthcoming), and license (possibly among other things) which can be specified on Annotation, SpecificResource, and/or External Resources.

Once I know where to put it, I can add that to the JSON-LD doc...or at least queue it up behind the other "cleaning" going on there.

**Comment by iherman** [comment]
@BigBlueHat I presume your question was editorial, ie, by 'where' you mean where in the document, right? If so, I agree with what you propose...

**Comment by BigBlueHat** [comment]
@iherman correct! Sorry that wasn't clear(er).

**Comment by iherman** [comment]
Closed by virtue of telco discussion:  http://www.w3.org/2015/11/18-annotation-irc#T16-19-50

**Comment by azaroth42** [comment]
Re-opening for tracking purposes. Telco /accepted/ the proposal, but it has yet to be implemented in the spec. Should keep open until that time.

**Comment by akuckartz** [comment]
The range of `dct:license` is `http://purl.org/dc/terms/LicenseDocument`. That can be refered to in a non-normative section of the web annotation specification.

**Comment by azaroth42** [comment]
Further reflection at editing time ... we could allow arbitrary strings using the Content pattern. Also, we should use rights, not license, as the Public Domain is not a licence... there are no rights on the content to be licensed.

```
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno%%anno%%",
  "type": "Annotation",
  "rights": {
    "type": "Content",
    "text": "This annotation is dedicated to the Public Domain"
  },
  "body": {
    "id": "http://example.net/review1",
    "rights": "http://creativecommons.org/licenses/by/4.0/"
  },
  "target": "http://example.com/product1"
}
```

**Comment by iherman** [comment]
Where do the terms:

```
"rights": {
    "type": "Content",
    "text": "This annotation is dedicated to the Public Domain"
  },
```

come from? Would we want to define those in the context of rights? I would prefer to keep away from that; we just said we have a property whose value is, in RDF terms, a resource, in JSON terms a URI or an object whose content we do not control.

(Note that there will be a separate WG coming up rights an obligation, defining such terms. We should leave them this...)

**Comment by azaroth42** [comment]
The option is to remain silent about embedded content and only allow for external license/rights URIs? 

Process wise, should we accept the current WD and raise a specific issue to reduce the scope here?

**Comment by azaroth42** [comment]
Removed the Content version; now require a URI to reference, but no requirements on what that resource actually is.  Could be creative commons, could be just some URI with HTML.
