### ISSUE TITLE
Do we need an `annotates` relationship for use in RDF and/or Link Relationships?

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#101]
We can currently express relationships (even vague ones) within an Annotation (see https://github.com/w3c/web-annotation/issues/98#issuecomment-153831097 ).

However, we still do not have (for better or worse) the ability to state `body annotates target`. We have instead `annotation hasBody body; annotation hasTarget target`.

Should we define an `annotates` relationship?

Or (perhaps) a link relationship that could be used with either an annotation or a body?

``` http
GET /blog-post/comment-1
```

``` http
HTTP/1.1 200 OK
Link: </blog-post>; rel="annotates"
```

That scenario done now would look like:

``` http
GET /blog-post/comment-1
```

``` http
HTTP/1.1 200 OK
Link: </blog-post>; rel="http://www.w3.org/ns/oa#hasTarget"
```

Obviously, if we specified `annotates` in the [link relation registry](http://www.iana.org/assignments/link-relations/link-relations.xhtml), we'd also (likely) want to specify the reverse relationship for us in the more common scenario of linking from a blog post to any known comments.

Here are the existing link relationship values that come pretty close (but are more specific):
- [bookmark](http://www.w3.org/TR/html5/links.html#link-type-bookmark) -- specific to bookmarking
- [describes](http://tools.ietf.org/html/rfc6892) -- description only
- [describedby](http://www.w3.org/TR/2009/REC-powder-dr-20090901/#semlink) -- same as above; just points the other way
- [replies](http://tools.ietf.org/html/rfc4685#section-4) -- would only work for a direct reply

and...historically (though not part of the registry...yet?)
- [annotation](http://tools.ietf.org/html/draft-ietf-iiir-html-00) -- ...you'll have to search for it...[or see it highlighted](https://via.hypothes.is/tools.ietf.org/html/draft-ietf-iiir-html-00)

**Comment by iherman** [comment]
> On 5 Nov 2015, at 05:09, BigBlueHat notifications@github.com wrote:
> 
> We can currently express relationships (even vague ones) within an Annotation (see #98 (comment) https://github.com/w3c/web-annotation/issues/98#issuecomment-153831097 ).
> 
> However, we still do not have (for better or worse) the ability to state body annotates target. We have instead annotation hasBody body; annotation hasTarget target.
> 
> Should we define an annotates relationship?

Well… if we are in RDF land for a moment, then I do not see what this is necessary. That type of relationship between a body and a target can be found out by a fairly trivial SPARQL query; using SPARQL as some sort of a rule engine (using SPARQL CONSTRUCT) one can generate new graphs with this relations, etc. 

RDF people have powerful tools already, we do not have to add additional things. Non-RDF people will not care…

**Comment by azaroth42** [comment]
I can see some value from a _protocol_ perspective in an iana relation registration for `annotates` (or `annotation` in homage)  and `annotatedBy`, such that the links can be surfaced at the HTTP layer. I'm with @iherman and Jacob that at the model/RDF layer `annotates` doesn't seem to solve a problem that anyone has expressed, at least such that I've understood it :)

The question I think would need answering is:  When a client encountered the `annotates` relationship, what would it do differently compared to if it wasn't there?

**Comment by BigBlueHat** [comment]
Annotation (to me at least) boils down to "the expectation of contextual display."

My blog post about your blog post _may_ be considered an annotation, or reply, or comment, or review, or whatever, but if I'm explicitly stating that it's an "annotation", the _expectation_ is that it will be displayed alongside in some way--marginalia, etc.

Here's what @timbl wrote for the `annotation` link relationship in 1993:

>   ANNOTATION
> 
> The information in B is additional to and subsidiary to that in A.
> 
> Annotation is used by one person to write the equivalent of "margin notes" or other criticism on another's document, for example.

There's a bit more about newsgroups and their articles along with the link be "acyclic," but those uses fall outside of what we're defining at this point, I'd reckon.

In RDF-land, it would be the expectation that the "description" contained in the triples not be considered canonical or authoritative, but as TimBL put it "additional to and subsidiary to." The author of `A` MAY consider the contents of `B` for eventual inclusion in a canonical graph, but by their expression as an annotation they stay "outside" until (and optionally) they are incorporated by the author of `A`--in a similar fashion to the copy-edit use case, etc.

All that said, this may fall outside the scope of our charter, and probably be something just done by "interested parties" (me...at least...) at the IETF and/or IANA as "just" a link relationship. But, since we're doing annotation, I thought I'd bring it up. :wink:

**Comment by azaroth42** [comment]
While I agree with all of the content, I don't see that it justifies the addition of an `annotates` predicate in RDF to be described in the model? The existence of the Annotation resource implies all of that, no?

Conversely, a Link header on the response from a resource that is the Body of an Annotation like:

```
Link: <http://example.org/target1>;rel="annotates";describedBy="http://example.org/anno1"
```

Could be very useful for discovery. Shall we close this issue and reframe in a new one?

**Comment by BigBlueHat** [comment]
:+1: to reframing this in the context of the discovery conversations (which are mostly yet to be had).

I do think we'd keep it entirely out of the model, probably reference it from the protocol, and most likely specify all of it at the IETF and register with IANA vs. do it "under" the W3C. But that's new territory for me, so maybe I can buy @jasnell some :coffee: or some such to find out how all that works. :wink:
