### ISSUE TITLE
ActivityStreams / Annotation comparison

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#102]
The ActivityStreams vocabulary has many of the same basic features as ours, although the Annotation model adds significant value in the target area of SpecificResources.  This issue exists to track the mapping, and provide input towards assessing if there is a common core of features.

After some clarification with James, a basic property mapping looks something like:
- as:published -> created
- as:updated --> modified (proposed)
- as:content --> content (proposed new name for text)
- as:name (proposed new name for as:displayName) --> label
- id, as:url, as:href --> id
- type --> type
- as:actor --> typically our creator
- as:context --> scope
- as:scope, as:bcc, as:cc, as:bto, as:to --> audience? (proposed)
- as:generator --> generator
- as:hreflang --> language [but note no language for Content resources]
- as:mediaType --> format
- as:oneOf --> oa:Choice or repeated predicate for selector/state (proposed)
- (all of the Collection stuff) --> (the same Collection stuff)
- as:inReplyTo --> target
- as:subject, as:object, as:target --> The mapping depends on the type of the parent object, but these typically map somehow to body and target
- as:tag --> Annotation

Class mapping:
- Content --> EmbeddedContent
- Note --> TextualBody
- Audio --> Audio
- Image --> Image
- Video --> Video
- Question --> Annotation [kinda]
- Application --> Software
- Group --> Organization
- Organization --> Organization
- Person --> Person

Significant missing mappings:
- as:accuracy --> ___ (for confidence of the annotation's truthiness)
- Document, Page -->  ___ (for separating web page or other multi-media resource)
- as:attributedTo --> ___ (for separating creator and agent responsible)
- as:replies --> ___ (a collection of things that reply to this)
- ___ --> Dataset (they don't have any way to type a Dataset)
- ___ --> generated
- ___ --> language (on Content, where there's a URI and no content property)

**Comment by jasnell** [comment]
Note that `as:accuracy` is specifically defined for `as:Place` and represents the "fuzziness" of the geo coordinates.

**Comment by azaroth42** [comment]
@jasnell Good point, don't want systems to infer that an Annotation is an as:Place. The use case here is for machine generated annotations, and wanting to provide some level of confidence in the assertion. So far we've treated it as too specific a requirement to have as in scope at this stage.

**Comment by BigBlueHat** [comment]
Per: http://www.w3.org/2015/11/18-annotation-irc#T16-12-33

> RESOLUTION: defer defining mapping of Annotation terms with Activity Streams term ot later Note, currently continue with Annotation terms in use

Goal being to not block on AS2 delivery, but still plan to define a mapping separately from the Annotation document(s) CR's--most likely as a NOTE aimed at parties interested in mapping the two into the same space (where possible).

**Comment by akuckartz** [comment]
It is easy to forget ToDos when they are only mentioned in closed issues. Why not keep it open and set an appropriate milestone?

**Comment by BigBlueHat** [comment]
@akuckartz because our plate is too full already. :frowning: If/when we get the other bits done--or AS2 ships--then this will surface all on it's own. :smile:

**Comment by azaroth42** [comment]
For reference, the Social WG F2F on Dec 1 will discuss taking AS to Rec or not:
    https://www.w3.org/wiki/Socialwg/2015-12-01#December_1

If the decision is _not_ to take it through the process, then any alignment would be informational only, as we couldn't normatively refer to the terms.  In the same way that we can't refer to Content in RDF.  For due process, I'm reopening with this new information as justification. Will re-close after the above discussion. 

@akuckartz @BigBlueHat is that okay with both of you?

**Comment by azaroth42** [comment]
New information: Social Web WG have declared their intent to take AS2 through the process and to try and get all CR blocking issues at least in the queue over the next week or so. That's not to say that they will get them /resolved/, but the intent is to move quickly and steadily towards CR.

Proposal: Given that (and that we are not as far along as that even), I propose to leave this issue open, and to [continue to] normatively require AS2 Collections per #50 and #92.

**Comment by BigBlueHat** [comment]
Great news. :+1:

**Comment by azaroth42** [comment]
I believe the outstanding action is to ensure that the vocab doc records the equivalencies between the terms that we've chosen to use and the AS terms, if they're different?  Once that is done, we can close?

**Comment by azaroth42** [comment]
Mark activity streams `at risk` as SWWG has not yet gone to CR.

Create a new version of the documents without AS in a branch

**Comment by BigBlueHat** [comment]
@azaroth42 also, this was marked as `model` long before we had the `vocab` document (or label).

Do we also need a note in the `model` document?

Just let me know.
