### ISSUE TITLE
http/https?

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/web-annotation#103]
The spec says in several places "http/https URI that identifies it."
- I completely agree about requiring URIs to be http and thus resolvable
- It would be nice to explain this in a paragraph, pointing to TimBL's "5 stars"
- However, I think that using https for URIs to identify things is never a good idea. See considerations in a question I posted to the community: http://stackoverflow.com/questions/33563814/can-https-urls-be-semantic-cooluris. If you agree, please remove the references to https

**Comment by BigBlueHat** [comment]
I'm :+1: on this generally. Here's another related link:
http://www.w3.org/DesignIssues/Security-NotTheS.html

However...I'm not keen on restricting the URI's people pick. They really shouldn't use `https` if the thing is also identifiable as `http`--and it's unfortunate that `https` is it's own protocol, etc...but it happened...what can we do... :stuck_out_tongue_winking_eye: 

Rather, I think we _should_ make a clear not to prefer `http` URI's over `https` one's specifically--even if the server always redirects to the `https` one.

That said, others here may know more of this problem space than I. Certainly, there are other dragons beyond here such as non-identifying query parameters (Google's `utm_*` tracking mess...etc...), and I'm not sure what the Linked Data answers to those problems are in total. But am _very_ curious about how we can help people not hit unnecessary walls.

**Comment by csarven** [comment]
+1 to serving secure `http` - as opposed to `https` - resources (since TLS is on a lower level any way). The catch is that, existing tooling/UI gives special treatment to `https`. On the other hand, serving secure `http` may quietly workaround (for better or worse) mixed content, .., sticking to singular vocabulary IRIs (as opposed to redirecting or mapping between `http` and `https`).

**Comment by iherman** [comment]
I think the choice between `http` or `https` is not for us to decide. Formally, both are fine for RDF, they are both URI-s. I believe it is out scope for the Annotation WG to decide which of the two should be used for reasons of coolness or anything else. This discussion has the capability to drag on... and the issues are not annotation specific.

My proposal is close the issue and continue the discussion elsewhere. It may happen on the mailing list, but it should not be a formal issue.

**Comment by csarven** [comment]
+1 to @iherman 's points. I think the only thing of relevance for this WG is whether to have the vocab ns in http or https. I think the default is http at W3C. There were some discussions to move to https, but that is most likely not an immediate concern for this WG.

**Comment by azaroth42** [comment]
Agree that while interesting, and perhaps a take-away is not to refer to specific protocols at all in the model spec, it's not in scope for the WG to even make recommendations here.  Propose close/out of scope on 11/11 call

**Comment by BigBlueHat** [comment]
:+1: to out of scope.

**Comment by akuckartz** [comment]
I doubt that security considerations are out of scope. Using unencrypted `http` is a security issue.

**Comment by iherman** [comment]
We have put aside other security issues, too, like access control to a full Annotation or a part thereof. More exactly, we rely on generic Web mechanisms to solve that, because these are not specifically annotation issues. I do not think `http` vs. `https` is different from that point of view.

**Comment by VladimirAlexiev** [comment]
I propose to replace "http/https URI" with "resolvable URL". That way the spec will be truly non-committal on the issue.

**Comment by iherman** [comment]
> On 9 Nov 2015, at 09:30, Vladimir Alexiev notifications@github.com wrote:
> 
> I propose to replace "http/https URI" with "resolvable URL". That way the spec will be truly non-committal on the issue.

There is a clear usage patterns for non HTTP URI-s for annotations. An EPUB is often identified with an ISBN, meaning a URN. I do not think we want to make it impossible to use such a URN as a target for an annotation. (Think of sites where people can add their notes to a book.)

**Comment by VladimirAlexiev** [comment]
Regarding the last comment by @iherman : then "http/https URI that identifies it" in the spec is bad because it's discriminatory

**Comment by iherman** [comment]
@VladimirAlexiev I am not sure I understand this comment... but I would propose we wait for now. The issue has been closed with the remark that we should not refer to specific protocol, and we should look again at the text of the next draft when the editors have issued it.
