### ISSUE TITLE
Embedded Targets

### ISSUE THREAD

**Issue by csarven** [w3c/web-annotation#105]
Would it make sense to broaden embedded bodies, more specifically textual bodies to also cover targets? While hasTarget has extensive ways of capturing the target information, it doesn't appear to have a simple way to refer to some text/markup. For example, hasBody can have oa:text, meanwhile hasTarget has to go through hasSelector - this is unless of course it is not prohibited to use oa:text on hasTarget.

I have something along the lines of: `<mark about="[this:#foo]" typeof="http://purl.org/dcmitype/Text">foo</mark>`, which was marked by the UI. That subject (#foo) will be the target of an annotation. What I'd like to do is extend that by simply saying that the target has a value/label/description/HTMLtext instead of having to go through hasSelector.

If oa:text is okay on hasTarget, I suggest some editorial on http://www.w3.org/TR/annotation-model/#textual-body and broaden the description to cover both body and target.

**Comment by azaroth42** [comment]
Can you provide the JSON-LD example for clarity please Sarven?

Do you want to refer to some text _in a web resource_ or just a bit of text that's embedded solely in the Annotation, along the same lines as TextualBody?  Or do you want to have a target that's a SpecificResource that also captures the exact representation of the selected (potentially also styled and stateful) segment of the web resource?

**Comment by csarven** [comment]
It is along the lines of oa:TextualBody and oa:text. Practically the same example as in http://www.w3.org/TR/annotation-model/#textual-body (all the bits for hasBody) but for hasTarget. So like:

```
<http://example.org/#qux> a oa:Annotation ;
    oa:hasTarget <http://example.org/#target> ;
    oa:hasBody <http://example.org/#body> .

<http://example.org/#target>
        a oa:TextualBody;
        oa:text "foo <em>bar</em> baz" ;
        dc:language "en" ;
        dc:format "text/html" .

<http://example.org/#body>
        a oa:TextualBody;
        oa:text "<p>Comment<p>" ;
        dc:language "en" ;
        dc:format "text/html" .
```

**Comment by azaroth42** [comment]
You could do this with EmbeddedContent, rather than TextualBody, as the class for the target. Is there a use case that motivates this particular pattern though, rather than the typical target-by-reference rather than by-value?  I could imagine it being useful in some situations in RDFa when the annotation is embedded in the same HTML as the target, as per #87. If that's the use case, lets pick one of the two issues :)

**Comment by csarven** [comment]
EmbeddedContent is not entirely clear to me, and also appears to go through `oa:hasSelector`. What I'm trying to achieve is much simpler.

RDFa and #87 is closer to what I want to achieve.
