### ISSUE TITLE
Selecting more than text

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#107]
Right now, we specify 5 [selectors](﻿﻿﻿http://w3c.github.io/web-annotation/model/wd/#selectors):
- [FragmentSelector](http://w3c.github.io/web-annotation/model/wd/#fragment-selector)
- [TextQuoteSelector](http://w3c.github.io/web-annotation/model/wd/#text-quote-selector)
- [TextPositionSelector](http://w3c.github.io/web-annotation/model/wd/#text-position-selector)
- [DataPositionSelector](http://w3c.github.io/web-annotation/model/wd/#data-position-selector)
- [SVGSelector](http://w3c.github.io/web-annotation/model/wd/#svg-selector)

@tkanai points out in https://github.com/w3c/web-annotation/issues/95#issuecomment-153966728 that there is not currently a way to include an `<img>` tag (and it's representative visual output) within the selection.

From the comment mentioned above:

> Could you tell me how to select "I (love)" words, or both "I" and the heart mark Image, from the html text below with the XPathSelector? I also would like to make sure how to select "I" only.
> `<p>I <img src="love.png" /> New York</p>`
> 
> As I frequently encounter such paragraphs while I'm reading Japanese eBooks, although images are "Kanji" characters, I am looking for an appropriate selector which can be applicable for non-normalized HTML documents.

Here is an example of such text which uses images (and `<ruby>` markup, fwiw) for presenting Kanji characters to the reader:
http://www.aozora.gr.jp/cards/000879/files/127_15260.html

Here's an annotation made with Hypothes.is that shows the inefficiencies of the currently specified `Text*Selector` selectors:
https://hypothes.is/a/kjbFiUKHSKaa1diyMQx1qQ
and as JSON
https://hypothes.is/api/annotations/kjbFiUKHSKaa1diyMQx1qQ

Because the image content is not in the "normalized" markup, it can't be selected.

It _may_ be possible to use an XPointer FragmentSelector, but that seems dubious given the lack of implementations and dearth of knowledge around it (sadly :cry:).

We need to consider this use case when specifying new selectors which are more "node focused" such as XPath and CSS based selectors--as they present an opportunity to support this use case directly...or at least lay the foundation...one hopes.

**Comment by azaroth42** [comment]
DataPositionSelector would work, FWIW.  Or we could make it symmetrical with a DataQuoteSelector?
I'm looking for easy and cross-domain here :)

**Comment by azaroth42** [comment]
Is there a proposal coming, or does it solved by another issue? Alternatively, `DataQuoteSelector` ?

**Comment by iherman** [comment]
I am a little bit afraid of trying to do too much and doing it in isolation. We do have fragment selectors in very general terms. I believe our general strategy should be that experts of various media types, that want to have annotations on that data, should define their respective fragment selector mechanisms, and the model should rely on those.

I realize that, in some cases, the fragment used by an application will not be entirely kosher in the sense of not going through the full round of IANA registration of the fragment. And that is fine: the application will use some non-fully-standard, or de-facto-standard, or XXXX-standard fragment ID. But trying to define, essentially, fragments within the realm of this WG has no end in sight...

**Comment by azaroth42** [comment]
Can we get a proposal for 2016-01-27, otherwise postpone?

**Comment by tilgovi** [comment]
The specific request about an _img_ tag would be covered by the XPathSelector.

**Comment by tilgovi** [comment]
You could select the tag in any number of other ways, too. If it has a name, it can be selected by the regular fragment selector. You could also target the image URL directly as the `hasSource`, and use `hasScope` to place it within the context of the page, although this would be ambiguous if the image appeared more than once.

I don't think there's anything in particular to do here.

**Comment by iherman** [comment]
I guess the CSS selector can also be useful...

It seems that the real issue to be solved is #95. I propose to close this one.

**Comment by azaroth42** [comment]
+1 to closing. This is better described in the other issues and is more of a use case for selectors than a specific proposal to discuss.

**Comment by tilgovi** [comment]
Fine to close. I'm going to split out #95, as well, as described in the
comments there.

**Comment by BigBlueHat** [comment]
:+1: Works for me.

**Comment by iherman** [comment]
Closed it on telco: http://www.w3.org/2016/01/27-annotation-irc#T16-32-17-1
