### ISSUE TITLE
Clarify "existing standards" in section 1.1

### ISSUE THREAD

**Issue by jpstroop** [w3c/web-annotation#108]
Minor thing, but under [1.1](http://www.w3.org/TR/annotation-model/#aims-of-the-model)

> ... unless there are existing standards that need to be accommodated or there is a significant cost associated with a method that is otherwise necessary.

Do you mean _un_-necessary? Otherwise I'm not sure how to read this condition.

**Comment by azaroth42** [comment]
The intent was that the method is necessary, and hence the cost is warranted, and hence multiple methods are warranted...  but agree that it reads like the cost is necessary. Will clarify!

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#aims-of-the-model
