### ISSUE TITLE
Narrow `hasScope` to match `as:scope` and introduct `as:context`

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#109]
Related to #102

Apparently (per @tilgovi), Hypothes.is is using `oa:hasScope` to "relate a (arbitrarily deeply nested) reply to the root document context of the thread."

Such that a user agent could query an annotation server by the current URL and find:
1. all the annotations
2. all the replies to those annotations

Here's how we've defined `hasScope` (note the _or_):

> The relationship between a Specific Resource and the resource that provides the scope or context for it in this Annotation.

The includes use case is:

> Zara makes a comment about an image in a particular web page to say that it is not the right organization's logo. Her client includes the page that the image is being rendered in, however the annotation is associated with the image resource itself.

Both this use case and @tilgovi's reply related one would include these expected actions by the annotation user agent:
- given the original annotation
- retrieve any resource(s) that are the `target`
  - an image, a reply, the original document
- if there's a `scope` resource, retrieve that/those also
- present the annotations as much as possible within the context of their creation

:question: So...the _or_ situation works...but should we consider separating them into two properties: `scope` and `context`? (read on! :wink:)

ActivityStreams 2.0 Vocabulary breaks these concepts into two properties:
[`scope`](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-scope)

> Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.

[`context`](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-context)

> Identifies the context within which the object exists or an activity was performed.

Honestly, I've gone 'round and 'round :carousel_horse: on this one... Either seems appropriate. One could consider the "larger work" to be the "total population of entities for which the object can [sic] considered to be relevant" OR one could think of it as "the context within which the object exists or an activity was performed." However, I do believe that (given those), `context` (as defined in AS2) would be more correct for a reply annotation--in that the original document may not actually be available when the reply is made...nor even of interest to the author of the reply annotation.

:thought_balloon:'s?

**Comment by iherman** [comment]
> Related to #102 https://github.com/w3c/web-annotation/issues/102
> Apparently (per @tilgovi https://github.com/tilgovi), Hypothes.is is using oa:hasScope to "relate a (arbitrarily deeply nested) reply to the root document context of the thread."
> 
> Such that a user agent could query an annotation server by the current URL and find:
> 
> all the annotations
> all the replies to those annotations
> Here's how we've defined hasScope (note the or):
> 
> The relationship between a Specific Resource and the resource that provides the scope or context for it in this Annotation.
> 
> The includes use case is:
> 
> Zara makes a comment about an image in a particular web page to say that it is not the right organization's logo. Her client includes the page that the image is being rendered in, however the annotation is associated with the image resource itself.
> 
> Both this use case and @tilgovi https://github.com/tilgovi's reply related one would include these expected actions by the annotation user agent:
> 
> given the original annotation
> retrieve any resource(s) that are the target
> an image, a reply, the original document
> if there's a scope resource, retrieve that/those also
> present the annotations as much as possible within the context of their creation
>  So...the or situation works...but should we consider separating them into two properties: scope and context? (read on! )
> 
> ActivityStreams 2.0 Vocabulary breaks these concepts into two properties:
> scope http://www.w3.org/TR/activitystreams-vocabulary/#dfn-scope
> Identifies one or more entities that represent the total population of entities for which the object can considered to be relevant.
> 
> context http://www.w3.org/TR/activitystreams-vocabulary/#dfn-context
> Identifies the context within which the object exists or an activity was performed.
> 
> I must admit that, within the world of annotations, I struggle making a difference between these two… Which makes me think that we should not, at least for now, differentiate between them.
> 
> Honestly, I've gone 'round and 'round  on this one... Either seems appropriate. One could consider the "larger work" to be the "total population of entities for which the object can [sic] considered to be relevant" OR one could think of it as "the context within which the object exists or an activity was performed." However, I do believe that (given those), context (as defined in AS2) would be more correct for a reply annotation--in that the original document may not actually be available when the reply is made...nor even of interest to the author of the reply annotation.
> 
> 's?

**Comment by BigBlueHat** [comment]
Been chewing on this and I agree with @iherman--the difference is too minimal to be valuable. So closing as `wontfix`.
