### ISSUE TITLE
Define the usage of ‘modified’

### ISSUE THREAD

**Issue by pciccarese** [w3c/web-annotation#111]
We should consider providing non-normative or even normative recommendations for the usage of ‘modified’. 

For example. would it make sense to specifying that the ‘modified’ property can be attached only by the Agent that created the original annotation? Or by the Agents that have authority on it?

That could define boundaries so that when an annotation is stored in an annotation database, the annotation does not get altered in potentially disruptive ways. 

So if we have the annotation:

```
{"id": "urn:uuid:123456-abcd-7890-efgh",
 "type": "Annotation",
 "bodyText": "This is y comment",
 "target": "http://cnn.com/“
 "created": "2015-11-30T00:00:00Z"
}
```

This should not be changed by a third party that edits a typo in their own storage to

```
{"id": "urn:uuid:123456-abcd-7890-efgh",
 "type": "Annotation",
 "bodyText": "This is my comment",
 "target": "http://cnn.com/“
 "created": "2015-11-30T00:00:00Z",
 "updated": "2015-12-01T00:00:00Z"
}
```

Otherwise the same identifier would refer to two different annotations in two different systems.

**Comment by BigBlueHat** [comment]
@pciccarese so, the identifier would still refer to the same annotation (regardless of storage), you just have two systems saying different things about the annotation--in which case it ends up being a matter of who to believe. Correct?

Having an `updated` date at least let's you know when you MAY have something that's not the same set of information as the one you're now holding who's dates are earlier, but I think that's all it does.

Ownership and authority fall outside the meaning (or scope) of this `updated` property.

So...in a way, I'd actually really _want_ any one with a copy of "my" annotation to store a valid, up to date, updated property if/when they changed anything (on my behalf or for their own reasons). I'd also like them to store some more information too (ideally), but I think that's probably out of scope for the Model, but MAY be in scope for the Protocol...maybe.

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#lifecycle-information
