### ISSUE TITLE
Add `mbox_sha1sum` for the same reason(s) FOAF did

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#115]
If `creator` info is publicly available, then the publisher MAY want to obfuscate the user's identifier. FOAF provides for this in the form of `foaf:mbox_sha1sum`:
http://xmlns.com/foaf/spec/#term_mbox_sha1sum

We just don't currently map it into our vocabulary, so to use it, we need to prefix it...like I've done here:
https://bigbluehat.cloudant.com/anno-mail/_design/anno-mail/_show/to-web-annotation/d2f075cd452ecacc143808a976e08271

I'd propose we name "ours" `email_sha1sum` to make it consistent with our relabeling of `mbox` to `email`.

Thoughts?

**Comment by azaroth42** [comment]
Is there a use case beyond a hopefully unique string that identifies the user?  If not ... can't it just go in id, with some URI padding?

**Comment by shepazu** [comment]
I like the use case. There are some new-ish specs around identity and encryption coming into W3C from FIDO (including perhaps a way to sign a JSON file, BTW). I don't know if this is relevant, but my immediate impulse is to make sure whatever we do is future-proof. Maybe we can look deeper at the possible overlap? https://www.w3.org/blog/2015/11/w3c-fido/

**Comment by BigBlueHat** [comment]
@azaroth42 there is not a registered `urn:sha1` nor is there one that states that this one is a `sha1` of a `mailto`, so...while I love the idea of putting this in the `id` field, there's not a current way to do that. It can't (imo) be an HTTP URL because the only "authoritative" URI I have for the user is their `mailto:`--which I was previously storing (and making available to others) in the `email` field.

I could (and perhaps this is what we should recommend) create a local URL for the user (based on a sha1 or whatever I feel like) and use that HTTP URL as the `id`--in which case it would be up to me to decide what I returned there.

The disadvantage here, though, is that as the annotation "moved around" among other annotation systems, the author's annotations could end up with many different `id`'s--vs. this approach of having a consistent way to create what FOAF calls an "indirect identifier"...essentially a "hash tag" (in the original sense ;) ) for that `creator`. All annotation systems creation annotations on behalf of a given email address would then create the same "indirect identifier" which would work in a similar fashion to the UUID we've been discussion for the annotation as a whole--a method of identification that doesn't dictate a required (or even known) interference location.

I'd like to avoid the requirement to store `creator` data in an additional place to annotations made by those creators. It certainly MAY be done, but I think it's out of scope to require that.

**Comment by BigBlueHat** [comment]
@shepazu yeah...that's way more than I had in mind here. :smiley: Also, I'd look to the new Web Payments credentials related work if/when I (personally) needed something that robust.

This is merely a way to state that this annotation was made on behalf of a `creator` who was identified by a certain `email` in scenarios where I don't (and they don't!) want that `email` shared "in the clear" too widely. No more, no less. :smile:

**Comment by BigBlueHat** [comment]
@azaroth42 so...I suppose we could use `ni:///sha-256;{...hash of email...}` per [RFC 6920](https://tools.ietf.org/html/rfc6920#section-9.4), but they don't have (afaict) a registration for sha-1...which means (unless that was done) that there'd be the introduction of yet more names for each email address.

Naming is Hard. :registered:

**Comment by azaroth42** [comment]
I'm not /against/ adding it, by the way, I just want to make sure that there isn't already an existing mechanism that serves the same purpose. I mean role. I mean intent :wink: 

If there was an additional requirement that the URI of a user be kept intact, would that fulfill the use case? It seems like something that could be mandated to at least be owl:sameAs a new URI associated with the user, and any sort of credit or attribution should be against a URI not hopefully unique string.

Then http://example.com/users/(sha-1-of-email) would need to be maintained by conforming systems, and we wouldn't need a new property.

**Comment by BigBlueHat** [comment]
> Then http://example.com/users/(sha-1-of-email) would need to be maintained by conforming systems, and we wouldn't need a new property.

Yeah...it's this last bit that's concerning. I'd like "conforming systems" to not have user management requirements--we don't currently have that requirement, for instance.

Systems managing users should certainly provide an `id` that's (ideally) dereferenceable via HTTP (because _Web_ Annotation). However, my offline ebook reader (re: DPUB use cases) may not have a dereferenceable URI for me...and, frankly, I may not _want_ it to have one that's dereferenceable...or even usable for communication (i.e. `mailto:`), but rather something more like a fingerprint ("signature" being far too strong a word for this idea) that says this annotation and that other annotation bearing this same string (somewhere in it's meaningful package) are all attributable to the same `creator`...even if the data about that creator is "minimal" (i.e. amounting to only this sha1sum of presumably their email address).

Right now, I'm exploring a "Simplest Thing That Could Possibly Work" app which consumes emails as if they were simple annotations and output a Web Annotation per email: https://github.com/bigbluehat/anno-mail
- There's no user system.
- There _are_ user identifiers however (though I'd rather not share them too widely ;) ).
- There's no _need_ (as far as this system is concerned) to create a resource that === the user.
- There _will_ be the ability to see all annotations by a particular `creator` however--identified by either their email address directly or the sha1sum (or similar) of said email address (since that's all the system gets told about the author at this point).

I _could_ create a user URL for each email I receive, but that's an additional burden and out of scope for "Annotation via Email" as a concept.

So, the only thing I'm really trying to solve is have a unique identifier for a `creator` that is not actionable beyond being a thing to filter by later--which is (afaik) precisely the use case described in [FOAF's `mbox_sha1sum`](http://xmlns.com/foaf/spec/#term_mbox_sha1sum) (however geeky that key name may be...).

I'm very open to other options. I just haven't yet found any that don't come with additional requirements beyond "hash this string and put it in your data instead of this other thing." :wink:

**Comment by akuckartz** [comment]
I suppose @bblfish has some suggestions for this issue.

**Comment by BigBlueHat** [comment]
At the end of the day this is really about "do we give this a name for the JSON format" as an graph-based consuming application won't care what it's called...it'll just use the `@context` definition and Do The Right Thing.

Guess we just need to decide where / if this fits (now, etc).

**Comment by iherman** [comment]
I would prefer not to go into a very complicated research here, mainly because many things are changing underneath our feet in this area (like the FIDO spec that @shepazu referred to). Ie, at this moment, we should have a single property whose range we do not define (maybe we will in later releases). Ie, I agree with @BigBlueHat's opinion:

> So, the only thing I'm really trying to solve is have a unique identifier for a creator that is not actionable beyond being a thing to filter by later--which is (afaik) precisely the use case described in FOAF's mbox_sha1sum (however geeky that key name may be...).

Naming is indeed hard, though... In many respect `fingerprint` would be descriptive but people might take it in the literal sense which is not what we want. But maybe that is still the closest...

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#agents
