### ISSUE TITLE
anno-ACTION-29: Create draft proposal for rendering state/selector

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#117]
Bringing over the conversation that started on the mailing list:
https://lists.w3.org/Archives/Public/public-annotation/2015Nov/0226.html

The output of which amounts to:
- `renderedVia` property with the range of `SpecificResource`
- contents of which are expected to be a [`SoftwareAgent`](http://w3c.github.io/web-annotation/model/wd/#h-creation-agents) (as with the value of `generator`)
- with the additional property `schema:softwareVersion` from [Schema.org](http://schema.org/softwareVersion)

I'm not including (post-converation) the `schema:browserRequirements` as it's just a plain text string and has minimal value for strategic anchoring implementations. However, with `schema` in the `@context`, folks can add it if they like--we'd just not alias it, nor invite the use of it directly.

**Comment by azaroth42** [comment]
:+1: to oa:renderedVia with a _domain_ of oa:SpecificResource, and range of prov:SoftwareAgent.  Additionally propose `renderedVia` as the JSON-LD key.

:+1: to schema:softwareVersion, propose `version` as the JSON-LD key.

:+1: to leaving out browserRequirements. We already describe how to include schema terms for Audience.

**Comment by iherman** [comment]
Decision on 2016-02-05, http://www.w3.org/2016/02/05-annotation-irc#T16-31-45

> Add oa:renderedVia, with domain SpecificResource, and no defined Range. Examples would use prov:SoftwareAgent, as per generator

**Comment by BigBlueHat** [comment]
Good work @azaroth42! When should we be closing these? After a call? or after the work is done?

**Comment by azaroth42** [comment]
The process that chairs and staff contacts discussed was that when the issue has been addressed in the document (e.g. the editor action as been taken) then a link to the section is provided in the issue and it can be closed.  The link is needed to demonstrate that the issue was heard, understood and action was taken (or the decision was that no action was needed). 
So ... I think this is at that stage, and I'll add in the link and close :)

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#rendering-software
