### ISSUE TITLE
JSON-LD Context keys

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#12]
The current JSON-LD context maps the ontology predicates directly into the same name in the JSON.  This means that "hasBody" is the key in the JSON, whereas "body" might be more intuitive.  By duplicating the keys, we're missing out on one of the key strengths of JSON-LD in that the serialization looks like JSON.

Proposal:

Rename the keys in the context to be more familiar.

Background:

This was discussed in the CG but rejected.

**Comment by tilgovi** [comment]
:+1:

**Comment by tilgovi** [comment]
I can say nearly for sure that as an implementor I am likely to ignore the official context document and use my own otherwise.

**Comment by tilgovi** [comment]
Also, we might consider snake_case for the JSON representation. I'm sorry if that's a total bikeshed, or if I should open a new issue for it. Not only is it empirically easier to read [1], it's quite popular for APIs and data serializations. ElasticSearch, CouchDB, Riak, MongoDB are all databases with REST APIs that use this convention. Twitter, GitHub, Digg, Facebook all use this convention (a notable exception is Google). While JavaScript convention is typically camelCase, it can be argued that a benefit of snake_case for JSON is that you can clearly distinguish data objects from code objects.

/me ducks :sweat_smile: 

[1] http://ieeexplore.ieee.org/xpl/articleDetails.jsp?reload=true&tp=&arnumber=5521745

**Comment by azaroth42** [comment]
Question for post FPWD as to whether classes should be de-namespaced via the context?

For example:

``` json
{
  "@type": "Annotation"
}
```

Instead of the current:

``` json
{
  "@type": "oa:Annotation"
}
```

**Comment by tilgovi** [comment]
:+1: to de-namespacing

Especially given that we made the decision to use motivations to ease reasoning we have a small number of classes. I don't see any reason not to list them in the `@context` so they can be de-namespaced in the body. That would make the JSON (no LD) _very_ sensible looking to every developer.

**Comment by azaroth42** [comment]
Closing, done.
