### ISSUE TITLE
Documentation error - language code in Example 17 is incorrect

### ISSUE THREAD

**Issue by iainsproat** [w3c/web-annotation#120]
In example 17, section [3.2.2.1](http://www.w3.org/TR/2015/WD-annotation-model-20151015/#textual-body), the example use case states:

> ... it is in French ...

But the example given shows English language:

> "language" : "en"

I was expecting that the example show the following in order to comply with the use case:

> "language" : "fr"

Documentation version referred to in the above is [Web Annotation Data Model, W3C Working Draft 15 October 2015](http://www.w3.org/TR/2015/WD-annotation-model-20151015).

**Comment by azaroth42** [comment]
Agreed, thanks @iainsproat :)

**Comment by azaroth42** [comment]
Fixed: http://w3c.github.io/web-annotation/model/wd2/#embedded-textual-body

**Comment by iainsproat** [comment]
Confirmed resolved. Thanks for fixing @azaroth42
