### ISSUE TITLE
`account` likely to conflict with foaf:account

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#130]
The recommended mapping for `foaf:nick` is `account`.  However there is a `foaf:account` property, which is a relationship to an OnlineAccount that has further properties, rather than the nickname used by the agent.

Consider:   http://xmlns.com/foaf/spec/#term_OnlineChatAccount
Where what we really mean by `account` / `foaf:nick` is `foaf:accountName`.

This is a concern for systems that want to use other foaf properties, as they would need to create strange mappings where account is nick, not account.

Proposal: Consider using `nick`, `nickname`, `handle`, `accountId` instead of just `account`

**Comment by iherman** [comment]
I am not sure where this concerns us. Can you elaborate?

**Comment by azaroth42** [comment]
That if an implementer were to want to expand their user descriptions using other foaf properties, they would need to pick some other JSON-LD key than `account` for foaf:account.  Which would be frustrating and kind of strange.

Happy to close wontfix if we think it's not a big deal.

**Comment by iherman** [comment]
Ah, o.k., I see. I am lukewarm on this. Because we are at the stage when the final form of the JSON-LD version is still being shaped, I do not mind if we use a different property if you have a better alternative. "nick" may not be that appropriate but, after all...

Pick one! :-)

**Comment by iherman** [comment]
Closed on telco: http://www.w3.org/2016/01/27-annotation-irc#T16-48-45

**Comment by BigBlueHat** [comment]
I just tripped over this change while reading through #242 code. Guess I missed the Jan 27th call...

I found the mapping confusing as I'd (personally) not expect `account` value to just be a username/nickname of the user.

Perhaps https://schema.org/alternateName would be clearer?

...but I know this is late game commentary...so...take it with some salt.

**Comment by BigBlueHat** [comment]
@azaroth42 @tilgovi @paolociccarese @iherman do you all remember this discussion from January per chance? :wink: Think it's going to trip up more than me. I'd vote for either `nickname` (for clarity over `nick`) or switching to `alternateName`.

From [FoaF](http://xmlns.com/foaf/spec/#term_nick):

> Property: foaf:nick
> nickname - A short informal nickname characterising an agent (includes login identifiers, IRC and other chat nicknames).

(see...they even use `nickname` in the description! :wink: )

From [Schema.org](https://schema.org/alternateName):

> An alias for the item.

I'd vote for `nickname` in the JSON-LD replacing `account` and keeping the mapping to `foaf:nick` (as `schema:alternateName` seems less...committal. :grin: 

@iherman @azaroth42 I'm only not re-opening this as I'm not sure what the proper policy/process is in cases like this one. (apologies if I'm Doing It Wrong)

**Comment by iherman** [comment]
As I said before, I am lukewarm about this... I go either way. No objection to `nickname`
