### ISSUE TITLE
Add diagrams to Vocab examples

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#131]
While I think that the model/serialization doc is cleaner without the model diagrams, especially given the new JSON focus, I think it would be good to reinstate the diagrams in the vocab document.  

That is, however a lot of work, and it would be good to have consensus on it before sitting down for a couple of days at the Omnigraffle mines.

**Comment by iherman** [comment]
I like diagrams:-) I believe having them in the vocab document is appropriate and o.k. Indeed, probably not in the JSON serialization document, though.

**Comment by csarven** [comment]
+1 to keeping diagrams! Personally I don't fancy reading JSON (Turtle is a lot more intuitive for me), so, the diagram is a good fallback if need to - and I suspect that others feel the same, especially if they don't grok any given syntax. So, even if the examples were in Turtle, I'd say it is good to have the diagrams, simply more welcoming to dive into.

**Comment by jjett** [comment]
I'm with csraven. Turtle is more intuitive to me and as a visual thinker it's easier and faster for me to grok diagrams. If you like I can volunteer to help with this aspect of the documentation process. 

So +1 for keeping diagrams from me.

**Comment by akuckartz** [comment]
Can an Open Standard be used for the diagrams please?

**Comment by iherman** [comment]
Omnigraffle is an authoring tool… the images in the current document are in PNG, I do not believe that would change (we may want to have it in SVG, too, which, afaik, Omnigraffle can also produce)

**Comment by azaroth42** [comment]
Example diagrams for feedback:
- http://w3c.github.io/web-annotation/vocab/wd/#annotation
- http://w3c.github.io/web-annotation/vocab/wd/#choice

The SVG versions follow the pattern:  http://w3c.github.io/web-annotation/vocab/wd/images/examples/annotation.svg but I'm not sure how we would link them and the export is ... not perfect.

**Comment by iherman** [comment]
> On 24 Feb 2016, at 00:52, Rob Sanderson notifications@github.com wrote:
> 
> Example diagrams for feedback:
> 
> http://w3c.github.io/web-annotation/vocab/wd/#annotation http://w3c.github.io/web-annotation/vocab/wd/#annotation
> http://w3c.github.io/web-annotation/vocab/wd/#choice http://w3c.github.io/web-annotation/vocab/wd/#choice
> The SVG versions follow the pattern: http://w3c.github.io/web-annotation/vocab/wd/images/examples/annotation.svg http://w3c.github.io/web-annotation/vocab/wd/images/examples/annotation.svg but I'm not sure how we would link them and the export is ... not perfect.

Indeed; it is strange that it has cut part of the figure… What is the original file it exports from?

As for the link issue: the way we did it, lately, in the CSVW document is to link to the svg file (simply via the `img` element) and added a note in the caption that the PNG (and the SVG) file can be accessed directly (see, for example, https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#metadata-format https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#metadata-format). 

However, there are two caveats with this: (1) we may not have a caption for each diagram and (2) if we have a lot of these (and we have), loading and displaying each SVG file may take some time, which is a pain. If we go down that route, it is probably worth trying to simplify the diagrams in terms of visual tricks, eg, removing the shadow effects.

Another possibility is to do it the other way round: have the PNG image in the file and a link to the SVG. It is a shame that we still may have to do that in 2016…

B.t.w., if we use SVG, we have to remove the width and height attributes in the svg element (and replace it with a viewBox if necessary, although it is also present in the svg file you referred to). That makes the graphics rescale automatically. (It is again a shame that this is still a problem, most of the editors still do this. The latest release of Illustrator has finally allowed one to set a preference to generate a really re-scalable graphics, but I am not sure many other tools do that…)

**Comment by azaroth42** [comment]
Assigning Paolo in an attempt to make progress while Rob deals with actions from the F2F, Benjamin doesn't have access to Omnigraffle

**Comment by BigBlueHat** [comment]
I found this https://github.com/ccnmtl/graffle2svg

Do we have the OmniGraffle documents somewhere? We should at least get them into a repo so that anyone with time can contribute--ideally. :smile:

**Comment by azaroth42** [comment]
All done, will open a postponed issue for SVG.
