### ISSUE TITLE
Format should use the vocabulary of mime types

### ISSUE THREAD

**Issue by gsergiu** [w3c/web-annotation#133]
The definition of Format field in external resources 
http://www.w3.org/TR/annotation-model/#external-resources
references to the RFC which defines the format of the format values.
https://tools.ietf.org/html/rfc6838

However there is already a standard vocabulary for mime types which is think is a better reference than the currently referenced RFC. (the RFC is reference in the following document as well.)
http://www.iana.org/assignments/media-types/media-types.xhtml

for additional info see 
https://en.wikipedia.org/wiki/Media_type

**Comment by gsergiu** [comment]
this is similar an can be solved together with #134

**Comment by azaroth42** [comment]
I don't believe the media types list is able to be normatively referenced, as it isn't a stable document. It gets updated at irregular intervals and there's no versioning.  So the RFC is the best we can do, as far as I know.  Happy to be corrected if this is not the case .... @iherman?

**Comment by gsergiu** [comment]
Yes .. with the versioning you have a point in not making it normative.
Still we could write a non normative note that the annotations SHOULD use this vocabulary.

Von: Rob Sanderson [mailto:notifications@github.com]
Gesendet: Dienstag, 12. Januar 2016 17:49
An: w3c/web-annotation
Cc: Gordea Sergiu
Betreff: Re: [web-annotation] Format should use the vocabulary of mime types (#133)

I don't believe the media types list is able to be normatively referenced, as it isn't a stable document. It gets updated at irregular intervals and there's no versioning. So the RFC is the best we can do, as far as I know. Happy to be corrected if this is not the case .... @ihermanhttps://github.com/iherman?

**Comment by iherman** [comment]
Hm. To be honest, I am not sure either. In fact, rfc6838 only defines the syntax of the format, as far as I can see, but it does not contain any specific values.

I think going along the line of @gsergiu should work, though. We leave the current text as is, because it just says that the value must follow the syntax in rfc6838, and we add a note (non normative) that refers to the other document making it clear what its status is, i.e., that it contains the currently registered types and that it is constantly extended. "Extended" is the operative word here, ie, applications may safely use a media type once it is registered because, afaik, it is never removed.

**Comment by iherman** [comment]
We will refer to https://www.iana.org/assignments/media-types/media-types.xhtml from the document.

Decision on call 2016-02-05, http://www.w3.org/2016/02/05-annotation-irc#T16-37-50-1

**Comment by gsergiu** [comment]
great thanks!

**Comment by azaroth42** [comment]
There is a reference in respec to the document already [[RDF-MIME-TYPE]] but it's from the perspective of the RDF/XML specification: https://www.w3.org/TR/REC-rdf-syntax/#ref-iana-media-types 

In that document it is a _normative_ reference, so we have a precedent :)
</sleuthing>

**Comment by iherman** [comment]
> On 17 Feb 2016, at 23:44, Rob Sanderson notifications@github.com wrote:
> 
> There is a reference in respec to the document already [[RDF-MIME-TYPE]] but it's from the perspective of the RDF/XML specification: https://www.w3.org/TR/REC-rdf-syntax/#ref-iana-media-types https://www.w3.org/TR/REC-rdf-syntax/#ref-iana-media-types
> In that document it is a normative reference, so we have a precedent :)

Except that your reference is not the latest version of that Rec, it has been superseded in 2014, and the _same_ reference has been moved as an informative reference in:

https://www.w3.org/TR/rdf-syntax-grammar https://www.w3.org/TR/rdf-syntax-grammar

(alias https://www.w3.org/TR/2014/REC-rdf-syntax-grammar-20140225/ https://www.w3.org/TR/2014/REC-rdf-syntax-grammar-20140225/)

:-) However, there is a note about this in the same document at

https://www.w3.org/TR/rdf-syntax-grammar/#h2_section-MIME-Type

we could just reuse that...

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#external-web-resources
