### ISSUE TITLE
Multiple States

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#135]
(Splitting from #93)

Issue: If you have both an HttpRequestState and a TimeState, then it is unclear as to whether a client should interpret this as a choice between the two States, or that both should be applied.   For example, if there is a resource that provides content negotiation in format, and there is a particular time at which the annotation should be applied, then both would be needed.  Alternatively, if there is a copy provided somewhere, then either using the HTTP headers or just using the copy would be valid.  

This could be described with List/Choice, but the model does not specify this.

Proposal: Following on from #93, add `subState` along the lines of `subSelector`.  Do the first State, and then do the State refered to by subState. If there are multiple States referenced directly, then they are different alternatives.

**Comment by iherman** [comment]
I am o.k. with consistency with #93.

**Comment by azaroth42** [comment]
As the use case is pretty weak, I propose to include it in Vocabulary, but not clutter the model document with it.  Then we have consistency and a way for people to use it if needed, but haven't added something of dubious value to wade through.

Thoughts?

**Comment by iherman** [comment]
I am not sure what you mean. Is it so that `subState` will appear as an RDF term in the vocabulary, but will not be included in the Model document? Or that the example does not appear in the model, but the term does?

I am o.k. with the latter, but I have problems with the former.

**Comment by azaroth42** [comment]
I meant the former (e.g. there would be an entry in the -vocab list, but not a section in the -model document).  I'll add a section in -model.

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#refinement-of-state
