### ISSUE TITLE
No context description found in the JSON-LD "Complete Example"

### ISSUE THREAD

**Issue by tkanai** [w3c/web-annotation#136]
I think it is worth to show how to write "@context" in the "complete" example (Example 63).

**Comment by azaroth42** [comment]
:+1: Thanks Takeshi!

**Comment by azaroth42** [comment]
Fixed in:
  http://w3c.github.io/web-annotation/model/wd2/#complete-example
:)

**Comment by azaroth42** [comment]
(Done, closing issue)
