### ISSUE TITLE
Editorial issues on the model version 2016-01-16

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#140]
- [x] "Fragment URI": is this an official term out there? I do not think so. The first sentence in section 3.2.3 does have some sort of a definition for this, but it is not clear...
- [x] The term "External Resource" is used, but it is never properly defined... Nor is the term "Web Resource" for that matter. 
- [x] Related to the two issues above: it may be a good idea to have a terminology section up front where we attempt to define terms like Fragment URI, external resources, web resources, etc. 
- [x] We may want to make it explicit that `"body" : "url"` is actually a valid shorthand for something like `"body":{"id":"url"}`. It just appears in the examples but I did not see anything explicitly mentioning it. Actually, this pattern appears elsewhere (e.g., for creators): we may want to define the shorthand in general with the usage of `@id`. (I guess in Turtle this was an obvious thing, so it is for JSON-LD, but we try not to rely on that knowledge...)
- [x] Section 4.2., and the example, suggests that I may have a selector defined somewhere else, with a URI, and refer to that. Ie, it can be abstract and user defined. I am fine with this, but it may be worth calling that out explicitly (and also making it clear that, most of the time, we use embedded objects as selectors...). The same comments holds for section 4.3. This may be linked to the previous issue.
- [x] I am not sure I like the header "Web Resources". At first reading I thought we are talking about something very different than in the next section, and then I realized that we are talking about different aspects of bodies and targets (through the full of section 3.2). I am not sure how to name this, though, we may want some editorial discussion on this.
- [x] I do not know what this means: "and is NOT RECOMMENDED for uses where the content of the body has any intellectual value" in section 3.2.5. What do you mean by "intellectual value"?
- [x] I believe we should use CSS Selector level 3, and not 2.1. This is now a Recommendation: https://www.w3.org/TR/2011/REC-css3-selectors-20110929/
- [x] Section 4.2.2: Text Quotation Selector -> Text Quote Selector
- [x] Section 4.3.1: descriptoin -> description
- [x] Section 4.4. referring to CSS2 only may be restrictive. Not sure what the best reference would be, though, because there is no single reference for CSS3. Maybe the CSS snapshot: https://www.w3.org/TR/css-2015/ but that is only 2015... Maybe some general handweaving referring to any CSS modules that are Recs.
- [x] Section 5.3.1: the example has a different style (colour)?

**Comment by azaroth42** [comment]
Fixed ... Can't really link every bullet though?
