### ISSUE TITLE
Restriction on 'purpose'

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#142]
In section 3.3.4 of the model document: why is 'purpose' restricted to textual bodies?

**Comment by azaroth42** [comment]
Because in order to associate it with an external web resource, it needs to be associated with a Specific Resource, not the resource directly.  See: http://w3c.github.io/web-annotation/model/wd2/#purpose-for-external-web-resources

**Comment by iherman** [comment]
You missed my point. Why not assigning a pupose to a body that is a video?

**Comment by azaroth42** [comment]
You can do that ... using a Specific Resource. I'm clearly missing your point, sorry!

(And you have to do it that way, per the Role discussion, because the same video might have different purposes in different annotations)

**Comment by iherman** [comment]
Ok, you are right but I also realized what led me down the wrong path. 

You do have an example for what you say in [4.1](https://w3c.github.io/web-annotation/model/wd2/#h-purpose-for-external-web-resources). And yes, that section "defines" `purpose` to be usable for such a resource. However, in [3.3.4](https://w3c.github.io/web-annotation/model/wd2/#h-motivation-and-purpose), where `purpose` is first defined, it says, as part of the definition: "The relationship between a TextualBody and a Motivation." This can be read as a formal definition for that property which has a restriction. In fact, you have the definition of that property at two different places! (Yes, I realize, those are not really definitions but...)

The whole of section 3.3 talks about different properties and many of those can be used for Specific Resources, ie, for bodies in general. However, so far in the narrative there is nothing about specific resources, and I have not seen some sort of a reference back to 3.3 (eg, in the introduction of Specific Resource in section 4) that makes this clear.

Maybe, as I proposed earlier, we should have an intro section with a terminology for external resource, web resource, specific resource, etc, making clear how these things interrelate. It could also make it clear that the properties are defined for a specific type of object but those definitions are not meant to be exclusive for the property.

B.t.w., just to add to your headache, I believe an index for the classes and properties, to be put into an appendix, would be a good idea, too. I believe respec has tools for definitions and reference to the definitions that is relatively easy to use (and generates cross links automatically). (We can discuss the technical details.) 

(I changed the issue to be editorial, though)

**Comment by azaroth42** [comment]
:+1: to terminology section and back ref from 4.1 to 3.3.

Not so keen on the index -- that seems like the vocab doc repeated in the model doc.  Perhaps we can link to examples in model from vocab?

**Comment by iherman** [comment]
> On 21 Jan 2016, at 00:08, Rob Sanderson notifications@github.com wrote:
> 
>  to terminology section and back ref from 4.1 to 3.3.
> 
> Not so keen on the index -- that seems like the vocab doc repeated in the model doc.
> 
> Would be much less formal. A bit like the table in the CSS spec: a list of classes and terms, linked back to the places where they are defined. The example on 'purpose', and my misunderstanding, shows that the plural in 'places' is important…

Again, it is not necessarily for this round. But I think it would be useful on the long run.

> Perhaps we can link to examples in model from vocab?
> 
> That is a good idea in any case, but that is a different issue; JSON users will not (necessarily) look at the vocab document.

**Comment by azaroth42** [comment]
Okay, I could see that.  An index of the places in which a key in the JSON is used, as opposed to the semantics of the predicate that key represents.

**Comment by azaroth42** [comment]
Added the index, complete modulo lists: http://w3c.github.io/web-annotation/model/wd2/#index-of-json-keys
