### ISSUE TITLE
Intervals in time states?

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#143]
At present, Time state only refers to one point in time. Wouldn't it be possible/useful to allow for a time interval as an alternative? Or define a separate state for an interval?

**Comment by azaroth42** [comment]
Same response as for #141.  If we can't validate a single datestamp, we'll end up with junk.  And I don't think we want to require explicit typing.

**Comment by iherman** [comment]
> Same response as for #141. If we can't validate a single datestamp, we'll end up with junk. And I don't think we want to require explicit typing.
> 
> True, the two are linked. But not fully: if we keep to dateTime, defining a start and end, ie, an interval, is still possible. This aspect is independent from #141.

**Comment by azaroth42** [comment]
To reframe/clarify the issue:

TimeState only allows a single point in time, whereas the representation may be valid across a known time interval.  For example, in Wikipedia it is possible to accurately calculate all of the dates when the representation is appropriate to the annotation, as the entire history of a resource is available.  

Proposal:

Add sourceDateStart, sourceDateEnd properties that have a W3CDTF (with at risk status, falling back to xsd:dateTime) to convey the interval.  Any representation between the two dates is valid for the annotation.

**Comment by iherman** [comment]
Thanks. This sounds perfect to me.

> To reframe/clarify the issue:
> TimeState only allows a single point in time, whereas the representation may be valid across a known time interval. For example, in Wikipedia it is possible to accurately calculate all of the dates when the representation is appropriate to the annotation, as the entire history of a resource is available.
> 
> Proposal:
> 
> Add sourceDateStart, sourceDateEnd properties that have a W3CDTF (with at risk status, falling back to xsd:dateTime) to convey the interval. Any representation between the two dates is valid for the annotation.

**Comment by azaroth42** [comment]
NickStenning: What's the proposed behaviour if sourceDateStart/sourceDateEnd are provided at the same time as sourceDate?

**Comment by iherman** [comment]
Telco discussion 2016-02-12: approve to do it.

See http://www.w3.org/2016/02/12-annotation-irc#T16-22-26

**Comment by azaroth42** [comment]
Re @nickstenning comment, propose that implementations MUST NOT have both sourceDate and the interval, and that both start and end MUST be provided.

**Comment by iherman** [comment]
> On 19 Feb 2016, at 21:36, Rob Sanderson notifications@github.com wrote:
> 
> Re @nickstenning https://github.com/nickstenning comment, propose that implementations MUST NOT have both sourceDate and the interval, and that both start and end MUST be provided.

+1

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#time-state
