### ISSUE TITLE
Style selector vs. Styles

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#144]
We do introduce the separate "Styles" in the model, but the use cases listed in the section could be covered by a Style Selector. Do we really need the separate concept of Styles?

**Comment by jjett** [comment]
Related to this, I'm still not sure why a body cannot be used to annotate a target with CSS instructions. The use case is no different from the text editing one. (I do understand that allowing such a thing nullifies the bodiless annotation use case, which is probably a good thing.)

**Comment by azaroth42** [comment]
Yes we need the distinction. Selectors /select/ the segment of interest. Styles provide a style for the rendering of the resource / segment.

**Comment by azaroth42** [comment]
Will make the text around styles clearer.

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#styles
