### ISSUE TITLE
Referring to Content in RDF

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#146]
The "Content in RDF" vocabulary will not advance, I believe; the EARL WG has not been rechartered and I do not think the vocabulary has a traction. I think we should remove the references.

**Comment by azaroth42** [comment]
We should discuss how to ensure the ease of migration / upgrading from the CG's work (that does use cnt) and the WG model.  The intent of referring to it (informatively) was that we can clearly align our work as the successor to the defunct Content in RDF work.

**Comment by iherman** [comment]
> On 19 Jan 2016, at 18:45, Rob Sanderson notifications@github.com wrote:
> 
> We should discuss how to ensure the ease of migration / upgrading from the CG's work (that does use cnt) and the WG model. The intent of referring to it (informatively) was that we can clearly align our work as the successor to the defunct Content in RDF work.

Then we can create an informative appendix describing the mapping. But not in the main text.

**Comment by azaroth42** [comment]
Removed: http://w3c.github.io/web-annotation/vocab/wd/#namespaces (and subsequent entries in the list)
