### ISSUE TITLE
Validation of FragmentSelector Value

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#148]
From https://www.w3.org/annotation/track/issues/7

Is it possible, and if not is it desirable, to be able to validate the values of FragmentSelectors against the specification that it is claimed to conform to?

For example, if a Selector claims that it conforms to the text/plain fragment syntax, and it is actually random characters, is it (a) possible to detect, and (b) is there anything that we need to do?

My proposal is that this is an implementation concern, and that given the conformsTo link, it would be possible to construct a validation suite.  Thus we should close #7 (in the W3C tracker) and this one.

**Comment by iherman** [comment]
> On 5 Feb 2016, at 20:30, Rob Sanderson notifications@github.com wrote:
> 
> From https://www.w3.org/annotation/track/issues/7 https://www.w3.org/annotation/track/issues/7
> Is it possible, and if not is it desirable, to be able to validate the values of FragmentSelectors against the specification that it is claimed to conform to?
> 
> For example, if a Selector claims that it conforms to the text/plain fragment syntax, and it is actually random characters, is it (a) possible to detect, and (b) is there anything that we need to do?
> 
> My proposal is that this is an implementation concern, and that given the conformsTo link, it would be possible to construct a validation suite. Thus we should close #7 https://github.com/w3c/web-annotation/issues/7 (in the W3C tracker) and this one.

Let alone the fact that we are open ended, ie, new fragment definitions come to the fore; meaning that we never have a fully compliant implementation if this becomes part of the core requirements and tests.

Ie, I think this should be closed without further ado

**Comment by iherman** [comment]
Issue closed per telco 2016-02-12

See http://www.w3.org/2016/02/12-annotation-irc#T16-26-08
