### ISSUE TITLE
Range Selector

### ISSUE THREAD

**Issue by tilgovi** [w3c/web-annotation#153]
For discussion, I present a proposal for a range selector. The purpose of this selector is to generalize the selection of the content described by a range from a start point to an end point, without constraining the means of describing either.

This proposal is a reaction to, and result of discussion about, an XPath selector as described in #95.

Repeating an excerpt of my comments there as a starting point for discussion, I believe the following benefits are offered:
- Flexible in that it can utilize any existing selector type for its start and end
- Allows a construction that closely matches a DOM Range

And the following negative complexity is introduced:
- Increases the number of objects and depth of the graph another level

**Comment by tilgovi** [comment]
I also believe that a generic range selector offers semantic benefits for certain kinds of selection, as compared with existing selectors for the same content.

For instance, a range selector that identifies sentence `A` with a text quote and sentence `B` with a text quote could continue to accurately describe a passage even with the insertion or removal of intervening sentences. Whether or not the selection still accurately captures the author's intent is out of scope and unknowable, but having the power to express a range with this sort of robustness is simply what is proposed here.

**Comment by azaroth42** [comment]
:+1: to the functionality. Let's discuss the details :smile_cat: 

To try and make this slightly more concrete, is the proposal to allow:

```
{
  "type": "RangeSelector",
  "startSelector": {
    "type": "FragmentSelector",
    "value": "startId"},
  "endSelector": {
    "type": "FragmentSelector",
    "value": "endId"}
}
```

With the semantics being that the selection is from the beginning of `source.html#startId` until the ... beginning? ... of `source.html#endId` ?

Thus a new class oa:RangeSelector (subClassOf oa:Selector), and two new relationships oa:hasStartSelector, oa:hasEndSelector (both with domain oa:RangeSelector, range of oa:Selector)

Note that they can't be just start and end, as they're already in use for TextPositionSelector (https://www.w3.org/TR/annotation-model/#text-position-selector)

**Comment by iherman** [comment]
> On 19 Feb 2016, at 19:14, Rob Sanderson notifications@github.com wrote:
> 
>  to the functionality. Let's discuss the details 
> 
> To try and make this slightly more concrete, is the proposal to allow:
> 
> {
>   "type": "RangeSelector",
>   "startSelector": {
>     "type": "FragmentSelector",
>     "value": "startId"},
>   "endSelector": {
>     "type": "FragmentSelector",
>     "value": "endId"}
> }
> With the semantics being that the selection is from the beginning of source.html#startId until the ... beginning? ... of source.html#endId ?
> 
> Thus a new class oa:RangeSelector (subClassOf oa:Selector), and two new relationships oa:hasStartSelector, oa:hasEndSelector (both with domain oa:RangeSelector, range of oa:Selector)
> 
> Note that they can't be just start and end, as they're already in use for TextPositionSelector (https://www.w3.org/TR/annotation-model/#text-position-selector https://www.w3.org/TR/annotation-model/#text-position-selector)

I am fine with this. There is only so many ways of doing this, and this seems to be an obvious one.

**Comment by tilgovi** [comment]
Fine for me, as well. And since it was my desired to represent a DOM Range and those are inclusive start, exclusive end, that maps well for me.

**Comment by iherman** [comment]
Discussed on telco 2016-02-26, and accepted it

See: http://www.w3.org/2016/02/26-annotation-irc#T16-28-17
