### ISSUE TITLE
Extension Capacity

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#154]
One of the advantages of using JSON-LD is the built in extensibility mechanisms. One of those is allowing the definition of new terms via adding them in a second or subsequent context file.  We currently allow only a single context, the Open Annotation one, thereby cutting off this benefit at the Annotation level.

Proposal:  Require the current context document, but allow more than one.

For reference, the ActivityStreams work has an entire section on extensibility that we could crib from, if we wanted to be more explicit: https://www.w3.org/TR/activitystreams-core/#extensibility

**Comment by iherman** [comment]
+1

Admin comment: this is the type of (in my view, fairly uncontroversial) issue that we may be able to decide on email or issue (by requesting enough +1 comments), without using telco time...

**Comment by akuckartz** [comment]
:smile:

**Comment by tilgovi** [comment]
:+1:

**Comment by azaroth42** [comment]
Proposal:  Extension section should include:
- Use JSON-LD for extensions -- NB this re-introduces JSON-LD into the -model document, which has been otherwise excised to -vocab
- Call out multiple contexts on the Annotation as the way to do that
- Ignore unknown keys, or unexpected values, rather than erroring out

Need a recommendation for internationalization of strings, rather than resource content?

**Comment by iherman** [comment]
@azaroth42

> Proposal: Extension section should include:
> - Use JSON-LD for extensions -- NB this re-introduces JSON-LD into the -model document, which has been otherwise excised to -vocab

Sigh. We should be indeed very careful in the way we formulate this, because bare JSON processors should still be o.k. with all this. I would think that, first of all, this is something for an appendix, not the main text (the latter should simply allow for more than one `@context` and stop of that). We should also make it clear that extensions are to be provided by particular implementations, and their usage may damage interoperability. Finally, I wonder whether we should not move the details on how to do extensions to the vocabulary document altogether rather than keeping it in the model document.

> - Call out multiple contexts on the Annotation as the way to do that

Yes and, if my previous note flies, just refer to the vocab document for people who want to do and know more

> - Ignore unknown keys, or unexpected values, rather than erroring out

Yes

> Need a recommendation for internationalization of strings, rather than resource content?

I am not sure I understand. JSON uses UTF-8, what else do we need at this point? How does this relate to I18N?

**Comment by azaroth42** [comment]
:+1: to moving extensions to -vocab and just allowing multiple contexts (without further explanation of why you might do that) in -model.

The i18n issue is if you want to provide /within the annotation/ multiple values for a property in different languages, then it would be lovely if there was a recommended way to do that as there are several possibilities within JSON-LD.

For example, if you wanted to have a label for an Annotation, with versions in English and French there are at least:

1:

```
{
  "type": "Annotation",
  "label": [ {"@language": "en", "@value": "Commentary"}, 
                {"@language": "fr", "@value": "Commentaire"}]
}
```

2:

```
{
  "type": "Annotation",
  "label": {"en": "Commentary", "fr": "Commentaire"}
}
```

3:

```
{
  "type": "Annotation",
  "label_en": "Commentary",
  "label_fr": "Commentaire"
}
```

Each with different pros and cons.

**Comment by iherman** [comment]
>  to moving extensions to -vocab and just allowing multiple contexts (without further explanation of why you might do that) in -model.
> 
> The i18n issue is if you want to provide /within the annotation/ multiple values for a property in different languages, then it would be lovely if there was a recommended way to do that as there are several possibilities within JSON-LD.
> 
> Ah, that one? Wouldn't it be better to put this in another issue? Is it related to the extension capacity?
> 
> For example, if you wanted to have a label for an Annotation, with versions in English and French there are at least:
> 
> 1:
> 
> {
>   "type": "Annotation",
>   "label": [ {"@language": "en", "@value": "Commentary"}, {"@language": "fr", "@value": "Commentaire"}]
> }
> 2:
> 
> {
>   "type": "Annotation",
>   "label": {"en": "Commentary", "fr": "Commentaire"}
> }
> 3:
> 
> {
>   "type": "Annotation",
>   "label_en": "Commentary",
>   "label_fr": "Commentaire"
> }
> Each with different pros and cons.

**Comment by iherman** [comment]
Discussed and accepted at telco 2016-03-04 ("Add extension section to vocab not model, proposing the use of multiple json-ld contexts")

See: http://www.w3.org/2016/03/04-annotation-irc#T16-37-22

**Comment by iherman** [comment]
Extra discussion (on same call): "Remain silent about i18n of extension properties, as it is covered by JSON-LD already"

See: http://www.w3.org/2016/03/04-annotation-irc#T16-46-10

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/vocab/wd/#extensions

**Comment by iherman** [comment]
Having looked at the model document (2016-03-18), one more request. At this moment, the possibility of adding extensions is mentioned only in passing, so to say, in a Note in section 4.5. I think this type of note (almost with the same content, actually), should be put elsewhere in the document to draw attention on this possibility in general. Maybe at the top of section 3.3.

I also wonder whether the example used in section 4 of the Vocabulary document is indeed the best. Is there a better example that is relevant to the basic model and not to collections? 

Cc: @azaroth42

**Comment by azaroth42** [comment]
:+1: to additional note in 3.3. That's a great place for it.  Happy to change example (it was from #184) if we can describe a better one?
