### ISSUE TITLE
Problem with Example Use Case in section 3.2.1

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#155]
The Example Use Case states:
Beatrice records a long analysis of a patent, and publishes it on her web site as an mp3. She then creates an Annotation with the PDF as the body, and the patent as the target.

Should probably be:
She then creates an Annotation with the mp3 as the body, and the PDF patent as the target.

**Comment by azaroth42** [comment]
:+1: Fixed

**Comment by paolociccarese** [comment]
Fixed with Merge pull request  https://github.com/w3c/web-annotation/pull/172 from w3c/editorial
