### ISSUE TITLE
Would change 'site' to 'website' in Use Case in section 3.2.2

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#156]
Just to make sure there is no confusion with physical sites or locations that could be also annotated.

**Comment by azaroth42** [comment]
:+1: Fixed, and standardized throughout on "website" rather than "site" or "web site"

**Comment by paolociccarese** [comment]
All occurrences done :+1: 

Fixed with Merge pull request  https://github.com/w3c/web-annotation/pull/172 from w3c/editorial
