### ISSUE TITLE
Clarification on sentence in section 3.2.5

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#157]
In the the sentence 
Systems may rewrite Annotations to instead use this pattern, rather than maintaining the bodyText form.

It is not immediately clear what "this pattern" means. I would change to:
Systems may rewrite Annotations to instead use Textual Body, rather than maintaining the bodyText form.

**Comment by azaroth42** [comment]
:+1: Fixed, and linked to the embedded textual body section.

**Comment by paolociccarese** [comment]
Rob, I am not sure about the use of 'separate' there. I would probably simplify to "use the TextualBody construction,".
