### ISSUE TITLE
"created, modified or generated" might be confusing

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#159]
Section 3.3 cites the three concepts of creation, modification and generation.

While the three concepts are later explained, it might be worth clarifying right away what 'generation' means.

Maybe something like: creation, modification and generation (of serialization)

**Comment by azaroth42** [comment]
:+1: Fixed

**Comment by paolociccarese** [comment]
Fixed with Merge pull request  https://github.com/w3c/web-annotation/pull/172 from w3c/editorial
