### ISSUE TITLE
Creator "may be either a human or software agent"

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#160]
In section 3.3.1, in the 'creator' definition we state 
This may be either a human or software agent. 

Later in section 3.3.2 we list Organization as a possible class for Agent.

Should we edit the sentence above to:
This may be either a human, an organization or software agent.

**Comment by azaroth42** [comment]
Good catch! :+1: to listing Organization in 3.3.1. Fixed

**Comment by paolociccarese** [comment]
Fixed with Merge pull request  https://github.com/w3c/web-annotation/pull/172 from w3c/editorial
