### ISSUE TITLE
Type in Example Use Case in section 3.3.4

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#161]
The Example Use Case starts with:
Example Use Case:Jane annotates a resource

Whitespace missing after ':'

Same problem for Example Use Cases of sections: 3.3.5 and 3.3.6

**Comment by azaroth42** [comment]
:+1: Fixed

**Comment by paolociccarese** [comment]
Fixed with Merge pull request  https://github.com/w3c/web-annotation/pull/172 from w3c/editorial
