### ISSUE TITLE
Section 3.3.6 Example Use Case wording

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#162]
The fragment:
She wants to ensure that it the copies can be aligned, and so sets a UUID
should probably be
She wants to ensure that the copies can be aligned, and so she sets a UUID

Removed an 'it' and added a 'she'.

**Comment by azaroth42** [comment]
:+1: Fixed

**Comment by paolociccarese** [comment]
Fixed with Merge pull request  https://github.com/w3c/web-annotation/pull/172 from w3c/editorial
