### ISSUE TITLE
Note after fragments list table is not consistent

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#163]
Between the 'NOTE' header and the content there is an empty line that was not present in all the previous notes.

Same problem with the following notes.

**Comment by azaroth42** [comment]
Some notes were <div> and some were <p>.  I've regularized them all to <div>.
:+1: Fixed

**Comment by paolociccarese** [comment]
Fixed with Merge pull request  https://github.com/w3c/web-annotation/pull/172 from w3c/editorial
