### ISSUE TITLE
Note in section 4.2.4 expansion?

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#164]
In the note we state that the "Text Position Selector" is very brittle with regards to changes to the resource. Any edits may change the selection, and thus it is recommended that a State be ...

However, I wonder if we should warn also about things that change in a webpage due to other dynamic components such as advertisements...

**Comment by azaroth42** [comment]
:+1: Added clause to the note about dynamically transcluded content

**Comment by paolociccarese** [comment]
Fixed with Merge pull request  https://github.com/w3c/web-annotation/pull/172 from w3c/editorial
