### ISSUE TITLE
Conformance clause

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#165]
All the documents should have a conformance clause. In general, this may be very harmless and simple, like 

https://www.w3.org/TR/tabular-data-model/#conformance

and most of it can be generated through the `<section id="conformance">` idiom in respec. However, as the discussion on the telco showed, there are aspects of conformance that needs WG discussion...

Because it affects implementations, this should be done before entering CR.

**Comment by iherman** [comment]
(This is a purely editorial remark!)

The latest editor's draft (dated Febr 19) has a conformance section in 6.2, as a subsection to Extensions and conformance. Two issues with that:
- The conformance section is usually (though indeed not always) set as its own top level section, somewhere at the top of the document. I would propose to turn this into section 3.
- At present, the boilerplate on the usage of rfc2119 is part of the terminology section. That should be part of conformance and, actually, is automatically generated by respec if the section's `@id` is set to conformance

**Comment by azaroth42** [comment]
Proposed approach:  Determine a set of features that are supported by the model and protocol. Then for each feature come to consensus around whether a client MUST, SHOULD or MAY implement it. 

For some parts, this is easy ... supporting the core of the Annotation MUST be implemented (id, type, hasBody, hasTarget).  For others it's much less easy ... SHOULD you support CSS Selectors or XPath selectors, which for some scenarios are very useful (annotations on HTML content) but for others are meaningless (annotations on basically everything else).

**Comment by iherman** [comment]
> Proposed approach: Determine a set of features that are supported by the model and protocol. Then for each feature come to consensus around whether a client MUST, SHOULD or MAY implement it.
> 
> Alternatively, or rather additionally, we may define 1-2 'profiles' of Annotations with the features it contains or not. Ie, say, for OA Basic this and this feature is a MAY, whereas for OA Full is a MUST.

I would restrict to a small number, otherwise it becomes more complicated. I am tempted to try for a choice between MAY and MUST, and aim for two, or maximally three profiles.

> For some parts, this is easy ... supporting the core of the Annotation MUST be implemented (id, type, hasBody, hasTarget). For others it's much less easy ... SHOULD you support CSS Selectors or XPath selectors, which for some scenarios are very useful (annotations on HTML content) but for others are meaningless (annotations on basically everything else).

**Comment by iherman** [comment]
Discussed on 2016-03-11: Conformance section will be defined by listing the required selector/states per media types for various classes of agents (server, client)

See: http://www.w3.org/2016/03/11-annotation-irc#T16-49-59

**Comment by azaroth42** [comment]
Progress: Changed terminology sections to be auto-including conformance sections. Still need to work out the media type / capability matrix, and I propose not to delay WD publication for that

**Comment by iherman** [comment]
Have made a spin-off of this issue (#203) concentrating on the media / selector matrix.

@azaroth42 : should we close this issue, because #203 takes it over?

**Comment by azaroth42** [comment]
Yep, let's close this and focus on #203. Thanks @iherman!
