### ISSUE TITLE
Additional terminology issues: relationship, property, instance...

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#166]
This, I believe, is related to the (still missing) terminology section of issue #140 

The document makes a difference between "Relationship" and "Property". This comes from the RDF ancestry, differentiating between a Literal and Object Property. Whilst that differentiation makes sense for RDF, of course, I wonder whether it makes sense in the JSON version. After all, everything that is on the left hand side of a ":" is a "name" in JSON parlance... On a similar vein, we also have the differentiation between "Class" and "Instance". 

We should consider: 
- Do we need all these terms (in JSON)? Can't we get away with, say, only properties?
- If we do need these different terms, then they must be clarified in the terminology section.

**Comment by iherman** [comment]
An additional terminology that must be detailed in my view: we often have this type of statement, e.g.:

> email  Relationship  Each agent MAY have 1 or more email addresses

We should make it clear that this means the value of the property is either a string or an array of strings in JSON.

**Comment by azaroth42** [comment]
I think we need them. The implication of a relationship is that the value will be one of:
- string that contains a URI
- array of URI strings
- object that has an id ... err ... relationship
- array of objects
- mixed array of URI strings and objects

Whereas a property has a data type that should be expressed in the document (such as a regular string, an integer, a W3CDTF, and so on)

I'll add the distinction to the terminology section.

**Comment by iherman** [comment]
> On 22 Feb 2016, at 23:53, Rob Sanderson notifications@github.com wrote:
> 
> I think we need them. The implication of a relationship is that the value will be one of:
> 
> string that contains a URI
> array of URI strings
> object that has an id ... err ... relationship
> array of objects
> mixed array of URI strings and objects
> Whereas a property has a data type that should be expressed in the document (such as a regular string, an integer, a W3CDTF, and so on)
> 
> I'll add the distinction to the terminology section.

O.k. I am fine with this if it is clearly specified in the terminology section.

**Comment by azaroth42** [comment]
I believe this is fixed by:
    http://w3c.github.io/web-annotation/model/wd2/#serialization-of-the-model

But please re-open if that's insufficient.
