### ISSUE TITLE
Do we allow the extension of clases?

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#167]
Do we allow extensions by adding additional Classes? (See also issue #154). If so, this should be mentioned. In section 3.2.2.

Rationale: it is not always clear in which of the five classes a specific media type belongs, and there may be cases where it does not belong really to any of those. Eg, MathML, or MusicXML... We should not try to categorize all of these, which may be corner cases, but maybe allow an extension...

**Comment by azaroth42** [comment]
:+1: I think if we allow extensions (per #154) then that gives us this for free. The one thing we should be clear on is that the Annotation class MUST be present, even if the resource has other classes also assigned.

**Comment by azaroth42** [comment]
Which is already in the doc (MUST have the type, MAY have other types) ... Not sure there's any actual action required, @iherman?

**Comment by iherman** [comment]
The current text says

> The Body or Target MAY have exactly 1 type, and if so, the value SHOULD be drawn from the list below.

I do not see the "MAY have other types" there. Maybe, if #154 is implemented, there can be a general statement saying that in all such situations there MAY be extensions.

**Comment by tilgovi** [comment]
Whatever language we should have that makes it clear it is acceptable should be there, because there is _no_ way we can stop people.
