### ISSUE TITLE
Write constraints document

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#173]
For: http://www.w3.org/TR/annotation-protocol/constraints

To be referenced from the protocol, link rel=constrainedBy

**Comment by azaroth42** [comment]
The requirement comes from here: https://www.w3.org/TR/ldp/#ldpr-resource (section 4.2.1.6)

Proposal: Use the spec as the constraints document, as it does have the set of constraints we expect the server to abide by. If the server has further constraints, then it's up to the server to express them.

```
Link: <http://www.w3.org/TR/annotation-protocol>;rel="http://www.w3.org/ns/ldp#constrainedBy"
```

**Comment by iherman** [comment]
It took me a while to understand what you mean:-) but now I think I get it. Indeed, using a link of the type

> http://www.w3.org/TR/annotation-protocol/constraints

is not a good idea; that URI does not dereference. Using the URI of the spec itself seems to be good enough.

Bottom line: +1 from me.

**Comment by azaroth42** [comment]
Not sure we need to spend telco time on this?  Please raise concerns here in the issue if you have any, otherwise I'll close it on March 3rd :)

**Comment by akuckartz** [comment]
Accessing http://www.w3.org/TR/annotation-protocol/constraints still results in a 404 error.

**Comment by azaroth42** [comment]
Hi @akuckartz ... right, because the proposal is to use the URL of the spec instead of having a specific document that would essentially just repeat information from the spec :)  Closing, given no objections.
