### ISSUE TITLE
Document annotation service endpoint rel

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#174]
In Protocol we refer to:
  http://www.w3.org/ns/oa#annotationService

Given the namespace, this is part of the ontology, and should be defined somewhere.  Or it should not have the namespace as its prefix, and instead refer elsewhere.

**Comment by iherman** [comment]
> On 23 Feb 2016, at 21:21, Rob Sanderson notifications@github.com wrote:
> 
> In Protocol we refer to:
> http://www.w3.org/ns/oa#annotationService http://www.w3.org/ns/oa#annotationService
> Given the namespace, this is part of the ontology, and should be defined somewhere. Or it should not have the namespace as its prefix, and instead refer elsewhere.

The simplest approach is to be part of the vocabulary. In RDF terms, it is a 'Resource', ie, something like 'annotationService a rdf:Resource', and leave it at that...

**Comment by iherman** [comment]
Discussed at telco 2016-03-04: Use the vocabulary for the purpose

See also: http://www.w3.org/2016/03/04-annotation-irc#T16-52-49-1

**Comment by azaroth42** [comment]
In the spirit of alignment ... I reached out to the schema.org community about how they would include this. The wider the understanding and implementation of the discovery links, the more use and acceptance the WG's work will get.

So while the inclusion of annotationService in vocab is easy, there are some options for how to align it with other work.  

SIOC (http://rdfs.org/sioc/spec/#sec-modules) has a services module, that defines a Service (A Service is web service associated with a Site or part of it.) and svcs:has_service (A Service associated with this SIOC object.).  The has_service predicate has no defined domain, but a comment for rdfs:Resource, so it seems appropriate.  However ... I'm not sure if we can and should use it.
If we do, it would be very easy:  `oa:annotationService rdfs:subPropertyOf svcs:has_service .`

Schema has `Service` (A service provided by an organization, e.g. delivery service, print services, etc.) which is too broad, and `ServiceChannel` which is not quite right either (A means for accessing a service, e.g. a government office location, web site, or phone number.).  In particular, the `ServiceChannel` has a predicate `serviceUrl` with range of URL, for where to go to use it.  Atypically for schema.org, this model seems far too complex.  It would require some property chain to get from resource to Service to ServiceChannel to serviceUrl :(

Thoughts?

**Comment by azaroth42** [comment]
Progress: http://w3c.github.io/web-annotation/vocab/wd/#annotationservice

**Comment by azaroth42** [comment]
AS has a `Service` class (https://www.w3.org/TR/activitystreams-vocabulary/#dfn-service) but only `instrument` that uses it.  Given responses on the schema.org list, I propose to mint new terms in our own namespace:
- oa:annotationService subPropertyOf sioc-services:has_service
- which is a sioc-services:Service, and equivalently an as:Service

**Comment by iherman** [comment]
> AS has a Service class (https://www.w3.org/TR/activitystreams-vocabulary/#dfn-service https://www.w3.org/TR/activitystreams-vocabulary/#dfn-service) but only instrument that uses it. Given responses on the schema.org list, I propose to mint new terms in our own namespace:
> oa:annotationService subPropertyOf sioc-services:has_service
> which is a sioc-services:Service, and equivalently an as:Service

Something seems to be missing here… :-)

I understand the role of the former in the protocol. I must admit I am not sure I fully understand the role of the second; maybe it is worth some explanation.

**Comment by azaroth42** [comment]
Sorry! Service is the range of has_service, so we're saying that the range of annotationService is a sioc-services:Service. I don't see any problem with doing that. We can just be silent about it.

**Comment by iherman** [comment]
@azaroth42, what I do not really understand is what this is used for. Per se, it looks like a harmless information to add, I agree, but is it something authors are expected to add somewhere, that implementers must provide, etc. I just do not see the consequences.

**Comment by BigBlueHat** [comment]
@iherman I think it's only real value is for scenarios where a publisher of the primary content also wants to be the preferred storage provider of the annotations--i.e. the current blogging world and most ebook publishers, etc.

It reads currently as a statement of availability and preference--which is good. Requiring it would have other unnecessary...requirements. :smile:
