### ISSUE TITLE
Remove TextPositionSelector in favor of RangeSelector?

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#177]
Assuming #153 is acceptable, do we want to instead have a text position selector that selects a character offset, and use two of them with a RangeSelector to duplicate the effects? The same would apply to DataPositionSelector.  (Both of which are really (Text/Data)RangeSelectors, not single positions anyway)

Thus, the current way:

```
{
  "type": "TextPositionSelector",
  "start": 10,
  "end": "15
}
```

Would become:

```
{
  "type": "RangeSelector",
  "startSelector": {
    "type": "TextPositionSelector",
    "position": 10
  },
  "endSelector": {
    "type": "TextPositionSelector",
    "position": 15
  }
}
```

I'm not really in favor as it makes more work for no real gain, but having one way to do things is better than having two and making implementers choose, so I'm throwing it out there.

**Comment by tilgovi** [comment]
I'd be fine with it, but others might find it verbose. We could also amend the existing selectors to make the end properties optional. In their absence, it should be treated as a zero-width point.

**Comment by tilgovi** [comment]
With the amendment I just mentioned, it would be possible to use the selectors as you've shown, but also possible to use them as ranges when that serves.

Maybe having more than one way to do things isn't great, though.

**Comment by iherman** [comment]
Discussed at telco 2016-02-26: resolved to leave as is

See: http://www.w3.org/2016/02/26-annotation-irc#T16-34-42
