### ISSUE TITLE
Acknowledgement section content and change section

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#179]
The acknowledgement section in the current editors' draft (Febr 19) only refers to the community group and it also lists the differences between the CG document and this one. It is also usual to acknowledge the Working Group (by, eg, listing all its members by name, or at least its active members' by name) and possibly others who have been active in the issues and comments, albeit not being members of the group.

Another issue is that, from now on, we will have to document the changes of the document in future releases; 'horizontal' reviews like A11y or others usually like to have that around. 

I would propose to:
- Create a separate 'changes' (informative) section which would contain, for now, the differences between the OA document and this one (instead of being in the Ack. section)
- Leave the acknowledgement to the community group in the Ack. section, and add a reference to the WG and others as mentioned above (It is of course fine not to list the names for now and just have this as a placeholder and it may be done later when the document is final)

**Comment by fhirsch** [comment]
+1 to summarizing changes from CG to appendix

Typically on each publication the Status of this Document should include a text summary of the major changes as well as a link to a diff - a best practice.

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#acknowledgements
