### ISSUE TITLE
Link from AnnotationCollection to target(s) of included Annotations?

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#184]
This came up in the IIIF use of collections (lists) of Annotations [1], so I'll raise it here too for consideration.

If you have a set of AnnotationCollections, each with some reasonably large number of Annotations in them, it would be a practical improvement to not require the client download all of the lists just to determine which of them contain annotations that target the resource(s) of interest.  Instead the annotation collection could optionally link through to the target of the annotations.

Essentially this is the propertyChain of from AnnotationCollection through AnnotationCollectionPage to the individual Annotations in items, to each hasTarget, and then potentially also down to hasSource if the target is a specific resource.

I understand the value of this in terms of the interaction patterns and optimization, but equally could be premature optimization. Any thoughts as to the value would be appreciated :)

[1] AnnotationList and forCanvas: https://github.com/IIIF/iiif.io/issues/754

**Comment by azaroth42** [comment]
I'm fine with postponing, just wanted to raise it and see what people thought.  It's also something that could easily be added as an extension for experimentation.

**Comment by BigBlueHat** [comment]
:+1: to keeping it in the extension space. The narrower our focus right now, the better. :shipit:

**Comment by iherman** [comment]
Discussed on 2016-03-11:  Add an informative note in extension section calling this use case as an example, if need be later would be revisited.

See: http://www.w3.org/2016/03/11-annotation-irc#T16-20-58

**Comment by azaroth42** [comment]
Decision to change the example, so closing this issue.
