### ISSUE TITLE
Usage of 'dc:' in the model document?

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#185]
I was a bit surprised, in section 5.1 of the latest version of the model document (2016-03-18) the example using `dc:description`. On the one hand, it is perfectly fine to use it and, from a strict JSON-LD point of view it is also correct, because the `dc` prefix, ie, CURIE-s using `dc:` are fine according to our `@context` file. However, this is the only place I believe in the document when this mechanism is used; we usually use a pure term (and the corresponding mapping) in the `@context` file.

I am perfectly file adding the term `description`, mapping to `dc:description` into the section on `Other properties` (3.3). But it is not a property that really fits into any of the subsections of that section, which is a bit awkward. Maybe a new subsection with some more common dc terms listed is the best of option (`subject`, `title`, ?). 

Alternatively, remove that term from the example, because it is, in fact, what we now call an extension. 

Cc: @azaroth42

**Comment by azaroth42** [comment]
:+1:

Also, with #184, how about two examples in extensions -- one of just using a property from an ontology that's already got a prefix defined in the context (such as dc:description), and then a second one where a new context is needed (suggestions welcome? on `telco`?)

**Comment by azaroth42** [comment]
Closing, as it's now all in the extensions as it should be :)
