### ISSUE TITLE
Minor pre-publication issues (2016-03-19)

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#186]
I have scanned through the three document purely from an editorial point of view. I have some comments below on things that should be done before publication. None of these are technical, ie, they bear no influence on the CFC. 

Here they are:
- [x] We should add, for Benjamin, "Invited Expert" as an affiliation, instead of leaving it empty.
- [x]  I am surprised that almost all the references are listed as "informative". I do not think that is correct. I would think that all references to a standard, made from a normative section, should be, as a rule, normative. There might be some cases when this is not true, but I guess it is a good rule of thumbs. (In `respec`, this means that you have to use `[[!REF]]`, instead of `[[REF]]`)
- [x]  For accessibility reasons, we should be careful how we treat figures. The 'alt' tag must be meaningful (Saying "Basic Annotation Model" may not say much I guess). I know this is difficult. We can also add a `@longdesc` and point to a fragment within the text that is shown in the figure. That may work well for the diagrams in the vocabulary, simply pointing at the corresponding turtle example.
- [x]  It is probably a good idea to add a reference to issue #165 in the conformance clause of the model document, making it clear that we are working on something here...
- [x]  Maybe worth adding a note in the section on diagrams in vocab, making it clear that more are coming in later releases...
- [x]  I wonder whether it is not worth, in the status section of the model document, to explicitly call out the 'feature at risk', namely the date format. Formally speaking this is to be done in the CR phase only, but putting it there already now does not harm.
- [x]  In the vocab, the new example using exif (example 98): please add a reference to exif (isn't it EXIF, b.t.w.?), and it may be worth emphasizing that the width and height values are the ones coming from exif
- [x]  in the protocol spec, there is no conformance section. At the minimum, it should contain the standard text on MUST, MAY, etc, that you are used in the other two documents
- [ ]  I get a bunch of horizontal scroll bars in the protocol spec, due to the new TR style. I wonder whether it is possible to slightly reformat the examples to avoid those...
- [x]  The Acknowledgement section of the protocol spec should be updated to include the same text as the other two documents...
- [ ]  I have received comments before if a document contained no 'changes since the last version' section. I realize it would be extremely complicated to do that for the model document, although, maybe, a set of high level description of the changes would be good. But for the future versions, however, we should be prepared to include a more detailed changes' section, too.

Cc: @azaroth42 @BigBlueHat @paolociccarese

**Comment by azaroth42** [comment]
I can't get the scroll bars to appear. Note the wrapped link on the second line of the example:

<img width="692" alt="screen shot 2016-03-19 at 3 15 39 pm" src="https://cloud.githubusercontent.com/assets/871868/13901564/7d6d19aa-ede5-11e5-92c6-ac012f13d7d5.png">

Not sure why we get different behavior. Could be browser specific? (Chrome on MacOS)

**Comment by iherman** [comment]
Very strange. Here are the screen dumps for me of the same example in Firefox _and_ Chrome, both on Mac! No idea why this is different on the same OS and also the same browser...

Never mind for now. This is a mystery we may want to deal with later

<img width="806" alt="screen shot 2016-03-20 at 05 12 29" src="https://cloud.githubusercontent.com/assets/520723/13902812/b3b1a4ca-ee5a-11e5-9f48-c13c2ccb0a49.png">
<img width="847" alt="screen shot 2016-03-20 at 05 13 44" src="https://cloud.githubusercontent.com/assets/520723/13902813/b668c3ba-ee5a-11e5-8d79-4ccc000b80e1.png">
