### ISSUE TITLE
Change of document title: why?

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#189]
I just realized that what we usually refer to as the 'model' document in our discussions:

http://w3c.github.io/web-annotation/model/wd2/

bears the title "Web Annotation", as opposed to "Web Annotation Data Model", which is the title of the previous version:

https://www.w3.org/TR/2015/WD-annotation-model-20151015/

Any reason why the title has changed? I would proposed we use the old title which still perfectly fit the document as it is today.

(To be clear: per process the title _may_ be changed, ie, my comment is not procedural.)

Cc: @azaroth42

**Comment by azaroth42** [comment]
A bug :)  It was from when we were discussing the split between model and vocabulary, and when our thinking changed, I didn't revert it. Will fix.

**Comment by iherman** [comment]
O.k. This must be done for the 2016-03-31 version of the document, though (not yet there...)

Cc: @azaroth42

**Comment by azaroth42** [comment]
Done.
