### ISSUE TITLE
Can I refine a state via a selector?

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#195]
At the moment, selectors and states can be both refined with another selector and a state, respectively. There is no word whether I can (or cannot) mix these two.

Proposal: 
1. It is possible to use `refine` on a State but referring to a Selector. Ie, I apply, say, a fragment id on a resource that I retrieved with a specific time stamp
2. It is not allowed to use a refine via a state on a selector. (I would not know exactly what that means...)

**Comment by azaroth42** [comment]
I'm nervous that would lead to two different methods to describe the same process.  The first (as above) with a state refined by a selector, and the second being hasState / hasSelector on the SpecificResource directly.  As we can't mandate a state, the second way seems preferable to me.

I would prefer to keep only states refining states, and selectors refining selectors.

**Comment by iherman** [comment]
I have no strong feelings. I have a slight preference for allowing No. 1 above, but will not lie down the road as they say; let us see what others say.

In any case, it is worth making this clear in the text one way or another. I will not be the only person asking this question...

**Comment by azaroth42** [comment]
Definitely we should be clear! Happy to go with what people think is best :)

**Comment by pciccarese** [comment]
I would be ok with No. 1 but I also have hard time in envisioning mainstream use cases for it. 

I was thinking at news websites that now tend to add the newest details on top of the article (see CNN.com) and publish always in the same page. According to the selector of choice, the new content might or might not have an impact on the outcome. However, I still don't see if that is fertile ground for No. 1. 

Maybe a situation where the publishing system of a website changed after a specific date and old and new content are coexisting?

@iherman any use case you were thinking of?

Meanwhile, I will be ok in having No.1 but put a note saying that is not necessarily stable?

**Comment by iherman** [comment]
> On 28 Mar 2016, at 18:20, Paolo Ciccarese notifications@github.com wrote:
> 
> I would be ok with No. 1 but I also have hard time in envisioning mainstream use cases for it.
> 
> I was thinking at news websites that now tend to add the newest details on top of the article (see CNN.com) and publish always in the same page. According to the selector of choice, the new content might or might not have an impact on the outcome. However, I still don't see if that is fertile ground for No. 1.
> 
> Maybe a situation where the publishing system of a website changed after a specific date and old and new content are coexisting?
> 
> @iherman https://github.com/iherman any use case you were thinking of?

Well, the obvious example is if I want to annotate the second page of a PDF version of a document as it was on january first. The obvious way to do this would be to use a State to retrieve a document dated Jan 1, refined by the request of getting a PDF over, say, HTML, and the refined by a _Selector_ (a FragmentSelector) for the 2nd page using the PDF media fragment.

**Comment by pciccarese** [comment]
I guess I was overthinking. That seems to me the basic use case that motivated the introduction of States. I think I am missing the nuance. Is that because of the order of refinement in the wording?

**Comment by iherman** [comment]
> I guess I was overthinking. That seems to me the basic use case that motivated the introduction of States. I think I am missing the nuance. Is that because of the order of refinement in the wording?

Schematically, what I said can be translated into:

State:
    a TimeState
    date: january 1st
    refinedBy:
        HttpRequestState
        accept format PDF
        refinedBy:
            FragmentSelector
            select 2nd page

But that can be done only if the last refinedBy is allowed, ie, refine a State with a Selector. At this moment it is not clear whether this is allowed, it is certainly not explicitly said, and Rob's position seems to be to disallow this

**Comment by azaroth42** [comment]
I would represent that as:

```
{
  "type": "SpecificResource",
  "state": {
    "type": "TimeState",
    "sourceDate": "2016-01-01",
    "refinedBy": {
      "type": "HttpRequestState",
      "value": "Accept: application/pdf"
    }
  },
  "selector": {
    "type": "FragmentSelector",
    "value": "page=2"
  },
  "source": "http://example.com/negotiable/dynamic"
}
```

Where the specific resource has the selector on it, rather than the state. But I agree that the pattern Ivan suggests is more accurate, as if you have not retrieved the PDF, then selecting the second page of it is meaningless and potentially dangerous (if page=2 matches an anchor of the HTML, for example)

**Comment by iherman** [comment]
> On 29 Mar 2016, at 18:20, Rob Sanderson notifications@github.com wrote:
> 
> I would represent that as:
> 
> {
>   "type": "SpecificResource",
>   "state": {
>     "type": "TimeState",
>     "sourceDate": "2016-01-01",
>     "refinedBy": {
>       "type": "HttpRequestState",
>       "value": "Accept: application/pdf"
>     }
>   },
>   "selector": {
>     "type": "FragmentSelector",
>     "value": "page=2"
>   },
>   "source": "http://example.com/negotiable/dynamic"
> }
> Where the specific resource has the selector on it, rather than the state. But I agree that the pattern Ivan suggests is more accurate, as if you have not retrieved the PDF, then selecting the second page of it is meaningless and potentially dangerous (if page=2 matches an anchor of the HTML, for example)

Actually (sorry, I am on my mobile) doesn't the text says somewhere that if there are several stetes/selectors, then they are _alternatives_? If so, what you write is definitely not the same...

Ivan

**Comment by azaroth42** [comment]
Currently, each item in a set of states is an alternative (e.g. avoiding an explicit choice node for those states) and the same for a set of selectors, but we don't say (and should) how to interpret them.

We used to have:

> It is expected that if a State is present, it will be processed first to ensure the correct representation is retrieved. Then, if there is a Selector, it would be applied to determine the correct segment of the representation. Finally, if there is a Style, it would be applied to ensure the correct rendering or the resource or segment. As Scopes do not affect the rendering directly, they may be processed in any way deemed appropriate for the user interface or application.

And even further back had a workflow diagram, but it was seen as too prescriptive.

**Comment by pciccarese** [comment]
So we go down to two choices:
1. keep it as is, maybe with the old text that establishes the order of interpretation
2. allow to encode the order in the structure

In general, even with the State, if I cannot retrieve that exact representation (which I am assuming will be very common case), I don't have assurance the annotation is still valid or not dangerous.

**Comment by tilgovi** [comment]
That we are discussing here whether the `refinedBy` property shared by `State` and `Selector` allows the nesting of one in the other only furthers my belief, which I've stated elsewhere, that `State` and `Selector` are not disjoint classes. Whether by time, space, or representation, there is a goal to refine a target. Whether certain refinements are nonsensical, ambiguous, or otherwise pose difficulties is not that concerning to me, provided there are common constructions that unambiguously handle common use cases.

I'm sorry to do this again because it seems to cause some stress, but I wish to ask once more: why are `hasState` and `hasSelector` different?

**Comment by iherman** [comment]
> On 29 Mar 2016, at 19:54, Rob Sanderson notifications@github.com wrote:
> 
> Currently, each item in a set of states is an alternative (e.g. avoiding an explicit choice node for those states) and the same for a set of selectors, but we don't say (and should) how to interpret them.
> 
> We used to have:
> 
> It is expected that if a State is present, it will be processed first to ensure the correct representation is retrieved. Then, if there is a Selector, it would be applied to determine the correct segment of the representation. Finally, if there is a Style, it would be applied to ensure the correct rendering or the resource or segment. As Scopes do not affect the rendering directly, they may be processed in any way deemed appropriate for the user interface or application.
> 
> And even further back had a workflow diagram, but it was seen as too prescriptive.

Just a thought experiment: what if we _disallow_ having both state and selector in the same place, but have refined by allowed in the way I proposed? It strikes me that the scheme you describe in that quote could be made much clearer by referring to refinedBy and imposing some (fairly understandable) restrictions, eg, not to refine a selector by a state…

I have not looked at style. At first glance it looks o..k. to refine a selector by a style but not to define refinedBy for style.

**Comment by azaroth42** [comment]
States describe the representation (or state) of the resource that is desired.  Once the processor has that representation, the Selector describes the part of the representation that is being annotated.  So there is (still) a difference between the two classes.

They're alternatives only within a single predicate ... you can do either State A or State B, and then you do Selector C ... rather than you can do any of State A, State B or Selector C.

The refinement is of the process of selecting part of the resource (or the process of retrieving a representation of the resource), not of the resource itself.

**Comment by iherman** [comment]
@azaroth42 : 

> States describe the representation (or state) of the resource that is desired. Once the processor has that representation, the Selector describes the part of the representation that is being annotated. So there is (still) a difference between the two classes.

I am personally fine with this, hence I am fine keeping the current separation. One could debate whether 'state' is the best term, but finding anything else would be bikeshedding. No need for it now.

As for the original issue: I still believe the simple approach in [my comment](https://github.com/w3c/web-annotation/issues/195#issuecomment-203239919) would work well:
1. disallow state and selector appearing in the same object in parallel (otherwise we will have to give some formal definition on priority of these, something that is not in the document)
2. allow the refinement of a state by a selector

We achieve the same effect (first extract the resources with, eg, HTTP restrictions, then select part of the resource), without any further complication in the specification.

**Comment by tilgovi** [comment]
Rob, thank you.

I accept that the handling of state and selector happens in different phases in the course of common annotation interactions. You've described this well and your description helpfully reveals the assumptions we have that seem to justify the separation, that a state is used to fetch a representation and then a selector specifies a segment of that representation.

I can, however, imagine uses where arbitrary refinement simplifies processing. In archival situations, where many versions of a single URL might already be available, the selector vocabulary could be leveraged for search. Perhaps I want to reference the set of archived versions of some document that contain some particular text. I could represent this query in a structured way using this vocabulary.

Separating the terms perhaps simplifies processing and renders the intent clearer for our common use cases. Structurally, it flattens the graph a bit by lifting selector out from a refinement of the state (if any). If questioning this is unappealing to everyone, I am not too bothered, but I find it interesting to consider. There is an elegance to the unification to my brain.

**Comment by iherman** [comment]
> On 19 Apr 2016, at 08:45, Randall Leeds notifications@github.com wrote:
> 
> Rob, thank you.
> 
> I accept that the handling of state and selector happens in different phases in the course of common annotation interactions. You've described this well and your description helpfully reveals the assumptions we have that seem to justify the separation, that a state is used to fetch a representation and then a selector specifies a segment of that representation.
> 
> I can, however, imagine uses where arbitrary refinement simplifies processing. In archival situations, where many versions of a single URL might already be available, the selector vocabulary could be leveraged for search. Perhaps I want to reference the set of archived versions of some document that contain some particular text. I could represent this query in a structured way using this vocabulary.
> 
> Separating the terms perhaps simplifies processing and renders the intent clearer for our common use cases. Structurally, it flattens the graph a bit by lifting selector out from a refinement of the state (if any). If questioning this is unappealing to everyone, I am not too bothered, but I find it interesting to consider. There is an elegance to the unification to my brain.=
> 
> Referring to the original issue that triggered this discussion (whether it is possible to refine a state with a selector), the inverse may not make too much sense. The selector typically means selecting from a resource that is already acquired via HTTP, whereas the state typically restricts what is really retrieved, ie, influences the server. In this sense, I do not really see how it would make sense to refine a selector with a state.

_If_ we decided to merge the concepts of states and selectors, we would have to separate them again defining for each structure how it can be refined, to account for the aforementioned situation. Ie, we would end up defining a subdivision again:-( In contrast, in my mind (provided we go ahead with this cross-refinement of a state by a selector) the situation becomes conceptually simple with the current separation...

**Comment by azaroth42** [comment]
> As for the original issue: I still believe the simple approach in my comment would work well:
> - disallow state and selector appearing in the same object in parallel (otherwise we will have to give some formal definition on priority of these, something that is not in the document)
> - allow the refinement of a state by a selector

I'm not keen, as it means that you couldn't reuse a State in different Annotations, they would always be tied together with the Selectors. It would also be inconsistent with the way styles and the other aspects of SpecificResources work. To disallow both hasState and hasSelector on the same specific resource seems like a big change, compared to just allowing Selectors to be refined by other Selectors, and States to be refined by other States.

**Comment by iherman** [comment]
I actually realized I was misunderstandable, my mistake. What I meant was not to have two states or two selectors in one place. At the moment it is not defined what this means. We also have to define formally what it means to have state _and_ selector in one place, by the way.

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by azaroth42** [comment]
PROPOSED RESOLUTION:  Allow a State to be refined by a Selector.

Rationale: Different states could result in different representations, that would need different selectors to work with them.  For example, if the representation delivered is a PDF, compared to HTML, from the same URI, then the FragmentSelector to pick the paragraph would be different.  Both might be useful as part of the same annotation, as the content is the exactly the same, just in different formats.

[And separating the can we have both hasState and hasSelector at the same time to a different issue]

**Comment by iherman** [comment]
+1

**Comment by jjett** [comment]
+1

**Comment by iherman** [comment]
Discussed on 2016-04-29: turn it into editor's action, accepting the latest proposal

http://www.w3.org/2016/04/29-annotation-irc#T15-51-10
