### ISSUE TITLE
Choice should have a priority order

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#2]
Currently, oa:Choice only allows two priorities for informing clients about the intended preference, the default option and all other alternatives. There is no order of preference within the alternatives. This may be desirable for gracefully degrading across a list of selectors, or representations with decreasing fidelity for body or target.

**Justification**

The proposal would allow more flexibility, without any increase in overhead.  It addresses use cases where there is more priority information available than just a default and a set of equal alternatives, such as q values in HTTP or other prioritization systems.

**Proposal**

Have a single rdf:List of all the choices in descending priority order.

``` JSON
{
  "@type": "oa:Choice",
  "hasList": ["default", "secondChoice", "thirdChoice"]
}
```

**Dependencies**
- Depends on #1 for serialization of the list, and for consistency

**Background**

oa:Choice is needed for the following requirements:
- Alternative bodies, where the user agent selects the most appropriate for the user based on preferences. For example translations of the body, and the user has set a language preference.
- Alternative targets, where the same target has multiple URIs or identities. Only one target needs to be displayed, rather than all of them.
- Alternative selectors to enable fallback scenarios where a very exact selector will work in some cases, but a more broad selector will be less precise but work in other cases, given a dynamic representation.

**Comment by jjett** [comment]
It seems like this approach works very well if we want to be proscriptive about which body/target/selector to use; however, if proscription is the goal, then why offer choices at all? I'm wondering if it wouldn't be better to go the opposite direction and not proscribe a default and punt the whole problem over to the consumer, i.e., they select their choice of resource for that annotation. With things like content negotiation this seems like something of a solved problem. The consumer has a default representation that they prefer to consume.

**Comment by azaroth42** [comment]
I don't think it's proscriptive, but descriptive. Here is the ordered list (proposed) of items that you can choose between.  Content negotiation doesn't solve the issue between different servers, or embedded resources.  The client can always make a choice amongst the resources, the default/item or ordered list is a server hint for which to use in the absence of other factors.

**Comment by azaroth42** [comment]
Resolved in FPWD
