### ISSUE TITLE
Should oa:start / oa:end be xsd:nonNegativeInteger or xsd:integer ?

### ISSUE THREAD

**Issue by stain** [w3c/web-annotation#200]
It was `xsd:nonNegativeInteger` in the OA spec, so I'm leaving oa.ttl at that - however https://www.w3.org/TR/2016/WD-annotation-vocab-20160331/#start and https://www.w3.org/TR/2016/WD-annotation-vocab-20160331/#end says `xsd:integer`.

As the position integer can't be negative, why are we now suggesting xsd:integer?

Anyway, the json-ld context should specify such a `@type`.

**Comment by azaroth42** [comment]
I'm fine with making them nonNegativeInteger in the ontology and documentation. Not sure about specifying in the context ... I'd like to see the effects of doing that when expanding and compacting.

For example, if the compaction results in `{@value: 1, @type: "xsd:nonNegativeInteger"}` instead of just `1`, that would be a pain for everyone with no gain.

**Comment by stain** [comment]
I would hope the context made RDF that was valid according to the ontology - so if we want to change it in JSON-LD it should be updated also in the ontology (even if a negative number here would be confusing - some might think it is like in Python from the end?).

JSON-LD playground examples:

``` json
{
  "@context": {
    "ex": "http://example.com/vocab#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "ex:start": {
      "@type": "xsd:integer"
    }
  },
  "@id": "http://example.com/",
  "ex:start": 1566
}
```

Expanding this yields:

``` json
[
  {
    "@id": "http://example.com/",
    "http://example.com/vocab#start": [
      {
        "@type": "http://www.w3.org/2001/XMLSchema#integer",
        "@value": 1566
      }
    ]
  }
]
```

However if you leave out `@type` in the context it is expanded as:

``` json
[
  {
    "@id": "http://example.com/",
    "http://example.com/vocab#start": [
      {
        "@value": 1566
      }
    ]
  }
]
```

Both yield the same triple

http://example.com/ http://example.com/vocab#start "1566"^^http://www.w3.org/2001/XMLSchema#integer .

**Comment by stain** [comment]
But on **compaction** with that context it becomes correctly without  `@value`:

``` json
{
  "@context": {
    "ex": "http://example.com/vocab#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "ex:start": {
      "@type": "xsd:nonNegativeInteger"
    }
  },
  "@id": "http://example.com/",
  "http://example.com/vocab#start": 1566
}
```

**Comment by azaroth42** [comment]
Yup, looks good to me :)

**Comment by iherman** [comment]
Meeting 2016-04-22: close the issue, move it to editorial

See http://www.w3.org/2016/04/22-annotation-irc#T15-49-35

**Comment by BigBlueHat** [comment]
Change to be made on vocab, context, and model documents.

**Comment by BigBlueHat** [comment]
Also, we're going to do this for all values previously stated to be `xsd:integer`.
