### ISSUE TITLE
Selector/media table

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#203]
I have put up an [initial table](http://w3c.github.io/web-annotation/model/medias.html) for media types and selectors (see PR #202). This issue is a spin-off of for issue #165.

I also added a second table, where some rows that are unclear, eg, CSS, JSON, and Javascript (obviously, any other programming languages could play the same role). Indeed, the current selector structure is fairly poor in terms of these, although annotating a, say, program, is a clear use case. The text position selector for these is also poorly defined (probably it should be considered in a 'minimized' version only)

Some questions/issues
- [ ] The reference to official media types may not be always appropriate. What is the media type of a binary data file? Maybe the entry should be 'anything that is not covered above'?
- [ ] I do _not_ propose to extend the current selectors to encompass CSS/JS/JSON; I do not think there is enough experience for these. However, we should add section in the vocab document, similarly to the extension section on motivation, on the possibility to extend selectors, and also add a reference to that extension possibility in the model document to make things more explicit. We could then use the CSS, JSON, and Javascript as example. A, say, Javascript selector _may_ include keys like 'function' or 'variable', meaning that the selector could specify the definition of a function or the creation of a variable; combined with, say, the selector for text position or range it could provide a good way to select a relevant part of a program. Something similar could be done for CSS or for JSON.
- [ ] There may be a need to give a more precise specification for some of the selectors for specific media types (if we accept them for that media type). For example, if a text position (or text quote) selector is "valid" for CSV, should the position number include the separator (i.e., ",") character? 
- [ ] There are some questions marks where I was not sure...
- [ ] Some entries are such that there is no formal definition for a fragment, but it is relatively clear what they mean. (E.g., in Turtle, the RDF identification of a term/URI prevails, TSV would use the same as CSV). We may decide to be silent on this, but flagging the issue nevertheless

Cc @azaroth42 @paolociccarese @BigBlueHat

**Comment by tilgovi** [comment]
Another question is how we should test range selector from #153.

**Comment by iherman** [comment]
Turn into an editor's action (call 2016-04-22)

See http://www.w3.org/2016/04/22-annotation-irc#T15-52-58

**Comment by azaroth42** [comment]
To suggest a few minor tweaks:
- Fragment should probably be ? for other and binary -- we don't know what fragment definitions are out there.
- Text Quote not for EPUB? EPUB3 as an HTML container seems plausible to do at least Text Quote?
- Data Position /could/ be used on anything, including HTML etc. For conformance I would prefer to NOT have it on Image and Video ... I don't expect that commenting on byte ranges of an image is meaningful to anyone.  Perhaps a ? on everything, and a tick on Binary?

**Comment by pciccarese** [comment]
In relation to the two question marks related to PDF. 
I've always been annotating the PDFs after HTML rendering (pdf.js sort of thing).
I am not sure that is directly possible in the native PDF format, which I am assuming the 'PDF (application/pdf)' means? 

Does anyone work directly with PDFs and knows the answer?

**Comment by iherman** [comment]
@azaroth42 

> Fragment should probably be ? for other and binary -- we don't know what fragment definitions are out there.

Yes, I agree with that.

> Text Quote not for EPUB? EPUB3 as an HTML container seems plausible to do at least Text Quote?

Yes, I suppose in a very abstract level a text quote could be used (although the implementation is tricky, because the zip file is not the same as the HTML element proper (ie, an implementation should drill down and test each constituent HTML file...). But I agree that, at least conceptually, this sounds right.

> Data Position /could/ be used on anything, including HTML etc. 

Yep, but I do not think we should really go with this, mainly because Text Position is also available. I would prefer to keep an 'x' for those

> For conformance I would prefer to NOT have it on Image and Video ... I don't expect that commenting on byte ranges of an image is meaningful to anyone. 

Except... isn't it correct that the EXIF metadata is in the first X byte of an image? (I may be wrong on this).

> Perhaps a ? on everything, and a tick on Binary?

I would prefer a ? on image & video, tick on Binary, and an 'x' on the rest.

**Comment by iherman** [comment]
@pciccarese, the [PDFWordFinder](http://help.adobe.com/livedocs/pdfl_sdk/9/PDFL_SDK9_HTMLHelp/API_References/Acrobat_API_Reference/PD_Layer/PDWordFinder.html) seems to indicate that a TextQuote may be possible. I am not sure about the Text Position.

**Comment by azaroth42** [comment]
@azaroth42 to put a pointer in the model for where the table should go

**Comment by tilgovi** [comment]
Paolo, I don't know PDF that well, but I have great through some of the annotation related bits of the spec (it's giant). PDF has a notion of annotation in the format, targeting points and maybe other geometry, as well as text. It also has a fragment identifier syntax, if I recall correctly, that allows to describe these geometries as well as pages and text.

I don't remember the exact extents of this, but there are things there. I just don't know how we'd test it.

**Comment by iherman** [comment]
Closing by virtue of (accepted) PR #235.
