### ISSUE TITLE
(model) update reference for language tags: BCP47 instead of RFC5646

### ISSUE THREAD

**Issue by fsasaki** [w3c/web-annotation#208]
https://www.w3.org/TR/2016/WD-annotation-model-20160331/#bodies-and-targets

> The Body or Target SHOULD have exactly 1 language associated with it, but MAY have 0 or more. The value of the property SHOULD be a language code following the [rfc5646 https://www.w3.org/TR/2016/WD-annotation-model-20160331/#bib-rfc5646] specifiction.

This should refer to BCP 47 instead of RFC 5646. BCP 47 is the BCP for identifying languages; it is currently represented by RFC 5646. If a new RFC for identfiying languages would be written, the BCP 47 reference will still be stable.

See an example how to reference BCP 47 here
https://www.w3.org/TR/its20/#bcp47

**Comment by iherman** [comment]
Sure, this is editorial (F2F on the 15.05.2016)
