### ISSUE TITLE
(model) make definition of a character more precise

### ISSUE THREAD

**Issue by fsasaki** [w3c/web-annotation#209]
From
https://www.w3.org/TR/2016/WD-annotation-model-20160331/#embedded-textual-body 

> The character sequence of the content of the Textual Body: 

This text and the whole document is missing a definition of a character. Please consider to define that a character is a Unicode code point.

**Comment by azaroth42** [comment]
Duplicate of 206, no?

**Comment by iherman** [comment]
Referring to #206, closing this issue.
