### ISSUE TITLE
(model) have a note on logical and visual order of text for text quote selector implementations

### ISSUE THREAD

**Issue by fsasaki** [w3c/web-annotation#210]
Comment on
https://www.w3.org/TR/2016/WD-annotation-model-20160331/#text-quote-selector
The annotation model specifies for implementations on the DOM level how the selector should be generated, see the paragraph starting like this:

> When generating the Text Position Selector values, it is recommended that implementations built for an environment that supports DOM Level 3 APIs use the textContent property of top level, user visible Node object [DOM-Level-3-Core] of the resource.

A user agent may have issues to implement the proper selection functionality on a user interaction level then working with bidirectional text. Here it would hep to have a note  saying that the text quote selector operatosr on the logical order of characters and that the visual order has to be taken into account separately by the user agent. See the following material for background information. 
- About logical versus physical order https://www.w3.org/International/questions/qa-visual-vs-logical
- About potential issues with selection, to http://r12a.github.io/scripts/tutorial/part4#selection 
  The material explains the issues.

The comment is not on referencing the two sources; a note itself would be useful.

**Comment by tilgovi** [comment]
:+1: to operating on the logical order and not the visual

**Comment by iherman** [comment]
Discussed 17.05.2016 F2F meeting: accepted as editorial
