### ISSUE TITLE
(model) missing mechanism to express language preferences in the intendend audience field

### ISSUE THREAD

**Issue by fsasaki** [w3c/web-annotation#211]
Comment on
https://www.w3.org/TR/2016/WD-annotation-model-20160331/#intended-audience
There is no mechanism to express that an annotation is intended for a user with a specific (set of) language preference(s). Example 10 in section [choice of bodies and targets](https://www.w3.org/TR/2016/WD-annotation-model-20160331/#choice-of-bodies-and-targets) shows how to represent multiple languages, but there is no interaction defined with teh intended audience.

One use case for this is to generate annotations in one language and then use (machine) translation to present them to many users in other languages. For this use case the intended audience mechanism would be very useful, if it would allow to separate user language preferences.

**Comment by iherman** [comment]
Out of scope (F2F meeting 17.05.2016)
