### ISSUE TITLE
misspellungs

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#212]
there are a number of typos, including 'specifiction' and 'HttpReqeustState' in the version i reviewed.  I raise this just in case. I assume that the spellcheck + proofread step is still to be done?

**Comment by azaroth42** [comment]
Thanks! Yes, we need to spellcheck, but a list of typos to fix as people see them (comments on this issue) would be much appreciated :)

**Comment by azaroth42** [comment]
I've corrected these typos, please create new issues for any further ones noticed.
