### ISSUE TITLE
'generated' and 'modified' date/time properties specific reference and format

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#217]
[raised by Addison Phillips, not yet discussed by i18n WG]

The generated and modified properties store the creation and most-recent modification timestamps for an annotation. The spec requires ("MUST") date times follow a very old WG note [http://www.w3.org/TR/NOTE-datetime] that defines a profile of ISO8601, but does not specify a specific format within that note. It goes on to recommend ("SHOULD") `xsd:dateTime` "with a timezone" (which is a specific format that happens to be one of those enumerated in the WG note). Generally, when working with time values, the minimal acceptable value would be a `full-date` (and having a timestamp, i.e. `date-time` is preferable). `RFC3339`defines these specific keywords and would be my suggestion as a better replacement for the WG note. XML Schema and `xsd:dateTime` is also a valid reference to use here.

**Comment by akuckartz** [comment]
I like the flexibility of W3CDTF.

**Comment by iherman** [comment]
Close, referring to the resolution of #216
