### ISSUE TITLE
How is language assigned to an annotation?

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#218]
[raised by r12a, not yet discussed by the i18n WG]

3.2.1 External Web Resources
https://www.w3.org/TR/annotation-model/#external-web-resources

How is language information added to an annotation?  Is the person creating the annotation expected to add it, or is it automatically picked up by the annotation?

(The same question could be raised for direction information, if that is added to the model.)

**Comment by iherman** [comment]
Out of scope. (F2F meeting 17.05.2016)
