### ISSUE TITLE
Defaults for an Annotation Collection

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#219]
[raised by r12a, not yet discussed by the i18n WG]

5.1 Annotation Collection
https://www.w3.org/TR/2016/WD-annotation-model-20160331/#annotation-collection

I wonder whether Default Language and Default Direction might be useful properties to add to the list of properties that describe the use of a collection.  I suppose it depends on how language and direction information are assigned to individual annotations. If done automatically, this may not be so important.  If done by hand, this could save a lot of trouble.

Another property might reflect the language(s) of the intended audience of the collection (as opposed to the language of the annotations themselves) - particularly for collections containing multilingual annotation sets.

**Comment by iherman** [comment]
Annotations have no language or direction, so this not relevant.

**Comment by iherman** [comment]
Further explanation: the _annotation_ per se does not have a language, it is "just" a datastructure linking the various elements together. The _body_ of an annotation may have language (currently set through `dc:language`, etc) mostly when embedded (as opposed to be just referred to).
