### ISSUE TITLE
white space normalisation

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#221]
[raised by r12a, not yet discussed by the i18n WG]

4.2.4 Text Quote Selector
https://www.w3.org/TR/2016/WD-annotation-model-20160331/#text-quote-selector

> unnecessary whitespace should be normalized

Who decides what 'unnecessary' and 'whitespace' are? Should it be defined in the spec? 

For example, does it include normalisation of zero-width space when used with SE Asian languages?  Does it make an exception for Thai and similar scripts, which use multiple spaces to identify sentence breaks rather than full stops? Does it take into account the normalisation rules for line breaks in Chinese and Japanese, or simply convert line breaks to spaces?  etc.

**Comment by azaroth42** [comment]
Working Group response: (╯°□°)╯︵ ┻━┻   :)

**Comment by r12a** [comment]
bringing in @tilgovi comment in https://github.com/w3c/web-annotation/issues/227

> Why do we specify normalization of white space, though? Why strip the selector of precision? Maybe my annotation is intended to target some whitespace.

**Comment by azaroth42** [comment]
Because (AIUI) whitespace is normalized by the browser before it gets to the DOM, so you can't get at it in any meaningful way.

**Comment by tilgovi** [comment]
For block elements, but not inline elements, white space is normalized for display, but not in the API.

**Comment by azaroth42** [comment]
@tilgovi This the getSelection() API, so even if the rendering is with the whitespace collapsed, the selection's characters will include the whitespace as recorded in the document, as opposed to what you end up with in your clipboard when you copy the selection from the browser?

We can take out the whitespace normalization recommendation. Systems wanting to match the content in different representations will need to massage the data, but they'll probably need to do that anyway.

(For an experiment, I made a document with the contents 

```
<p>a   b      c  d     e</p>
```

, selected some text, and looked at window.getSelection() and compared the extent of the selection ... which included the whitespace characters from the textContent)

**Comment by tilgovi** [comment]
To be more accurate:

The string interface for a `Selection` is subject to the display notification [1].

But the nodes themselves report text content faithfully as space characters have their content included when parsing characters in the body text of HTML [2][3].

To my knowledge, whitespace isn't collapsed or ignored anywhere between tags and there should be `Text` nodes wherever there is text, including whitespace.

[1] https://www.w3.org/Bugs/Public/show_bug.cgi?id=10583
[2] https://www.w3.org/TR/html5/syntax.html#parsing-main-inbody
[3] https://www.w3.org/TR/html5/syntax.html#parsing-main-incdata

**Comment by tilgovi** [comment]
Yes, just followed up to same the same about `Selection` as you.

I am not sure I favor assuming that the `Selection` API is used to stringify a selection. In Hypothesis, for instance, I implemented the text quote selector by inspecting the text values of the ranges retrieved from `getSelection().getRangeAt(n)` for `0 <= n < getSelection().rangeCount`.

In the past, the Selection API was used, but it made anchoring more compute intensive. The easiest way to guarantee the same normalization was to traverse the entire DOM and select every node. The alternative used now can just call `document.body.textContent` and let the browser return all the text content efficiently.

I suppose both approaches seem equally valid to me, I just wonder if we really gain much by specifying additional normalization.

**Comment by tilgovi** [comment]
Here's a good discussion [1]. If `innerText` were standard, this might be less heinous to implement (and wouldn't cause flashes of selected content), but it's also a performance hit that becomes significant when anchoring many quotes.

[1] http://perfectionkills.com/the-poor-misunderstood-innerText/

**Comment by iherman** [comment]
Discussed at with I18N WG, 2015-05-26: remove the recommendation to normalize whitespace

See: http://www.w3.org/2016/05/26-i18n-irc#T15-44-36

**Comment by azaroth42** [comment]
Also noted that if the client cannot find the unnormalized text, it can easily normalize the whitespace internally and then search again. The same would apply for case changing and so forth -- the robustness of text selection is not limited to whitespace, and should be solved holistically rather than putting the easy\* one (whitespace) on the server and the rest on the client.
- Or very very hard for some languages!
