### ISSUE TITLE
String body must not have a language associated?

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#223]
[raised by r12a, not yet discussed by i18n WG]

3.2.5 String Body
https://www.w3.org/TR/2016/WD-annotation-model-20160331/#string-body

> MUST NOT have a language associated with it.

I know string body annotations are not a recommended approach, but if people do use them, i'm not sure why there must not be an associated language.  Surely it could sometimes be useful?

**Comment by iherman** [comment]
That case is when we have the simplest possible syntax for bodies, if language tag is necessary then we have the solution for it.

**Comment by r12a** [comment]
Ivan, what's the solution?

**Comment by r12a** [comment]
Doh! I understand. You mean the solution is to use a different type of body.

**Comment by iherman** [comment]
> On 20 May 2016, at 17:38, r12a notifications@github.com wrote:
> 
> Doh! I understand. You mean the solution is to use a different type of body.

:-) Exactly. The string body is a shorthand for the general concept to offer an easy way to create an annotation for very simple situations.
