### ISSUE TITLE
Use of dc:language

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#225]
[raised by r12a, not discussed by i18n WG, and maybe more of a question]

The Web Annotation Data Vocabulary spec at https://www.w3.org/TR/2016/WD-annotation-vocab-20160331/ refers many times to dc:language.  I don't fully understand the how it's being used, but i'm concerned since dc:language doesn't support BCP47, and so it doesn't seem to be helpful to refer to it.

**Comment by azaroth42** [comment]
The resolution is to add a note to vocab to say that we require BCP47 as the recommended usage of dc:language of using controlled vocabularies.

**Comment by johnwcowan** [comment]
That seems right.  Dublin Core documentation refers to older specific versions of BCP 47 rather than to the evolving BCP 47 itself, but there should be no problem with the use of any form of BCP 47 language tag: they are all syntactically and semantically compatible.
