### ISSUE TITLE
Unable to unsubscribe from mailing list

### ISSUE THREAD

**Issue by morbus** [w3c/web-annotation#23]
G'day. I've tried numerous times to unsub from the public-annotation mailing list (via morbus@disobey.com), but the second CONFIRM is never acted upon - instead, I get back a message from list-help@listhub.w3.org. Could an admin unsubscribe me manually please?

<pre>
Received: from m4.mxes.net ([unix socket])
     by m4.mxes.net (Cyrus v2.3.12) with LMTPA;
     Wed, 18 Feb 2015 07:42:40 -0500
X-Sieve: CMU Sieve 2.3
Return-Path: <public-annotation-request+bounce-morbus=disobey.com@listhub.w3.org>
Received: from 216.86.168.176
    by m4.mxes.net (bayesd) with LMTP id 1424263360-76556-14
    for <morbus_disobey.com@ms4.mxes.net>; Wed, 18 Feb 2015 07:42:40 -0500 (EST)
Received: from local_scanner.mxes.net (mxout-01.mxes.net [216.86.168.176])
    by mxout-01.mxes.net (Postfix) with ESMTP id 061DB8A0DA
    for <morbus@disobey.com>; Wed, 18 Feb 2015 07:42:40 -0500 (EST)
Received: from frink.w3.org (frink.w3.org [128.30.52.56])
    (using TLSv1 with cipher DHE-RSA-AES128-SHA (128/128 bits))
    (No client certificate requested)
    by mxin.mxes.net (Postfix) with ESMTPS id CD4408A057
    for <morbus@disobey.com>; Wed, 18 Feb 2015 07:42:39 -0500 (EST)
Received: from lists by frink.w3.org with local (Exim 4.80)
    (envelope-from <public-annotation-request@listhub.w3.org>)
    id 1YO3xf-0006F1-4e
    for morbus@disobey.com; Wed, 18 Feb 2015 12:42:39 +0000
To: morbus@disobey.com
References: <E7B38559-30A7-4833-9E4E-80162DFF9378@disobey.com>
In-Reply-To: <E7B38559-30A7-4833-9E4E-80162DFF9378@disobey.com>
X-Loop: public-annotation@w3.org
From: public-annotation-request@w3.org
Auto-Submitted: auto-replied
Subject: CONFIRM u940223980
Message-Id: <E1YO3xf-0006F1-4e@frink.w3.org>
Date: Wed, 18 Feb 2015 12:42:39 +0000
X-Virus-Scanned: ClamAV
X-Spam-Allowed: Sender domain in global Allow list passes SPF check
X-Originating-IP: 128.30.52.56
X-Envelope-To: <morbus@disobey.com>
X-Spam-Check: Enabled,6.0,13.0,1,1,42,1,0,0,1,1,0,0,0,[SPAM],
X-Spam-Status: No, score=-4.0 threshold=6.0,13.0 Allow Listed
X-Spam-BayesResult: Unsure, 0.498447
X-Spam-Score: -4.0
X-Spam-Scoring: 0,0

It has been requested that the following address:

       morbus@disobey.com

should be deleted from the public-annotation mailing list.

It has NOT yet been unsubscribed from the list.
To unsubscribe you need to confirm the unsubscription
request by sending an email to the address:

        public-annotation-request@w3.org

with the Subject string:

         CONFIRM u940223980

...
</pre>

<pre>
Content-Type: text/plain;
    charset=us-ascii
Mime-Version: 1.0 (Mac OS X Mail 8.2 \(2070.6\))
Subject: CONFIRM u940223980
X-Universally-Unique-Identifier: 492E18AD-BFA5-4533-85A8-DBECBE0AE4AA
From: Morbus Iff <morbus@disobey.com>
In-Reply-To: <E1YO3xf-0006F1-4e@frink.w3.org>
Date: Wed, 18 Feb 2015 07:43:48 -0500
Content-Transfer-Encoding: 7bit
X-Smtp-Server: smtp.mxes.net:morbus_disobey.com
Message-Id: <C4429A52-5044-4AD9-BF2E-EC5371B3513F@disobey.com>
References: <E7B38559-30A7-4833-9E4E-80162DFF9378@disobey.com> <E1YO3xf-0006F1-4e@frink.w3.org>
To: public-annotation-request@w3.org
</pre>

<pre>
Received: from m4.mxes.net ([unix socket])
     by m4.mxes.net (Cyrus v2.3.12) with LMTPA;
     Wed, 18 Feb 2015 07:44:15 -0500
X-Sieve: CMU Sieve 2.3
Return-Path: <list-help@listhub.w3.org>
Received: from 216.86.168.176
    by m4.mxes.net (bayesd) with LMTP id 1424263455-76556-21
    for <morbus_disobey.com@ms4.mxes.net>; Wed, 18 Feb 2015 07:44:15 -0500 (EST)
Received: from local_scanner.mxes.net (mxout-01.mxes.net [216.86.168.176])
    by mxout-01.mxes.net (Postfix) with ESMTP id 42C7C8A05B
    for <morbus@disobey.com>; Wed, 18 Feb 2015 07:44:15 -0500 (EST)
Received: from frink.w3.org (frink.w3.org [128.30.52.56])
    (using TLSv1 with cipher DHE-RSA-AES128-SHA (128/128 bits))
    (No client certificate requested)
    by mxin.mxes.net (Postfix) with ESMTPS id C8C298A059
    for <morbus@disobey.com>; Wed, 18 Feb 2015 07:44:14 -0500 (EST)
Received: from lists by frink.w3.org with local (Exim 4.80)
    (envelope-from <list-help@listhub.w3.org>)
    id 1YO3zC-0006kD-3T
    for morbus@disobey.com; Wed, 18 Feb 2015 12:44:14 +0000
To: morbus@disobey.com
Subject: Re: CONFIRM u940223980
References: <E7B38559-30A7-4833-9E4E-80162DFF9378@disobey.com> <E1YO3xf-0006F1-4e@frink.w3.org> <C4429A52-5044-4AD9-BF2E-EC5371B3513F@disobey.com>
In-Reply-To: <C4429A52-5044-4AD9-BF2E-EC5371B3513F@disobey.com>
X-Loop: public-annotation@w3.org
From: list-help@listhub.w3.org
Message-Id: <E1YO3zC-0006kD-3T@frink.w3.org>
Date: Wed, 18 Feb 2015 12:44:14 +0000
X-Virus-Scanned: ClamAV
X-Spam-Allowed: Sender domain in global Allow list passes SPF check
X-Originating-IP: 128.30.52.56
X-Envelope-To: <morbus@disobey.com>
X-Spam-Check: Enabled,6.0,13.0,1,1,42,1,0,0,1,1,0,0,0,[SPAM],
X-Spam-Status: No, score=-4.0 threshold=6.0,13.0 Allow Listed
X-Spam-BayesResult: Unsure, 0.502396
X-Spam-Score: -4.0
X-Spam-Scoring: 0,0

******* About the W3C Mailing Lists *******

There are many mailing lists provided by the W3C for discussion

...
</pre>

**Comment by azaroth42** [comment]
Not an issue about a deliverable, closing.
