### ISSUE TITLE
Change NS to https://.../wa/

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#230]
As we want to go to HTTPS, and can't reuse oa

**Comment by azaroth42** [comment]
Will become:  https://www.w3.org/ns/wa#

**Comment by iherman** [comment]
Per

https://www.w3.org/blog/2016/05/https-and-the-semantic-weblinked-data/

it seems that the official advice of the data activity at W3C is to stay with http (instead of https). This may make this issue irrelevant and could be closed. This should also invalidates the resolution: https://www.w3.org/2016/05/17-annotation-minutes.html#resolution02

Cc: @azaroth42

**Comment by akuckartz** [comment]
So everbody is moving to https but the Semantic Web community stays with http? Dislike.

**Comment by iherman** [comment]
@akuckartz, this is of course a legitimate discussion, but it has to be done elsewhere. It is not the job of this Working Group to deal with this issue...

That being said, in the case of this WG, the issue becomes all the more complicated that the http: version of the OA namespace exists and has been in use by a number of implementations over the years. Changing the URI is therefore a more complex issue, regardless of whether it is a change in the scheme or somewhere else.

**Comment by azaroth42** [comment]
I propose close wontfix for this specific issue of changing the namespace. Exactly how we deal with deprecation is a separate discussion.  Given we had a resolution, I guess we need to re-resolve this next week on the telco. (tagging as such)

**Comment by iherman** [comment]
> On 21 May 2016, at 10:56, Rob Sanderson notifications@github.com wrote:
> 
> I propose close wontfix for this specific issue of changing the namespace. Exactly how we deal with deprecation is a separate discussion. Given we had a resolution, I guess we need to re-resolve this next week on the telco. (tagging as such)

+1

**Comment by stain** [comment]
I hope we are not changing the namespace just to add `https://` - are there other incompatibilities with OA that were agreed? 

Users are still free to download vocabularies and contexts over https and we (should) make that clear in the specs.

**Comment by iherman** [comment]
Discussed at telco 2016--05-27, reflecting on https://www.w3.org/blog/2016/05/https-and-the-semantic-weblinked-data/ closing without further action
