### ISSUE TITLE
Add accessibility to the model & vocab

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#231]
Rob, Benjamin, Ivan reviewed the specifications, especially in conjunction with the IDPF profile of OA, and noticed that:
- Accessibility is not mentioned, and is as important as i18n
- There is an existing pattern from IDPF that we could use
- It is the same pattern as our approved audience addition (also from IDPF)
- It adds only a single new key (accessibilityFeature)
- It's cross-domain -- every domain needs a11y, and different communities would likely come to different patterns without guidance.

Proposal:

Use schema.org/accessibilityFeature as a mechanism for expressing accessibility features of resources, including Body, Target and TextualBody.  There would be no recommendation of what the values are (as they're only maintained in a wiki page).  This just provides a single hook for managing the inclusion of the features.

Example:

```
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno/1",
  "type": "Annotation",
  "body": {
    "type": "TextualBody",
    "value": "<span style=\"font-size: 48pt\">A Big Comment</span>",
    "format": "text/html",
    "language": "en",
    "accessibilityFeature": "largePrint"
  },
  "target": {
    "id": "http://example.org/videos/1",
    "type": "Video",
    "accessibilityFeature": "captions"
  }
}
```

**Comment by iherman** [comment]
+1

Ivan

> On 18 May 2016, at 18:09, Rob Sanderson notifications@github.com wrote:
> 
> Rob, Benjamin, Ivan reviewed the specifications, especially in conjunction with the IDPF profile of OA, and noticed that:
> 
> Accessibility is not mentioned, and is as important as i18n
> There is an existing pattern from IDPF that we could use
> It is the same pattern as our approved audience addition (also from IDPF)
> It adds only a single new key (accessibilityFeature)
> It's cross-domain -- every domain needs a11y, and different communities would likely come to different patterns without guidance.
> Proposal:
> 
> Use schema.org/accessibilityFeature as a mechanism for expressing accessibility features of resources, including Body, Target and TextualBody. There would be no recommendation of what the values are (as they're only maintained in a wiki page). This just provides a single hook for managing the inclusion of the features.
> 
> Example:
> 
> {
>   "@context": "http://www.w3.org/ns/anno.jsonld",
>   "id": "http://example.org/anno/1",
>   "type": "Annotation",
>   "body": {
>     "type": "TextualBody",
>     "value": "<span style=\"font-size: 48pt\">A Big Comment</span>",
>     "format": "text/html",
>     "language": "en",
>     "accessibilityFeature": "largePrint"
>   },
>   "target": {
>     "id": "http://example.org/videos/1",
>     "type": "Video",
>     "accessibilityFeature": "captions"
>   }
> }
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub https://github.com/w3c/web-annotation/issues/231

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Discussed on telco 2016-05-27, accepted to add the Accessibility Features. See

See https://www.w3.org/2016/05/27-annotation-minutes.html#resolution06
