### ISSUE TITLE
Next/Prev are untestable

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#233]
Benjamin and Rob believe that the requirements of next and prev in the model for pages are unable to be tested, as they require knowledge of the state of the Collection while testing the Page.  For example, if you are at the last page, it MUST NOT have a next link (but how do you know it's last?) and it SHOULD have a prev link (but it might not, and you don't know that it's not also the first page)

https://www.w3.org/TR/annotation-model/#annotation-page

**Comment by azaroth42** [comment]
Noting that they would be testable if the metadata about the AnnotationCollection was embedded in the page, using partOf.

Compare the example here:
- https://www.w3.org/TR/annotation-model/#annotation-page

With Example 9 in protocol here:
- https://www.w3.org/TR/annotation-protocol/#responses-with-annotations

**Comment by gsergiu** [comment]
very correct ... the total number of the items in the collection and the number of items provided in the current page must be supplied in each response.

**Comment by halindrome** [comment]
Isn't it testable if we have the platform under test tell us information about the collection that is being tested?

**Comment by gsergiu** [comment]
@halindrome I think that the only information hat is needed is the total number of items in the collection. But I would rather include this information in every server response, than creating an extra call for it.

Concretely, every text search engine provides this information in the response. I think we can learn from their (long) experience in the field.

**Comment by gsergiu** [comment]
@azaroth42 
In the pagination based navigation, the page size is used for computeing the number of pages. 
I think it would be inportant to allow this parameter to be set in request, and consequently to be also included in the prev and next links (as optional parameter). 
Implementations may also use a default value for the page size ... but this is hard to be retrieved from the api ... still not imposible.
One needs to have in the system more pageSize items.
By requesting the first page .. one can find the pageSize ( only if ... next is present in the response) 

Still .. I expect that many implementations will expose pageSize as input param

**Comment by azaroth42** [comment]
Closing as we have tests for next/prev, so clearly the issue is wrong :)

**Comment by gsergiu** [comment]
well .. this depends on how precise the tests are. 
I think that without knowing the page size (which in the most cases is a parameter for the json apis), it is not really posible to implement a robust testing. 
However, this should probably be discussed in another ticket.
