### ISSUE TITLE
Remove purpose=commenting requirement from bodyValue

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#240]
We heard several times last week that there was confusion as to why the bodyValue text must be treated as commenting, rather than simply following the motivation for the Annotation.

As purpose is not required for TextualBody, there's no way to introspect on the bodyValue to figure out what it should be, we heard a lot of requests for using it for plain text tagging ... I propose to remove the restriction that the purpose must be considered to be commenting.  A system encountering an annotation with a motivation that isn't commenting and with bodyValue would not know what to do.

**Comment by iherman** [comment]
+1

**Comment by BigBlueHat** [comment]
:+1:

**Comment by pciccarese** [comment]
Also +1, the restriction is too arbitrary.

**Comment by iherman** [comment]
Discussed at telco 2016-05-27, decided to remove the restriction.

See http://www.w3.org/2016/05/27-annotation-irc#T15-22-44

**Comment by hugomanguinhas** [comment]
Hi all,

The lifting of this constraint is really relevant for us... thanks!
btw, as we are at the moment updating our implementation, I just wanted to check with you if the field/property is still called bodyText (as it is defined in current the spec) or has it changed to bodyValue?

Thanks!

Br, Hugo

**Comment by azaroth42** [comment]
bodyValue

The most recent ED is:  http://w3c.github.io/web-annotation/model/wd2/

**Comment by BigBlueHat** [comment]
@hugomanguinhas one word of caution, however. `bodyValue` is _very_ limited in what can be said about it. By definition it has no known language (could be anything) and it MUST be considered `text/plain`.

Full list is here of course http://w3c.github.io/web-annotation/model/wd2/#model-5

**Comment by hugomanguinhas** [comment]
Hi Benjamin,
thanks! we will use it carefully and will only advertise it for very simple cases when indeed the language is not known.
Br, Hugo
