### ISSUE TITLE
protocol testing requirements

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#244]
And to describe the set of features to test for Protocol:

Given a particular request (URI + http method + request headers + body):
- Status code is as expected
- Headers are present
- Value of the headers are as expected
  - Content Type
  - Link
  - If-Match vs ETag
  - Allow, Vary, CORS headers, 
- JSON response is as expected (using json-schema tests)

**Comment by halindrome** [comment]
This should all be do-able via the WPT environment.

**Comment by BigBlueHat** [comment]
@halindrome and I chatted yesterday and he pointed me at the `wptserve` docs:
https://wptserve.readthedocs.io/
and specifically the `handlers` section:
https://wptserve.readthedocs.io/en/latest/handlers.html

I intent to dig through all that early next week, and am more than happy to have collaborators if anyone else is interested. :grin:

**Comment by azaroth42** [comment]
Closing as this is implemented in the testing framework now.
