### ISSUE TITLE
Minor issues with the individuals' formatting in the vocab spec

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#245]
- [x] in the [section on Named Individuals](http://w3c.github.io/web-annotation/vocab/wd/#named-individuals) none of the individuals have the `instanceOf: oa:Motivation` entry, although all of them are individuals for motivation
- [x] the `ltr` and `rdl` individuals are correctly formatted, but they appear as separate 'sections' (section 2.4 and 2.5) although they should. Either
  - they should be subsumed by the section 'Named Individuals', or
  - they should be in a separate section entitled something like 'Individuals for directions', and the previous section should be renamed as 'individuals for motivation' (or something similar)
- [x] the `autoDirection` does not appear in the table of contents... (I guess some issues with the section element)
- [x] I am not sure about `PreferContainedDescriptions` and `PreferContainedIRIs`: I guess they are also individuals in the sense of RDF, although they are just used as part of the protocol; if so, the same sectioning remark applies for them as for `ltr` and `rtl`

**Comment by azaroth42** [comment]
In LDP, the Prefer\* URIs are `owl:Individual`s (see: https://www.w3.org/ns/ldp.ttl) so I just followed the same pattern.

The sectioning weirdness was due to a missing start section tag, throwing everything else out of sync.
