### ISSUE TITLE
Consistent definitions of the id for External Web Resources and Specific Resources

### ISSUE THREAD

**Issue by gsergiu** [w3c/web-annotation#247]
The id property of the bodies and targets should have a consistent definition

The current definitions:
1. For External Web Resouces states that the id is: 

> The IRI that identifies the Body or Target resource.
> Bodies or Targets which are External Web Resources MUST have exactly 1 id with the value of the resource's IRI. 

see https://www.w3.org/TR/annotation-model/#external-web-resources 

example 17:

```
"body": {
    "id": "http://example.net/review1",
    "rights": "http://creativecommons.org/licenses/by/4.0/"
  } 
```

With the given definition I would expect that the URI http://example.net/review1, in combination with the Accept:application/json should return:
{
    "id": "http://example.net/review1",
    "rights": "http://creativecommons.org/licenses/by/4.0/"
  }
1. For Specific Resources, the id is:

> The identity of the Specific Resource
> A Specific Resource MAY have exactly 1 IRI that identifies it.

see https://www.w3.org/TR/annotation-model/#specific-resources

Syntactically correct Example as type is not mandatory (semantically .. probably not)

```
"body": {
    "id": "http://example.net/resource1",
    "source": "http://example.net/review1",
  } 
```

Again with the given definition of the id I would expect to get the following json when using the application/json in the accept header for http://example.net/resource1
{
    "id": "http://example.net/resource1",
    "source": "http://example.net/review1",
  } 

I think that these definitions are slightly ambiguous, and I assume that their meaning will be better explained through the following:
1. For External Web Resources:
   id:   The IRI that identifies the External Resource referenced by the Body or Target
2. For Specific Resources
   id: The IRI that identifies the Body or Target representing the SpecificResource

Still an open question remains:
Why should the ids of Bodies and Targets have different meanings depending on their type?

**Comment by gsergiu** [comment]
PS: in this post I made some speculations, as there is no example of SpecificResource using and id

**Comment by azaroth42** [comment]
-1. The External Resource /is/ the Body or Target. Those definitions imply there is a separate intermediary resource that somehow references it.

**Comment by azaroth42** [comment]
Propose: close, wontfix ?

**Comment by iherman** [comment]
+1

**Comment by gsergiu** [comment]
@azaroth42  for the SpecificResource and the "source" Resource are two different resources, right?
For TextualBody is no need to reference an external resource, as the text is embeded. 

However, for ExternalResources  I'm not convinced that the Body should be considered the same resource as the External Resource. Especially when the annotations have the possibility to add "rights" statements to the Body=ExternalReource, or to extend the context of the body and add additional statements.  Over the time, or by mistake the statements from the Body might conflict with the Statements from the ExternalResource (as retrieved per ID).  I think it is safer and more correct to consider the ExternalResource body as a different resource, that the referenced one. 
The BodyResource is owned by the creator of the annotaion, basically containing his assertions, while the ExternalResource has another owner, and properties like right, must be declared only by the owner of the resource (in my opinion).

**Comment by azaroth42** [comment]
Yes, The specific resource would be the object of the hasBody relationship, and the full resource is the object of hasSource from the specific resource.  So the "Body" is the specific resource. So we do already consider the source resource and the specific resource as separate resources.

However, as most target resources will not be linked data, the annotation is the only place where rights, language, format and so forth can be maintained. So to say that the rights must only be declared by the owner of the resource is just saying that there will never be rights statements.

**Comment by gsergiu** [comment]
well ... is it better If I attach public domain rights to the http://microsoft.com , and another person CC0 and a microsoft employee adds the the following URL: https://raisingthemug.files.wordpress.com/2015/01/copyright-all-rights-reserved.jpg ?

**Comment by azaroth42** [comment]
We couldn't stop you from doing that anyway.  In the open world, anyone can make any assertion about any resource.  If MS are concerned that someone has made the assertion, then it would behoove them to make a counter assertion that would be treated with a higher degree of trust, given the publisher of the assertion.

**Comment by gsergiu** [comment]
Yes ... but there is a difference, when we have the Body as being a different resource than the External Resource, and the annotations add rights statements and creator to Body, but not to the external resource (for which only the owner should assign rights). 

I assume this is again something that has to be modeled as SpecificResource with the current specifications. However, I find it wrong that it is possible to add rights to ExternalResources without having a possibility to verify automatically, that the rights statements are correct.

**Comment by azaroth42** [comment]
Well ... could you make a clear statement about the problem, and a proposal for the solution?

**Comment by gsergiu** [comment]
Solution 1. I would propose that the regular body should reference the ExternalResources using the "source" property, similar to the SpecificResources.
(In my opinion, the id should contain the URI that retrieved the body, meaning the json serialization of the body)

Solution 2. I the solution 1 is not adopted, I think that we should specify that the regular bodies  are external resources and they can include only information (metadata) about the resource that is accessible for machine reading (e.g. format can be retrieved from Content-Type header, language from meta tags, etc.). Additionally, in case of outdated metadata, the information (cached) in the body must be overwritten with the one retrieved from the External Resource (the open question is when to do this?)

**Comment by azaroth42** [comment]
The first solution is essentially what was proposed and rejected previously, of requiring a SpecificResource for every body and target.  It was rejected as making the simple cases overly complex for no significant gain.

The second solution would preclude TextualBody, which again is the simple case. And yes, clients should believe the resource rather than the metadata in the Annotation (e.g. `Content-Type` header should be used when if conflicts with `format`).  Maybe that should be explicit in the model, but that's the only change I could see as valuable at this stage.

**Comment by gsergiu** [comment]
1. If nothing else can be made at this stage a note stating that "annotations that need to add new asserts on the ExternalResource should/must use the SpecificResources for this purpose. The metadata that is available in the resource must take precedence over the metadata from the Annotation.". 
2. The open question that remains in this case is, if it is ok to add the "rights" statements to the bodies and targets that use External Resources (and not Specific Resources), given the fact that there is no (or I'm not aware of a) protocol to verify automatically the correctness of the rights statement ?

**Comment by iherman** [comment]
Discussed on 2016-06-03: RESOLUTION:  Add to the note in 3.2.1 that information from the resource should be considered authoritative, not the Annotation's properties

See http://www.w3.org/2016/06/03-annotation-irc#T15-42-38

**Comment by azaroth42** [comment]
... And done.
