### ISSUE TITLE
Change 'reviewing' to 'assessing'?

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#249]
This has been partially discussed on last week call. I would  change 'reviewing' to 'assessing' as it has a more generic and less formal nature. That will allow for more specific terms when needed.

**Comment by jjett** [comment]
@paolociccarese +1 for this change but I think we should also add a 'critiquing' to capture the other sense of 'reviewing' which is not 'assessing'.

**Comment by paolociccarese** [comment]
@jjett do you have a reference to what you mean by 'critiquing'? The definitions I find online are things like 'a detailed analysis and assessment of something, especially a literary, philosophical, or political theory'. Which brings it back to 'assessing'.

**Comment by jjett** [comment]
@paolociccarese the combinatorial of 'detailed analysis' + 'assessment' seems sufficient for distinguishing between the two to me. While related to assessing, I think most researchers, especially humanists would argue that critique is an entirely different concept.

**Comment by azaroth42** [comment]
This is already done, I just forgot to make the issue and mark it pending.

**Comment by paolociccarese** [comment]
Just to make sure we are in alignment (ignore if I am looking at the wrong documents):
- in http://w3c.github.io/web-annotation/vocab/wd/ the section 2.3.12 is still marked as 'reviewing'
- in http://w3c.github.io/web-annotation/model/wd2/ the table still lists 'reviewing'

**Comment by azaroth42** [comment]
Yup, it's in #246
