### ISSUE TITLE
JSON-LD Frames should be dereferenceable ... where?

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#251]
We have non normative JSON-LD frames for Annotations, Collections and Pages.  They should be downloadable from somewhere, but where should they live?  At the moment the context document lives in /ns/ but these don't feel like the same sort of thing.

Should they just live along side the specification? `/TR/annotation-vocab/annotation_frame.jsonld`

**Comment by iherman** [comment]
If they are on /TR, the become immutable. Given that the frame specification may still change, that may not be a good idea.

We can also put it as, say,

http://www.w3.org/annotation/vocab/frame.jsonld

or something like that. 

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by azaroth42** [comment]
Also, the examples should be dereferenceable, with the right URIs rather than example.org.
They should also go in /annotation/ ?  /annotation/examples/json/ and /turtle/ ?

Or should they live under their respective specifications, with links from the spec?

**Comment by iherman** [comment]
> On 6 Jun 2016, at 17:21, Rob Sanderson notifications@github.com wrote:
> 
> Also, the examples should be dereferenceable, with the right URIs rather than example.org.
> They should also go in /annotation/ ? /annotation/examples/json/ and /turtle/ ?
> 
> Or should they live under their respective specifications, with links from the spec?

Both are possible. Again, we have to be mindful that /TR is immutable. Ie, if we put them 'under' the respective spec, they will be cast in concrete.

I am actually wondering whether it is not better to leave/place the examples on github, so that people can add new ones later. We can redirect to them from under the /annotation from W3C, but that is only a redirection.

We should also be careful, looking ahead, that if we do something in /annotation, then we should probably do something like

/annotation/v1/

or something similar, with an eye on a possible v2 coming later

Ivan

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub https://github.com/w3c/web-annotation/issues/251#issuecomment-223992055, or mute the thread https://github.com/notifications/unsubscribe/AAfyE9NVWy8qsSaao8FcptmKK9BBOFbZks5qJDsBgaJpZM4IqxyY.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by azaroth42** [comment]
If we foresee people adding further examples beyond the ones extracted from the specs, lets put them under /annotation/2016/examples/

Agree that having them on github would be good too ... but makes it harder to give them real URLs beyond the gh-pages trick. I guess I'm not convinced that people would make new PRs against the repository after the end of the WG, as there'd be no one with the task of reviewing or authority to accept them. This has come up in other WGs -- for example there are several PRs open against the LDP test kit: https://github.com/w3c/ldp-testsuite/pulls

**Comment by iherman** [comment]
> On 6 Jun 2016, at 18:45, Rob Sanderson notifications@github.com wrote:
> 
> If we foresee people adding further examples beyond the ones extracted from the specs, lets put them under /annotation/2016/examples/
> 
> Agree that having them on github would be good too ... but makes it harder to give them real URLs beyond the gh-pages trick. I guess I'm not convinced that people would make new PRs against the repository after the end of the WG, as there'd be no one with the task of reviewing or authority to accept them. This has come up in other WGs -- for example there are several PRs open against the LDP test kit: https://github.com/w3c/ldp-testsuite/pulls https://github.com/w3c/ldp-testsuite/pulls

This is actually, a slightly larger issue, which we may want to address: what is called in the w3c jargon "life after rec". This includes these types of changes, but also errata management, etc.

In the CSV WG what we did was to set up a new CG whose goal is to (1) discuss and possible propose changes like the ones you refer to (2) discuss possible errata and how to manage them (3) possibly discuss issues around a v2. That CG actually uses the WG's (former) github repo, and even the errata management is bound to that repo (see [1] to see how it works). The former WG chairs, document editors (and the W3C staff, especially the team contact) has the right to accept PR-s and write/admin the repo. Some of the pointers (like the errata) are redirected from W3C space to github, but most of the things are just there[2].

The CG has not been terribly active, no new PR has arrived, and only a few errata (but that worked smoothly). This is obviously the example of the horse drinking or not, but it is way better than concentrating everything on the W3C site which, these days (when practically nobody used CVS any more except the team) means that it becomes the sole responsibility of one or two team members. That becomes a bottleneck, much greater than via github.

I am very much in favour following the CSV WG line. I do not really mind if the URI-s of the test cases are github URI-s, but we can simply redirect a directory to a github directory, ie, 

www.w3.org/annotation/v1/examples http://www.w3.org/annotation/v1/examples -> https://w3c.github.io/web-annotation/???? https://w3c.github.io/web-annotation/????

(I am, actually, not convinced that /web-annotation/admin/TR is the best path for this, although the latest changes seem to go that direction. Simply a /web-annotation/TR would work, too. But that is a detail.)

My 2 cents...
1.  https://www.w3.org/2013/csvw/errata/ https://www.w3.org/2013/csvw/errata/
2. http://w3c.github.io/csvw/

**Comment by azaroth42** [comment]
Thus the URIs for the annotations should thus be the github URIs, as that's where you actually retrieve them from.

**Comment by iherman** [comment]
Yes. We may set up redirections from W3C, but that is a slightly different issue.

**Comment by azaroth42** [comment]
Has this been done, and we can close the issue?

**Comment by iherman** [comment]
Added a PR #373 that takes care of this.
