### ISSUE TITLE
Track alignment between motivations and other ontologies

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#256]
There are other ontologies with similar concepts to our Motivations, such as Actions in schema.org and Activities in ActivityStreams.  There should be a place to track the alignment between these systems, and to act as a registry for new motivations / motivation schemes to be linked from to encourage reuse and interoperability.

The proposal is to create an annotation wiki page for this purpose, and populate it during the CR phase.

**Comment by azaroth42** [comment]
- assessing:  schema:AssessAction
- bookmarking: schema:BookmarkAction
- classifying
- commenting: schema:CommentAction (schema:Comment) | (as:Note)
- describing: schema:ReviewAction?
- editing: schema:UpdateAction | as:Update
- highlighting
- identifying: 
- linking: (as:Link)
- moderating:  schema:AcceptAction/RejectAction/AuthorizeAction | as:Flag/Accept/Reject
- questioning:  schema:AskAction (schema:Question) | as:Question
- replying: schema:ReplyAction (schema:Answer) | 
- tagging: 

Resources: 
- https://schema.org/docs/full.html is the full list of Classes in schema.org
- https://www.w3.org/TR/activitystreams-vocabulary/#activity-types is the list of Activities in AS2

**Comment by azaroth42** [comment]
Put in the github wiki to allow CG members who are not W3C members to edit.  Also wikis of closed WGs are usually frozen to prevent spamming.

**Comment by iherman** [comment]
@azaroth42, what should happen with this issue? If we want to do it, we should do it soonish, otherwise just close it with no further actions…

**Comment by azaroth42** [comment]
@BigBlueHat @tcole3 @azaroth42 consider this close-able given the comment above, and the lack of external requirements for making it broadly available. This is being closed without prejudice, and can be reopened if there's a proposal for how better to make the mappings available.

**Comment by gsergiu** [comment]
I find a little bit strage to close this ticket, saying that we can close it again later on...
Why not postponing the ticket to V2? like the related tickets #113 and #428

**Comment by azaroth42** [comment]
This ticket was to do a mapping to other ontologies, which was done in the comment above.  Now that the WG is closed, the wiki is locked, meaning the easiest place to actually find the mapping /is/ this issue until someone comes up with a reason to do anything further.

**Comment by gsergiu** [comment]
I do understand the explained rationale, but I would have expected to have a document as output for this ticket. Having this ticket closed, by referencing one comment ... is quite the same as ignoring the ticket. For me it looks like a discussion without any conclusion... grabed in the closed issues cemetery. However ... the editors have the decision power...
