### ISSUE TITLE
'Web Resource' not consistent across the document

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#264]
In a few places 'Web Resources' is lowercase. 

These are:
- Beginning of section 3.1
- section 3.3.6 in the Model table

Also, in the introduction we have two instances of ‘web resource’ but that is probably ok.

**Comment by azaroth42** [comment]
:+1: Fixed. I also left it as lower case in the use case for Request Header State, as that's more informative than requiring specific terminology.
