### ISSUE TITLE
Add Accept-Post to subsequent example?

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#275]
I wished I'd noticed this during the #85 merge, but alas...

@azaroth42 you OK with me adding this line to the example just below the [`Accept-Post` info](https://www.w3.org/TR/annotation-protocol/#h-container-retrieval)--see the paragraph just before Example 3.

``` http
Accept-Post: application/ld+json; profile="http://www.w3.org/ns/anno.jsonld"
```

That last paragraph sounds like it's about to lead into an example...and then their isn't one. This would fix that.

(if this is too late game and not worth the PR, just close it. :wink: )

**Comment by azaroth42** [comment]
It's already there:  http://w3c.github.io/web-annotation/protocol/wd/#container-retrieval :)

**Comment by BigBlueHat** [comment]
Blarg...so many URLs!...I was on the current `/TR/`... :frowning:
