### ISSUE TITLE
Diagram inconsistencies (in pull request #279)

### ISSUE THREAD

**Issue by paolociccarese** [w3c/web-annotation#280]
Diagram inconsistencies (in pull request #279):
- [x] Example 70 not matching the figure (items)
- [x] Example 76 dcterms:creator vs as:generator and org vs org1
- [x] Example 77 dcterms:creator vs as:generator
- [x] Example 85 not matching the figure (items)
- [x] Example 92 ‘user’ vs ‘person’
- [x] Example 93 ‘as:generated’ vs ‘as:generator’ and ‘client1’ vs ‘client2’
- [x] Example 99: dcterms:creator vs as:generator
- [x] Example 100: dcterms:creator vs as:generator
- [x] Example 105: book vs restaurant

**Comment by pciccarese** [comment]
See pull request #281

Excludes:
- example 70 and 85 as I believe they are ok as they are
- example 92 cannot find the canvas

**Comment by azaroth42** [comment]
For the long lists of things, I agree there's a discrepancy between the diagram (start and end entries) and the turtle (the first three entries).  

I'll put a comment of `...` in the Turtle.
