### ISSUE TITLE
Admin information to be added to the document for CR

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#290]
To publish the documents in CR, we need
- [x] define an end date for the CR period (to be part of the final WG vote)
- [x] finalize an implementation report URI, which should also include some sort of a mock up. Maybe @gkellogg or @halindrome can provide us with an empty space

See the [mock-up CR version of our document](http://w3c.github.io/web-annotation/model/wd2/index-respec.html?specStatus=CR)

**Comment by halindrome** [comment]
Where does an implementation report usually live?  I assumed in the W3C space somewhere?

**Comment by iherman** [comment]
> On 8 Jun 2016, at 15:41, Shane McCarron notifications@github.com wrote:
> 
> Where does an implementation report usually live? I assumed in the W3C space somewhere?

These days, more and more often, it is on github, possibly redirected from a stable W3C address. I think we can do this. Ie, I would set up a redirection from, say, /annotation/v1/implementation_report to a github.io page.

The advantage of github is that people can do updates more easily than having to do it via CVS. (Do you still remember the CVS usage on W3C for WG participants? Those were the days…)

Ivan

**Comment by halindrome** [comment]
I miss CVS.  It was so simple.

@gkellogg I think you have a template.

On Wed, Jun 8, 2016 at 8:46 AM, Ivan Herman notifications@github.com
wrote:

> > On 8 Jun 2016, at 15:41, Shane McCarron notifications@github.com
> > wrote:
> > 
> > Where does an implementation report usually live? I assumed in the W3C
> > space somewhere?
> 
> These days, more and more often, it is on github, possibly redirected from
> a stable W3C address. I think we can do this. Ie, I would set up a
> redirection from, say, /annotation/v1/implementation_report to a github.io
> page.
> 
> The advantage of github is that people can do updates more easily than
> having to do it via CVS. (Do you still remember the CVS usage on W3C for WG
> participants? Those were the days…)
> 
> Ivan
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/web-annotation/issues/290#issuecomment-224593441,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAfx8LlTxA1pRTK4R5z8nSZoFe1fHO1aks5qJsefgaJpZM4Iwqk1
> .

## 

Shane McCarron
halindrome@gmail.com

**Comment by gkellogg** [comment]
The Implementation reports are generated from individual EARL submissions using the [earl-report](https://rubygems.org/gems/earl-report) gem. Instructions for submitting reports are placed in the implementation report template itself (for example, see that for [CSVW](http://w3c.github.io/csvw/tests/reports/index.html#instructions-for-submitting-implementation-reports), which can be referenced in specification header. The [README](https://github.com/w3c/csvw/blob/gh-pages/tests/reports/README) in the report directory provides basic instructions for generating the report.

I'd be happy to help set up the implementation report directory and template file for the group.

**Comment by iherman** [comment]
@gkellogg, that would be very helpful. We need this to start the formal CR process. Probably the best place is to put it into the admin folder of the repo.

Thanks!
