### ISSUE TITLE
(Protocol) Editorial issues about IRI

### ISSUE THREAD

**Issue by tkanai** [w3c/web-annotation#299]
Minor editorial issues.
The second paragraph in Section 5.1 says 

> Upon receipt of an Annotation, the server may assign HTTPS IRIs to all resources and blank nodes in the Annotation, and must assign a IRI to the Annotation resource, even if it already has one provided in the entity body description.
- "HTTPS IRIs" should be "IRIs"
  I can't find any reasons to set HTTPS restriction in this line.
- "a IRI" must be "an IRI"
  Right?

By the way, I'm afraid the process "must assign a IRI to the Annotation resource" might be a little bit hard to imagine what it is necessary to do. I think "must assign an id property to the Annotation resource" is much easier to imagine, and it helps reading the next paragraph, my two cents...

**Comment by azaroth42** [comment]
The reason for HTTPS is from the recommendation to use HTTPS instead of HTTP.

"a IRI" is a typo, will fix.

MUST assign a IRI is actually exactly the same as MUST assign an id property, as the value of the id MUST be an IRI (and SHOULD be an HTTPS IRI).

**Comment by tkanai** [comment]
I see.
My reading was " the server may assign HTTPS IRIs" and any others, such as HTTP IRIs or mailto IRIs, "to resources.".

The HTTPS recommendation is from distribution purposes, and I'm 100% agree with you to assign  HTTPS IRIs for resources which are available from the server.
And if it is the case, I prefer to be said that "Upon receipt of an Annotation, the server may assign HTTPS IRIs to distributable resources". It might be necessary to define what is "distributable resources" separately, though.

On the other hand, since we have many non-"oa" properties, such as foaf:Parson, and the server will need to "assign" appropriate IDs, for instance mailto IRI, and/or HTTP IRIs such as ORCID ID, for those Annotation resources, I'm afraid these IRIs which are mostly used for identification purpose are dropped from the scope.

**Comment by azaroth42** [comment]
Okay, I'm happy with that distinction :) Have fixed in the document.
