### ISSUE TITLE
4.1.1 Client Preferences uses `ns/oa` while examples use `ns/ldp`

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#304]
http://w3c.github.io/web-annotation/protocol/wd/#client-preferences

> - If the client prefers to receive the list of annotations only as IRIs, then it must include the Prefer request header set to the value `return=representation;include="http://www.w3.org/ns/oa#PreferContainedIRIs"`.
> - If the client prefers to receive the complete annotation description, then it must include the Prefer request header set to the value `return=representation;include="http://www.w3.org/ns/oa#PreferContainedDescriptions"`.

@azaroth42 which one is correct: this text? or the examples?

**Comment by BigBlueHat** [comment]
So. It looks like this text is correct and the example code is incorrect.

LDP only has [PreferMinimalContainer](https://www.w3.org/ns/ldp#PreferMinimalContainer) (if I'm not mistaken).

@iherman is it to late for a PR to fix these incorrect URLs in the examples?

/me will send one just in case. :wink:

**Comment by iherman** [comment]
Go ahead

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by iherman** [comment]
For the records: the fixed HTML files (for CR) have been generated and uploaded.
