### ISSUE TITLE
Link errors in the vocab document

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#307]
@azaroth42 :

I have taken care of some link errors in the protocol document, but the link checker found some that I would prefer you'd take care of, see the output of:

https://validator.w3.org/checklink?uri=http%3A%2F%2Fw3c.github.io%2Fweb-annotation%2Fadmin%2FTR%2Fannotation-vocab%2FOverview.html&hide_type=all&recursive=on&depth=&check=Check

You can ignore:
- 404 reports on the other CR document, that will disappear when the documents are put in place
- not sure what to do with the redirection of ~azaroth, but that can also be ignored if there are good reasons of being the way they are
- missing references to rdf-syntax-ns and rdf-schema; the link checker cannot really handle those, but the webmaster will accept that
- the dublin core terms that, again, are beyond our control
- all the blue entries, which are informational

It leaves with two internal fragments (I prefer not to touch to these) and the really disagreeable ones, namely the activity stream fragments.

**Comment by azaroth42** [comment]
Solutions:
- Stanford has dropped my homepage, so I'll just take out my personal URL... guess I need a new one :)
- ActivityStreams links ... Their namespace doesn't resolve to an ontology, just the context :( I'll raise an issue on their issue tracker, but it should be the same as the other unresolvable rdf term fragments.
- The fragment links to terms we can't do much about
- That leaves the references to #value and #rdf-resource ... which I've tracked down and fixed.

Revised versions are now in the regular working directories.

**Comment by iherman** [comment]
I have re-checked the new version and it is now all right. The errors are all explainable, and are problems with the types of URL-s that the link checker cannot properly handle. Closing the issue.
