### ISSUE TITLE
Require dct:Text class for interpretation of literal bodies

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#31]
To distinguish between tags and comments. This explicitly makes the body a comment and never a tag.

**Comment by iherman** [comment]
@azaroth42 can you explain/elaborate? I am not sure what you mean and why...

**Comment by azaroth42** [comment]
Currently the usage of a literal body is ambiguous as to whether the text is a comment or a tag, leaving implementers to guess based on motivations and heuristics.  This would make it explicit that a literal body is _always_ a comment and never a tag.  The reason why motivation is insufficient is that there can be multiple bodies on an annotation, all could be literals, with a mixture of comments and tags:

```
{
  "@type": "oa:Annotation",
  "motivatedBy": ["oa:commenting", "oa:tagging"],
  "hasBody" : ["comment", "tag"],
  "hasTarget": "http://example.org/"
}
```

It's an outcome from the thread:  
https://lists.w3.org/Archives/Public/public-annotation/2015Apr/0139.html

**Comment by azaroth42** [comment]
Superceded by outcome of roles discussion.
