### ISSUE TITLE
Annotation IRI mention in 4.

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#319]
From [4. Annotation Containers](http://w3c.github.io/web-annotation/protocol/wd/#h-annotation-containers)

> The Annotations MUST be assigned IRIs with an additional path component below the Container's IRI.

Should/could this be moved into the [5.1 Create an Annotation](http://w3c.github.io/web-annotation/protocol/wd/#h-create-a-new-annotation) section?

It seems out of place here (from an implementing perspective) and it's easily overlooked later--when focusing on 5.1.

Given that this is a protocol specific requirement (since that's not a requirement of `id` within `items` within `AnnotationCollection`), I think it fits best in 5.1.

Thoughts? @azaroth42

**Comment by azaroth42** [comment]
:+1: Agree it's not in the right place.

**Comment by iherman** [comment]
Covered by the PR #321. Closing this issue.
