### ISSUE TITLE
JSON-LD aliases in Vocabulary content

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#320]
It would be great to not have to jump to and from [Appendix A in the Vocab document](http://w3c.github.io/web-annotation/vocab/wd/#h-json-ld-context) when mapping between JSON-LD and other RDF formats.

I mostly found it confusing when looking up info on our `AnnotationCollection` (which is only a rename of `as:OrderedCollection`).

Not sure how to do that in this tool, but happy to do the work if someone can point me in the right direction! :smile:

**Comment by azaroth42** [comment]
Jump to the appendix from other parts of Vocab, or from the Model document?   

We could include the mapping for each term in the Vocab doc along with the description of the term, but the intent was to keep the model document as RDF-agnostic as possible.  Also, the context should do the mapping for you in software, no?

**Comment by BigBlueHat** [comment]
Yeah. This is entirely a "ctrl+f" sort of request. :smiley: Wanting to get to the correct part of the Vocab document by searching for the JSON-LD aliases (rather than always ending up in the appendix, having to find the actual name, then search for that...).

It's a Nice To Have to be certain (i.e. not a requirement).

**Comment by azaroth42** [comment]
I agree nice to have, but given its outstanding since June ... close no-one-cares-enough-to-fix? Otherwise, @BigBlueHat do you have time to do it?

**Comment by iherman** [comment]
It seems that no-one-cares-enough-to-fix... Closing
