### ISSUE TITLE
Try to register profile with IETF

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#324]
We should start early to attempt to register the profile URI for annotations, as the process for registration seems new and we might run into workflow issues on both W3C and IETF sides.  For example, is it sufficient to put it in our document, as per media types, or do we have to send it to ... someone? ... at IETF?

**Comment by azaroth42** [comment]
RFC reference: https://tools.ietf.org/rfc/rfc7284.txt

**Comment by BigBlueHat** [comment]
@azaroth42 I spoke with Markus (author of RFC7284) and he pointed me [to the protocol assignment form](https://www.iana.org/form/protocol-assignment)--which I'm submitting now.

Here's the contents of the request:

### What type of assignment/registration are you requesting?

> Profile URI

### Which registry are you requesting this assignment/registration be made in?

> Profile URI

### If possible, please give a brief description of why you need this assignment/registration:

> Per RFC 7284 recommends adding Profile URIs to this central registry "to ensure interoperability and decrease the coupling between clients and servers."
> 
> Consequently, the Web Annotation Working Group (of which I am an active participant and co-editor of the Web Annotation Data Model) would like to add the Profile URI we require for the Web Annotation Protocol.

### Additional Information. Please include a reference to the specification or RFC (if available) that defines this number or name space:

> The Web Annotation Protocol requires that Web Annotations be served with the `application/ld+json` media type and that it SHOULD use the `profile=http://www.w3.org/ns/anno.jsonld` parameter. We hope this registration will encourage use of the profile URI.
> 
> The complete media type declaration presented in a request is:
> application/ld+json; profile="http://www.w3.org/ns/anno.jsonld
> 
> The requirement is stated here:
> https://www.w3.org/TR/annotation-protocol/#h-annotation-retrieval

I'll report back as it progresses.

Cheers!
🎩

**Comment by BigBlueHat** [comment]
Also, from the form response:

> Your application has been added to the processing queue. Processing typically takes about one week.

**Comment by iherman** [comment]
> On 2 Nov 2016, at 14:27, BigBlueHat notifications@github.com wrote:
> 
> Also, from the form response:
> 
> Your application has been added to the processing queue. Processing typically takes about one week.

Great.

IETF _may_ reply that this would processed only if the W3C TR document goes to Proposed Recommendation. From their point of view, this would be understandable: it is only at a PR phase that the document gains the right level of stability. Ie, if this is their answer then we should simply point to the fact that a PR transition should happen within a few weeks.

**Comment by BigBlueHat** [comment]
I've heard back with a request to add the information needed in the columns of this table (aka the registry):
http://www.iana.org/assignments/profile-uris/profile-uris.xhtml#table-profile

Here's what I intend to send:

``` yaml
Profile URI: http://www.w3.org/ns/anno.jsonld
Common Name:
  Web Annotation
Description:
  A profile URI to request or signal the document is in the Web Annotation JSON format.
Reference: https://www.w3.org/TR/annotation-model/
```

Is the description (especially) clear enough? @iherman @azaroth42 @tcole3 

Also, I reference the Data Model spec--as that's what defines the Web Annotation JSON(-LD) format--but we do not (yet?) reference the Profile URL in that spec...but rather in the Web Annotation Protocol spec. Should we add that in an Appendix?

**Comment by iherman** [comment]
Isn't it more appropriate to refer to the protocol spec in the profile registration instead? The protocol spec refers to the annotation model, but the profile URI is really irrelevant for the model unless the protocol is used...

**Comment by BigBlueHat** [comment]
@iherman yeah. I think you're probably right. However, I'm still a bit concerned that people storing and serving static Web Annotation documents--or doing so via a non-conformant API--will not find/know-about the profile. They either may not find it or assume it only pertains to Web Annotation Protocol implementations.

I'd like to be sure we encourage the best possible habits. 😁 

Thoughts?

**Comment by iherman** [comment]
> @iherman https://github.com/iherman yeah. I think you're probably right. However, I'm still a bit concerned that people storing and serving static Web Annotation documents--or doing so via a non-conformant API--will not find/know-about the profile. They either may not find it or assume it only pertains to Web Annotation Protocol implementations.
> 
> If implementers use our protocol, then they will have to look at the Protocol document where there is a reference to the profile. If they do not use our protocol, then we cannot help them:-)

I think we are all right simply using the protocol reference.

**Comment by azaroth42** [comment]
+1 to protocol.  There's a reference to the model from the protocol, and vice versa.  The protocol is where the actual definition of the profile and media type is, so I think it's the right reference.

**Comment by BigBlueHat** [comment]
Given the above, I'll be submitting the following and will report back:

``` yaml
Profile URI: http://www.w3.org/ns/anno.jsonld
Common Name:
  Web Annotation
Description:
  A profile URI to request or signal the document is in the Web Annotation JSON format.
Reference: https://www.w3.org/TR/annotation-protocol/
```

Thanks!

**Comment by akuckartz** [comment]
Does it need to be ".jsonld" ? "http://www.w3.org/ns/anno" with content negotiation should be considered as an alternative.

**Comment by BigBlueHat** [comment]
The profile is for `application/ld+json` and that URL is from the Web Annotation Protocol specification.

It could have been defined without the `.jsonld` perhaps, but I think that :ship: has sailed. Given that it's a JSON-LD profile, I think the URL being for that specific representation is fine.

**Comment by azaroth42** [comment]
Also, I don't see what other formats would be even possible for the context document?  Conneg is already enabled for the actual namespace URI which is .../ns/oa# not .../ns/anno#

**Comment by BigBlueHat** [comment]
All done: http://www.iana.org/assignments/profile-uris/profile-uris.xhtml

😄
