### ISSUE TITLE
Vocabulary references rdf:Resource, should be rdfs:Resource

### ISSUE THREAD

**Issue by gkellogg** [w3c/web-annotation#326]
In particular `renderedVia`. Also, `PreferContainedDescriptions` and `PreferContainedIRIs` have the wrong `rdf:type`.

**Comment by gkellogg** [comment]
I'm wondering why this is outstanding for so long? It seems easy to fix:
- PreferContainedDescriptions has type `oa:rdf:Resource`, should be `rdfs:Resource`. See https://github.com/w3c/web-annotation/blob/gh-pages/vocab/wd/ontology/index.ttl#L168.
- PreferContainedIRIs has type `oa:rdf:Resource`, should be `rdfs:Resource`. See  https://github.com/w3c/web-annotation/blob/gh-pages/vocab/wd/ontology/index.ttl#L173
- renderedVia has range `rdf:Resource`, should be `rdfs:Resource`. See https://github.com/w3c/web-annotation/blob/gh-pages/vocab/wd/ontology/index.ttl#L364.

**Comment by BigBlueHat** [comment]
Not sure why this one's gotten missed. I'm marking it as `editor_action` which should more clearly add it to @azaroth42's list. :wink: 

Thanks for staying on it!

**Comment by azaroth42** [comment]
Apologies for the ridiculously long delays... day job and all that.  Fixed the instances, and took the range out of renderedVia, as it doesn't say anything.

**Comment by gkellogg** [comment]
Thanks Rob, I'll update gems and the test results.
