### ISSUE TITLE
Container Representations section should be more demanding

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#328]
Right now (and even after PR #321), the text is _very_ light on requirements for the Server. The client, is told it MUST send certain things if it has preferences, but the Server (according to the text anyhow) is not told it MUST (or even SHOULD) do anything...at all.

This is merely :wink: editorial, I'd reckon and would likely look like rephrasing some of the "client MUST" text to associate it with the required response.

Seem about right?

**Comment by azaroth42** [comment]
Discussion on call 7/15 agrees that the (new) discussion of representations is too light on the server side, and it currently requires reading the examples and paying close attention as a server developer to sections headed as client concerns.
