### ISSUE TITLE
Creating and Updating when canonical is present

### ISSUE THREAD

**Issue by csarven** [w3c/web-annotation#329]
Form the WA Protocol;
Creating:

> If the Annotation contains a canonical link, then it MUST be maintained without change.

Updating:

> Servers SHOULD reject update requests that modify the values of the canonical or via properties, if they have been already set.
1. Is there a discrepancy between these two statements? If MUST to maintain without change, how can it be SHOULD reject for updates (as opposed to MUST reject)?
2. If MUST to maintain without change if canonical is present, does that imply that the sender sort of forces the receiver to keep annotations around (forbids deleting?) even though the receiver may not want to (for whatever reason).

**Comment by rhiaro** [comment]
> If the Annotation contains a canonical link, then **it** MUST be maintained without change.

"It" is ambiguous I think... initially I thought it referred to the Annotation, but actually it probably refers to the canonical link?

**Comment by azaroth42** [comment]
Discussed on call on 7/15, agree that it's ambiguous as currently worded and will clarify that "it" refers to the link, not the entire annotation.

**Comment by csarven** [comment]
Should the `SHOULD` under _Update_ be a `MUST`?

**Comment by azaroth42** [comment]
No, the rationale behind SHOULD is that with strong identity management and trust, a server could allow some agents to manage `canonical` fields.  It shouldn't be prevented from doing, and thus not a MUST.

**Comment by csarven** [comment]
This may be obvious to some readers but "`canonical` link" should perhaps be more explicit about the `oa:canonical` property, and not the canonical link element (via `rel=canonical`).
