### ISSUE TITLE
[Protocol] The ETag sentence in Chapter 4 should refer to RFC 7232

### ISSUE THREAD

**Issue by tkanai** [w3c/web-annotation#331]
The sentence "All HTTP responses from Annotation Containers must include an ETag header that implements the notion of entity tags from HTTP" in 4.1 refers to RFC 7230 which is about HTTP/1.1.

Since the sentence is about "ETag", RFC7232 is much more suitable reference, I think.
Actually, the sentence "The response must have an ETag header with an entity reference value that implements the notion of entity tags from HTTP" in Chapter 3 refers to RFC 7232.

**Comment by azaroth42** [comment]
Telco discussion on 7/29 agrees, marking as editorial / editor action to fix this. Thanks @tkanai!
