### ISSUE TITLE
"modified" should be in both AnnotationCollection and AnnotationPage

### ISSUE THREAD

**Issue by tkanai** [w3c/web-annotation#332]
Generally speaking, the value of ETag represents each HTTP response body, and it makes easy for clients to detect whether cached data should be updated or not. 

While I was reading EXAMPLE 5, 7 ,10, I couldn't think the ETag value would be changed so frequently and thought it could not be changed even if annotations in the collection have been updated. For example, the value of total has not been changed when the number of added annotations and deleted annotations are the same. It also has not been changed when annotations have been just modified.

The AnnotationPage is designed to be retrieved by sending several GET requests. Since each AnnotationPage response does not provide "collection status", I'm afraid clients could not stop retrieving AnnotationPage, when the collection get new updates during the retrieving process. Besides clients can not make sure whether the retrieved data is a brand new collection or not, due to the issue above.

I think the server should provide "modified" date and time of the collection at where the "total" is required. Good point is the ETag value will be updated without introducing Annotation specific rules.

**Comment by azaroth42** [comment]
Discussed on 7/29 telco and accepted: http://www.w3.org/2016/07/29-annotation-irc#T15-20-34
