### ISSUE TITLE
Protocol examples should use comma separated headers in examples

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#333]
Given that many implementations use a dictionary approach to sending and receiving headers, having multiple headers with the same name will result in data loss, compared to using comma separated values in a single header.

For example the link headers: https://www.w3.org/TR/annotation-protocol/#responses-without-annotations

Plus add a note explaining the rationale.

Discussed: http://www.w3.org/2016/07/29-annotation-irc#T15-45-55

**Comment by BigBlueHat** [comment]
@azaroth42 thoughts?
https://github.com/w3c/web-annotation/commit/a6b358e65a0c0db4808cce3a3b39ceb50d082737

**Comment by azaroth42** [comment]
Looks good. I might combine the second and third paragraphs?

**Comment by BigBlueHat** [comment]
So...we have a new problem...from [RFC 7230 (bottom of page 5)](https://tools.ietf.org/html/rfc7240#page-5):

```
   To avoid any possible ambiguity, individual preference tokens SHOULD
   NOT appear multiple times within a single request.  If any preference
   is specified more than once, only the first instance is to be
   considered.  All subsequent occurrences SHOULD be ignored without
   signaling an error or otherwise altering the processing of the
   request.  This is the only case in which the ordering of preferences
   within a request is considered to be significant.
```

If I'm reading that correctly, the way we're using `Prefer` doesn't work...as the last value "wins" meaning the server can't really use them both together. (Proposal for fixing forthcoming).

**Comment by BigBlueHat** [comment]
So I had this wonderful proposal for fixing this, but just found that it looks like LDP just provides multiple `include` values as space delimited IRIs:

From: https://www.w3.org/TR/ldp/#prefer-examples-direct-membershiponly

> Clients interested only in information about the container (for example, which membership predicate it uses) and its membership might use this hint on a GET request: `Prefer: return=representation; include="http://www.w3.org/ns/ldp#PreferMembership http://www.w3.org/ns/ldp#PreferMinimalContainer"`.

[`include` is not (as yet) a registered preference](http://www.iana.org/assignments/http-parameters/http-parameters.xhtml#preferences), so perhaps we'll need more information added to my note commit that explains its usage. And perhaps we should help LDP (or whoever) get `include` registered.

Thoughts?

**Comment by BigBlueHat** [comment]
Here's the LDP-level definition of the `include` parameter for `Prefer`:
https://www.w3.org/TR/ldp/#h-prefer-include
