### ISSUE TITLE
Processing language for mono-lingual and internationalized resources

### ISSUE THREAD

**Issue by gsergiu** [w3c/web-annotation#342]
The main conclusion of #335 and #337, which is partly implied in the definition of the processingLanguage is that the processingLanguage is not needed for mono-lingual and for internationalized resources, and this should be derived from the dc:language.

The concrete proposal is to add a non normative note indicating that:
"For internationalized resources and mono-lingual resources used in body or target, the dc:language should be provided, and no processing language should be set"

**Comment by r12a** [comment]
I think i'd propose a slight modification to that suggestion:

"For single-language internationalized resources and mono-lingual resources used in body or target, the Language property should be provided, and no processing language should be set."

**Comment by gsergiu** [comment]
@r12a 
Well ... what is the meaning of "single-language internationalized resources"? Do we have a definition somewhere?
Through internationalized resources, I was thinking at something like Dbpedia, were one can get the descriptions in different languages. If one language is provided as dc:language, the client is able to extract the from the reource the text that is available in the given language. 

I don't mind improving this definition, as long as this will be cristal clear for developers.

BR,
Sergiu

**Comment by azaroth42** [comment]
I don't think this is necessary as the spec already says:

> If [`processingLanguage`] is not present and the `language` property is present with a single value, then the client should use that language for processing requirements.

The implication is that you don't need to set `processingLanguage`.  Recommending NOT to say something seems strange ... you can duplicate the information if you want to be explicit.  And as in #343, there might be "en" in one and "en-UK" in the other.

Propose close wontfix.

**Comment by iherman** [comment]
Discussed on 2016-10-28: close, wontfix

See http://www.w3.org/2016/10/28-annotation-irc#T15-17-02

**Comment by gsergiu** [comment]
Well .. I didn't verify the latest version of the specifications, but, at least the older definitions didn't make it clear, why both properties are needed. And I feel that this should be made clear in the standard.

Probably the difference between _language:en_ and _processingLanguage:en-gb_ is the key to clarify the differency between the two properties. 

While the definitions and the meaning is quite similar, I do agree that a creator of an annotation, or the annotation system itself might need to set the processingLanguage:"en-gb", for external resources that have language:"en". 
It seems to me that the main difference between these properties is that language should be the value set by the owner of the external resource (e.g. a meta field in a html page). While the processing language is the values that the annotations system needs in order to process/represent the annotation. 

I think that in the meanwhile was agreed that language should have the same value as the external resource.

I think it will be very usefull for the implementers to be explicitly informed tha the processing language contains the value needed for correct processing/representation of information within the annotation system .

**Comment by aphillips** [comment]
Note (sotto voce): "en-UK" means "English as used in Ukraine". you probably mean "en-GB"

**Comment by azaroth42** [comment]
:blush: Ooops. I did mean -GB, but I expect there are Ukranian differences to English as well :D
