### ISSUE TITLE
Clarify text concerning legal IRIs for Annotation Containers

### ISSUE THREAD

**Issue by halindrome** [w3c/web-annotation#344]
In the Annotation Protocol spec, the language reads:

> Annotation Containers may have any IRI, but must end in a "/" character.

Now, first this is not great spec text.  It should be more precise.  But I know what you mean, and any reasonable person will know what you mean.  However, an IRI has a lot of components.  One way to interpret this is that the literal string representing the IRI must end in a solidus (U+002F).  Another way to interpret this is that the path component of the IRI must end in a solidus.  

I have decided that the most liberal interpretation is required of the spec for 2 reasons.  One, we are already in CR and constraining it further would require a restart.  Two, it makes it much much easier to implement in the test suite.

So, my question for the group is: can I use the following as a container IRI - "client/foo.py?path=annotations/"

I could use an interpretation on this as soon as possible.

**Comment by BigBlueHat** [comment]
The objective of that bit of text--afaict--is to prep for the appending of annotation ID's to the collections IRI when their created.

Your example IRI still fits that particular bill...though, as you state, based on a more liberal interpretation. :smiley: 

@azaroth42 this is probably your fish to fry.

**Comment by azaroth42** [comment]
Yup, the intent is:  

> The Container's URI MUST NOT have a query or fragment component, and the path component MUST end in a "/" character.

Such that when you create an Annotation, you simply put the id/slug on the end of the container's URI.

**Comment by halindrome** [comment]
Is that text you cited in the spec?

**Comment by azaroth42** [comment]
Nope, but it should be :) I've flagged as editorial / editor action

**Comment by halindrome** [comment]
Uggh.  Okay, back to the test framework drawing board.
