### ISSUE TITLE
processLanguage description improvement suggestion

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#345]
https://www.w3.org/TR/annotation-model/#model-1

editorial suggestions

**processingLanguage** property description

> The language to use for text processing algorithms such as line breaking, hyphenation, which font to use, and similar. 

It might be clearer to say:

"The actual language of the Web Resource's content. This information will be used by text processing algorithms such as line breaking, hyphenation, which font to use, and similar. "

**language** property description

> The value of the property SHOULD be a language code following the [bcp47] specification.

I think that should probably say

"The value of the property SHOULD be zero or more comma-separated language tags which follow the [bcp47] specification."

**Comment by gsergiu** [comment]
well ... the new proposal is getting very close to the definition of language.  I think that for language is also ment to be the "actual" languages used in the web resources.

Here the current definition of the language:

> The language of the Web Resource's content. 

 And the proposed definition of the processed language:

> The **actual** language of the Web Resource's content.

The rest of the text in "definition" are only indications where to use it ... but the real definition is only the first sentence of the text, which is almost/excactly the same.

I find better the definition you provided in the tentative conclusions of the usecases document:
http://w3c.github.io/i18n-discuss/notes/annotation-language-use-cases

> Where the language property has a list of languages as its value, the issue is to know which of those languages should be taken to be the default text-processing language (eg. to know that it's ja in our example bo,ja,zh above). 

However we turn it, the processingLanguage has only the meaning of selecting a **"default text processing language"** from the language list.
(this ... is valid as long as the solution proposed in #341 or something similar is not adopted)

**Comment by aphillips** [comment]
@r12a I disagree with this:

> "The value of the property SHOULD be zero or more comma-separated language tags which follow the [bcp47] specification."

There is no point in making the property a list. Making the property into a list makes is superfluous: we already have a `language` property that can appear 0 or more times. The point of having `processingLanguage` is to make it a _single_ language tag that, in the presence of multiple `language` properties, determines the default language used for processing the resource. It only exists because `language` is already a zero-or-more and because `language` is not (in BCP47-parlance) a "language priority list" (that is, multiple values do not have a fallback order).

There is nothing to prevent a resource from actually containing many different languages and the `language` property can already be used to indicate the various languages used. But implementations need an unambiguous way to know which language to use for, say, font selection.

I would also prefer that the normative text say that the value of the property MUST be a well-formed BCP47 language tag.

**Comment by r12a** [comment]
the proposal for 0 or more language tags _is_ for the Language property, not for the processingLanguage property (see the source text in the spec).  I edited my first comment to show more clearly which suggested text refers to which property.  

However, looking again at the description of processingLanguage, i see that it doesn't specify that the value ought to be a BCP47 language tag.  I think it should.

Perhaps we should read the descriptions again fully, rather than just point out the things i happened to have noticed, but it's too late for me to do that tonight.

**Comment by aphillips** [comment]
@r12a My bad. I missed the part where you switched from `processingLanguage` to `language`. But I agree that we should visit the descriptions in total. Perhaps while you're sleeping I can contribute suggestions.

**Comment by gsergiu** [comment]
@r12a let's not mix, the cardinality with the definition. I understand that you have the problem with the cardinality of dc:language, but there is no good reason to introduce a different property with the same meaning/definition, but with a different cardinality. 

If the meaning of the processingLanguage is to select the default value form the list of values available in the dc:language, its definitions should be updated to express this meaning. 
There is no need to dupplicate the definition. 

So ... the definition which describes the meaning of the property, has nothing to do with the cardinality or ... format. 

From my side there is no problem to recommend BCP47 as preffered format for both dc:language and processingLanguage.

**Comment by azaroth42** [comment]
Language is already 0..*, with a SHOULD for 1. I'm not sure that I see the value or usecases for changing that at this stage.  It shouldn't be comma separated in a single JSON string... for multiple languages it would be:

```
 "language": ["en", "cy", "de"]
```

I don't think that the proposed change for `processingLanguage`'s description makes it clearer. The current definition is focused on the use, which is the reason for the property's existence compared to the `language` property.

The lack of BCP47 in `processingLanguage` is definitely an oversight.

Proposal:
- Add the same BCP47 recommendation to `processingLanguage`.

**Comment by iherman** [comment]
Discussed 2016-10-28: the group conditionally agree with the proposal, provided @r12a agrees; if so, then the issue can be closed (more exactly, turned into editorial action)

See: http://www.w3.org/2016/10/28-annotation-irc#T15-27-38

**Comment by azaroth42** [comment]
Note that this requirement is already in the vocab: https://www.w3.org/TR/annotation-vocab/#processinglanguage

**Comment by r12a** [comment]
commenter satisfied
