### ISSUE TITLE
Add info about which Media Type to Model

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#346]
The [protocol states](https://www.w3.org/TR/annotation-protocol/#h-summary):

> The media type to use for Annotations is: application/ld+json;profile="http://www.w3.org/ns/anno.jsonld"

The model document, however, currently doesn't mention what media type should be used when serving documents that use the model.

Adding a quick note (perhaps with links to the protocol) seems prudent.

**Comment by azaroth42** [comment]
"Serving" is covered by the protocol.  I'm okay with a non-normative reference from model to protocol.
I suggest in section 1.2, mirroring the reference to the vocab.
