### ISSUE TITLE
Avoid mixed-content error with JSON-LD context in HTTPS

### ISSUE THREAD

**Issue by csarven** [w3c/web-annotation#347]
Editorial change:

If a document is loaded over HTTPS, JSON-LD libraries are subject to getting the mixed-content error in the browser if `@context` uses HTTP: `http://www.w3.org/ns/anno.jsonld`

Perhaps change (especially the examples) to use `https://www.w3.org/ns/anno.jsonld` to avoid this possibility altogether.

**Comment by azaroth42** [comment]
I thought that we decided that both the context and the namespace were to remain HTTP. The context document is the identifier for the profile, and thus should dereference in the same way as a namespace's URI does.

I disagree that this is editorial, as it changes normative requirements for every annotation.

**Comment by csarven** [comment]
I only recall the ns staying at HTTP.

I think this is editorial because it exemplifies the use of HTTPS over HTTP as the most desirable approach. In my implementation, I've noticed that if the context is HTTP, mixed-content error is thrown because the client-side RDF library tries to dereference it as is - i.e., it doesn't pass the context URL through an HTTPS proxy to avoid this when the origin is HTTP. Should libraries and implementations be forced to override or ignore the context? This is just additional processing that no one wants to deal with. Naturally publishers are free to use the HTTP or HTTPS, but why not set a good example?

The schemes of the URLs in context can stay HTTP, it is only the reference to the context URL that should be HTTPS.

Just my two :moneybag:

**Comment by iherman** [comment]
It is certainly not an editorial change. The document normatively refers to the context document using HTTP; the examples should not use a different URI. Ie, the change requires a change in the normative text, hence this is definitely _not_ editorial.

I think we should defer the decision until we get several implementation report and see whether the majority of implementors have hit this issue. If so, we should make the change for the PR, but we can try to convince the Director not to induce a new CR round due to this. To preempt the problem, we may want to contact all implementers we know about to focus on this issue and give us feedback.

**Comment by BigBlueHat** [comment]
I'd prefer client implementers (and/or their underlying libraries) do their own preference handling when it comes to (in)secure requests.

The name we use should remain unchanged and "http://" is the more flexible/"upgrade-able" of the two protocol schemes, so using that one seems prudent for longevity.

**Comment by BigBlueHat** [comment]
Looks like Schema.org will be treating theirs as equivalent: https://schema.org/docs/faq.html#19

Seems like a sensible approach.

**Comment by csarven** [comment]
There is an equivalent issue at https://github.com/w3c/activitystreams/issues/351

**Comment by csarven** [comment]
Okay to defer the decision. Also agree with https://github.com/w3c/web-annotation/issues/347#issuecomment-240118895

**Comment by gsergiu** [comment]
by following the schema.org answer:

> this is a lengthy way of saying that both 'https://schema.org' and 'http://schema.org' are fine. 

Is there a technical solution to solve this issue on the server side?
I assume that there is no problem to put the schema available both under 
http://www.w3.org/ns/anno.jsonld and https://www.w3.org/ns/anno.jsonld.
(probably a forward rule in apache server is suffiecient)

@azaroth42 @BigBlueHat 
Could we write a non normative note, indicating that server implementations that run on https, may use the https context?

**Comment by gsergiu** [comment]
@csarven this seems to be a problem of the RDF client you are using. I'm not sure if it is possible to "downgrade" the serverity of the message in your client from error to warning. (basically, both servers are delivering their cotnent correctly, it is only your client that denies the response)

**Comment by csarven** [comment]
It is fairly common to experience a mixed-content error in Web browsers with their default settings. So, while I agree that RDF libraries should be smarter on how they handle this (as I've mentioned, using a proxy is one way), it is not an edge case in my opinion, at least currently.

It is primarily the examples that concern me, and that the publishers copying these with the http context could cause issues for https clients we could otherwise avoid.

I'd like to suggest that the ns should stay as http, i.e., the URIs inside context use http. So, both http and https context URLs should use http for the ns. This is so that both will continue to function if/when http can be treated as secure. Down the line, publishing with https context may no longer be needed and no further changes to the ns itself will be required.

A note suggesting that both http and https context should be treated equal with the caveat/warning to publishers that if they use http, some clients may experience mixed-content errors.

**Comment by azaroth42** [comment]
I think it is an edge case, as the number of browser based clients that will dynamically dereference the context and use it to interpret the content that it has received as triples is probably countable on zero fingers. Any realistic browser-based client that needs the context will simply provide a copy of it, as it can't change once we hit TR so there's no risk of it going stale.

Annotations MUST use the http context URI. So publishers MUST, in fact, copy the examples as use that URI:

> The Annotation MUST have 1 or more @context values and http://www.w3.org/ns/anno.jsonld MUST be one of them.

**Comment by gsergiu** [comment]
@azaroth42 
ok ...
Does this mean that https://www.w3.org/ns/anno.jsonld is not allowed/valid?
Or .. does this mean that @context: ["http://www.w3.org/ns/anno.jsonld", "https://www.w3.org/ns/anno.jsonld"] is not allowed?

**Comment by gsergiu** [comment]
@csarven well ... I think that the browsers are not doing performing automatically the dereferencing , ... so the copy-paste into browsers cannot be a problem. (the problem might be in some javascript clients that run in browser ... that's different)

**Comment by azaroth42** [comment]
Technically

```
{
 "@context": ["http://www.w3.org/ns/anno.jsonld", "https://www.w3.org/ns/anno.jsonld"]
}
```

would be allowed, it would just be totally pointless, as the interpretation would be that each entry in the list is a different context, and thus the client would need to dereference the HTTP context as well as the HTTPS context.

**Comment by gsergiu** [comment]
@azaroth42 
you are right ... I was just thinking if we should prevent people of doing stupid things. 
So .. the conclusion is that "https://www.w3.org/ns/anno.jsonld" is not allowed/(recommended) to be used in the context according to the current specification.

Should we really have such a constraint?
Could we say that "http://www.w3.org/ns/anno.jsonld" or "https://www.w3.org/ns/anno.jsonld" must be in the context list?

**Comment by csarven** [comment]
I'm okay to drop this issue with acknowledgement that clients should handle this appropriately. Feel free to close at will.

+1 to requiring the canonical context URI (in http). If implementations encounter both http and https they should probably equate them - maybe this need not be said. The https context uses the http ns any way.
