### ISSUE TITLE
Provide requirements guidance for future additions/modifications to OA namespace

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#355]
The ontology documentation should provide explicit requirements for how additions and/or modifications can be made, to prevent arbitrary and possibly conflicting statements to be added.

Proposal:

> Any changes to this document MUST be from a Working Group in the W3C, that explicitly references the Web Annotation model, vocabulary and/or protocol in their charter.

**Comment by iherman** [comment]
Proposal accepted: "Any changes to this document MUST be from a Working Group in the W3C that has established expertise in the area"

To be put into ontology documentation

See http://www.w3.org/2016/09/30-annotation-irc#T15-15-21
