### ISSUE TITLE
Examples of Implementations

### ISSUE THREAD

**Issue by RicardoUsbeck** [w3c/web-annotation#356]
Dear all, 

I am looking for example implementations of https://www.w3.org/TR/annotation-vocab/ similar to DBpedia Spotlight + NIF. 

Any pointers to relevant resources would be appreciated. 

Thank you very much.
Ricardo

**Comment by fsasaki** [comment]
See this mail thread
https://lists.w3.org/Archives/Public/public-annotation/2016Apr/0041.html

and an example request here

http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?input=Berlin&informat=text&outformat=turtle&language=en&dataset=dbpedia&mode=all&filter=freme-ner-output-as-web-annotation

the underlying framework is worked on by @jnehring, putting him into the loop FYI.

**Comment by azaroth42** [comment]
This isn't an actual issue, so am closing it.  Feel free to join and discuss on the public-annotation WG list, or the open annotation community group :)

**Comment by RicardoUsbeck** [comment]
Thanks for the pointers!
