### ISSUE TITLE
Clarify that TextualBody can be the source of a SpecificResource or target of Annotation

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#357]
Any rdfs:Resource can be the source of a SpecificResource, and a TextualBody is a Resource.  The name implies that it must only be used as the object of hasBody, but that's just where it would typically be found, not the only place it can be found.

Use cases:
- Associating a style with a TextualBody
- Associating a renderer with a particular format of a TextualBody
- An annotation on the Body to note a typo

**Comment by iherman** [comment]
Resolution: it is possible, but no reason to change anything in the document.

See http://www.w3.org/2016/09/30-annotation-irc#T15-21-44
