### ISSUE TITLE
HttpRequestState used in eg44, but is not in context

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/web-annotation#358]
Example44 https://www.w3.org/TR/annotation-model/#complete-example uses

```
"type": "HttpRequestState",
```

However, this type is not defined in http://www.w3.org/ns/anno.jsonld, so this `RIOT -out ttl` resolves this as a local (filesystem) URL

**Comment by azaroth42** [comment]
The example should be `"HttpState"`, not `"HttpRequestState"`.
Good catch, thanks @VladimirAlexiev!

**Comment by azaroth42** [comment]
Actually, as @iherman pointed out to me, the spec uses HttpRequestState throughout, so the context is the bug.

**Comment by VladimirAlexiev** [comment]
This is how the example looks. Made with rdfpuml but had to fake the blank nodes: maybe I should extend rdfpuml to handle them properly.
![oa-eg44](https://cloud.githubusercontent.com/assets/536250/18988720/9a6f7452-8710-11e6-9477-0aae38f8c2c0.png)

**Comment by iherman** [comment]
The context document must be added to add HttpRequestState

See http://www.w3.org/2016/09/30-annotation-irc#T15-23-50
