### ISSUE TITLE
JSON-LD contexts for Model/Protocol

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#36]
The protocol currently refers to the model's default JSON LD context.  However it requires additional protocol specific features beyond the annotation model itself, such as ldp:contains, ldp:BasicContainer, iana:alternate and similar.

We would be mixing concerns by including those protocol specific features into the model's context document.  Similarly, if we included all of the model's features into the protocol's context.  There is the option for multiple context documents, however this is not known to be a common pattern.

Proposal:  Create a common context document with both the protocol and model's features and reference from both.  This might make for administrative challenges (e.g. a revision of the protocol specification will change something referenced by the model) in the future, but better than requiring multiple contexts.

**Comment by iherman** [comment]
+1 to this proposal

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by tilgovi** [comment]
+1

**Comment by azaroth42** [comment]
And related to #35, which needs to reference the context, it would live in the model spec even though it defines [a few] features related to the protocol.

**Comment by azaroth42** [comment]
Resolved in Oct 2015 WD
