### ISSUE TITLE
Clarification on the usage of rights in the example use case

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#360]
(Copied a [mail](http://www.w3.org/mid/7C2AC417-FBF0-400E-A68E-D9BC3CF5AC2D@monegraph.com) of @riannella to the issues' list to ensure proper tracking.)

In the Annotation Model Rights Informations section [1], the example Use Case mentions 2 licenses - one for the “Annotation" and one for the “Body”.

However, its not clear then what the Annotation is (from an intellectual property rights perspective). For example, in Section 3.1 it says that "Typically, an Annotation has a single Body…"

Some clarity on this would be useful.

Also, the rights statement “MUST” be a IRI - can it not also be some embedded JSON?

[1] https://www.w3.org/TR/annotation-model/#rights-information

**Comment by azaroth42** [comment]
The first issue is "What does it mean to have a license associated with an Annotation and a different one associated with a Body".  The intent is that the Annotation document and its semantics can be used according to the license associated with it.  That could be more or less restrictive than any rights asserted over the Body, Target or other resource.

Per the example in the model document, Ramona wants to be knows as the author of the Body content, and does not want that document to be used commercially, and hence asserts CC-BY-NC for the Body.  However the annotation does not include the Body directly, nor can one infer any properties of the Annotation as relating to any given Body.  The Annotation is the document that links the Body (or Bodies) to the Target (or Targets), and Ramona is happy for anyone to use this document in any way they want, hence asserts CC-0. 

Another scenario is where the creator of the Annotation is not the creator of the Body or Target.  I could link a video on Youtube as the body to an image in Flickr as the target, without being the rights holder for either of those two resources. I can put my Annotation under CC-0 without affecting the rights of the video or image.

Editorial action to consider how this might be clarified in the document.

The second issue is whether some expression of the rights statement can be embedded within the Annotation.  The intent of the working group is to not allow this, as it complicates the model and there isn't a good normative reference for what implementers should expect to encounter (that we know of).  Instead, if there are (now or in the future) such expressions, they can be published at an IRI and that IRI referenced from the Annotation.  If there is a compatible (e.g. RDF with JSON-LD expression) model available, a future version of the specification could refer to it directly.

So the answer to the second part is no, it MUST be an IRI, per the specification.  No action needed for this, beyond perhaps a little more text in the model document to clarify the intent.

**Comment by iherman** [comment]
Just adding cc @riannella to call his attention :-)

**Comment by riannella** [comment]
You say "However the annotation does not include the Body directly" - what happens if it did?

**Comment by riannella** [comment]
There is a w3c normative spec (see W3C POE WG) coming that specifies rights statements.

**Comment by azaroth42** [comment]
If it did embed the body, they're still modeled as separate resources, just like multiple targets are. So you could still assert different licenses for each body, target and the annotation. Being embedded in the annotation serialization is a convenience for clients to prevent the need to dereference everything separately.

**Comment by riannella** [comment]
Maybe its just the Use Case then...what is the "work" (intellectual content) that is then being licenced as CC0?

**Comment by BigBlueHat** [comment]
@riannella the CC0 bit is just the interstitial connective tissue. It references to additional works: target and body. In the [example](https://www.w3.org/TR/annotation-model/#example-14) the `body` is an `SpecificResource` (vs. a `TextualBody`).

Here's what it would look like if that resource were "inlined" as a `TextualBody`:

``` json
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno19",
  "type": "Annotation",
  "rights": "https://creativecommons.org/publicdomain/zero/1.0/",
  "body": {
    "value": "Really great product! More people should by it!!1!",
    "language": "en",
    "format": "text/plain",
    "purpose": ["assessing", "commenting"],
    "rights": "http://creativecommons.org/licenses/by-nc/4.0/"
  },
  "target": "http://example.com/product1"
}
```

The `body` is CC-by-NC and the interstitial annotation is CC0.

Clearer? :sunglasses:

**Comment by riannella** [comment]
I can't see any intellectual property (ie a "work") in the "interstitial connective tissue" ;-)
I suggest that rights can be assigned to the bodies (individually) _or_ the annotation (as a whole) but not both cases.

**Comment by azaroth42** [comment]
I think we should leave such a ruling up to the legal system in the future if it ever becomes an issue.
If the activity of linking resources together with a motivation (which can be considered a type for many purposes) does not constitute IPR, then RDF itself would not constitute something that has IPR. And _that_ would be quite a shock to many organizations.

I propose close, won't fix.

**Comment by riannella** [comment]
Well, you have made that call in the Spec. You have provided a use case and example that clearly states you can license facts like:

"@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno19",
  "type": "Annotation",
  "rights": "https://creativecommons.org/publicdomain/zero/1.0/",
  "target": "http://example.com/product1"

I suggest the WG gets legal advice.

**Comment by BigBlueHat** [comment]
@riannella as far as I can tell, we haven't stated that one can license the facts just that if you are asserting rights over those statements, that's where you'd put them. Whether or not any legal system on the planet will care (or how much and to what end) is certainly beyond the scope of this group.

RDF as IPR, though, does seem to fall decidedly in the lap of the POE WG, however. Likely, you'll bee seeing a few of us join that WG and mailing lists in hopes of at least watching how it plays out. :smile: 

Additionally, we can't run on the assumption that the Annotation and Body (and certainly not the Targets) are made at the same time, or by the same entity, etc. It's completely possible for an annotation to be created by myself, targeting a work written eons ago, and using it's Wikipedia page as one (but not the only) body--such that each of those things MAY have its own `rights` statement assigned within the Annotation, and would certainly have it's own copyright, license, etc.
