### ISSUE TITLE
Remove un-implemented List, Composite, Independents

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#369]
In order to exit CR, we need to remove List, Composite and Independents as they are not implemented in any product.

If there isn't an implementation using them today, we need to take them out. If there is, then we need to get them tested and into the report.

If there's no implementation before 11/11/2016, they will be removed.

**Comment by azaroth42** [comment]
An implementation of Composite:
  http://ghp.wellcomecollection.org/annotation-viewer/quilt/

**Comment by iherman** [comment]
Having checked with the director:
-   it is all right to put unimplemented, but at-risk features into an informative appendix, while remove it from the main spec
-   however, if a feature that was _not_ identified as 'at risk' does not get through the exit criteria, then it should be removed (and may be put into the appendix) but, formally, a new CR should be published (albeit with a short short cycle) before going to Proposed Rec

As discussed on a call, that means that two documented implementations of 'Choice' would be necessary to go the Proposed Rec directly...

**Comment by azaroth42** [comment]
Extended to include removal of Creator and Choice for Targets, and bodyValue property of the Annotation, lacking implementations.

**Comment by iherman** [comment]
With the publication of 3rd CR (22nd of November), this issue is now closed.
