### ISSUE TITLE
Annotation Containers should permit non- ldp:BasicContainer

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#37]
The protocol specification currently _requires_ that Annotation Containers be implementations of ldp:BasicContainer.  This prevents implementations from using other types of Container, such as Direct or Indirect Containers or any defined in the future, even if they may be appropriate for business needs.

Use Case:  In managing a list of annotations, an LDP implementer wants to use a direct container to assert the membership of newly created annotations within the list which is separate from the container itself.  This would most easily be done with a DirectContainer, but this is not possible as the Annotation Container must be Basic.

Note that BasicContainer and DirectContainer are siblings in the LDP class hierarchy, even though DirectContainer could trivally be a more specific subClassOf BasicContainer. :crying_cat_face: 

Proposal:  Benjamin and Rob to craft spec text that promotes a default of Basic, but allows for others when appropriate.

**Comment by iherman** [comment]
Just adding a link for an easier understanding: http://www.w3.org/TR/ldp-primer/#navandret gives an example for usage of a DirectContainer. (There are also other example in that primer.)

**Comment by iherman** [comment]
Rob, I would like to see the use case a bit expanded, because I am not sure I follow it exactly.

What I am worried about is that if the server is allowed to handle Direct Containers, that means that a generic client, if it wants to be independent of a particular server, must implement that management of the results of a Direct Container. That means it has to understand a kind of an indirection on the membership property; not sure client implementations will be happy...

**Comment by azaroth42** [comment]
There should be no difference from the client's perspective, otherwise I agree that it would be better to pick exactly one.  The client requests are identical, but the response needs to identify that it's a DirectContainer. The main difference is that there will be other triples generated in the background, associated with resources other than the Annotation or the Container.

**Comment by iherman** [comment]
Ah. Let me try to remember: the responses from a DirectContainer include the same triples as the BasicContainer _plus_ a copy of those that use a dedicated (and settable) property, right? If that is so, then indeed a client may simply ignore a DirectContainer, so there is no real problem.

**Comment by tcole3** [comment]
This seems a potentially useful change. A few questions first though to make sure I am understanding the implications correctly (and then separately a possible proposal):
1) The list of annotations (call it AList) can itself be a LDP-RS (i.e., AList does not have to be an LDP Container). Is this correct?
2) Even though they are part of AList through the membershipResource predicate of the Direct Container in which they are contained, the listed Annotations can be retrieved individually and independently AList directly from their Direct Container. Is this correct?
3) Would/could retrieving (GET) AList retrieve a graph that includes as sub graphs all of the listed annotations, e.g., just as retrieving the http://example.org/netWorth/nw1/ LDP-RS in the LDP 1.0 spec retrieves all of the assets and liabilities contained in the associated Direct Containers? 
4) Can the Prefer Request header (with appropriate include and/or omit parameters) be used to retrieve a shorter representation of the AList resource (or does this approach only work with LDP Containers)?

**Comment by tcole3** [comment]
For some use cases, the granularity of oa:Annotation is somewhat limiting. There appears to be value in being able to work with lists, clusters or sets of annotations. The use of LDP Direct Containers seems to suggest a way to efficiently manage and retrieve annotations in a list or set. 

Could the protocol go further in this direction and provide an equally efficient way to Create annotation lists or sets, e.g., a way to post in a single graph, a single LDP-RS that includes multiple annotations. This would raise the bar a bit for the server -- e.g., might require implicitly the creation and population of a Direct Container for all the included annotations, more could always be added by subsequently posting to the Direct Container -- but being able to post multiple annotations in a single graph could be seen as making life easier for the client and would support a more transactional interaction, e.g., these 3 related annotations all need to be created together or not all. 

Would this approach require adding an AnnotationList class to the data model?

**Comment by azaroth42** [comment]
Closing ... fixed in latest WD
