### ISSUE TITLE
TLDR prevention at beginning? of Protocol

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#38]
Most of the Protocol spec is totally uninspiringly obvious to anyone who has thought about REST for more than 5 minutes, or anyone who has read the LDP spec.  It would be advantageous to have a summary of the additional constraints easily available, rather than requiring adopters to read through the entire doc and pick them out individually.  This could be at the beginning or an appendix clearly referenced at the beginning.

**Comment by iherman** [comment]
+1 to this.

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by tilgovi** [comment]
+1

**Comment by cmbirk** [comment]
Yes.  A summary would be great so that we have an idea of what tests need to be built on top of the existing LDP tests.

**Comment by fhirsch** [comment]
+1

**Comment by paolociccarese** [comment]
+1

**Comment by iherman** [comment]
Discussed and resolved on telco: http://www.w3.org/2015/06/24-annotation-irc#T15-42-06-1
