### ISSUE TITLE
If-Match not used in PUT protocol test

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#386]
The test that checks whether an annotation can be updated using PUT doesn't send If-Match, and hence a server that respects the SHOULD in the second paragraph of https://www.w3.org/TR/annotation-protocol/#update-an-existing-annotation will fail the request, and thus fail the test.

Can we improve the test to first do a GET on the annotation URI, check for the ETag and then send the correct If-Match header?

**Comment by halindrome** [comment]
I will fix this today.

**Comment by halindrome** [comment]
I have updated the server tests to use this.  Note that it will probably BREAK other implementations that were passing because we are now requiring an additional header that needs to be in the CORS permissions.

**Comment by iherman** [comment]
@azaroth42 @BigBlueHat I will close this specific issue, but you should look at the implementation issues raised by @halindrome ASAP...
