### ISSUE TITLE
Should all responses have the anno json-ld profile?

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#39]
Should all responses from Annotation Servers where the entity-body is a serialized annotation have a Content-Type of application/json+ld with the profile URI for the annotation profile?  As most servers will have to explicitly set the content-type header, rather than allowing it to be set by an upstream system (such as apache's mod_mime_magic or similar) the implementation cost seems low.

It doesn't seem totally necessary, but could be useful for systems that do support multiple profiles.  Better to be liberal with what you accept and strict with what you send.

**Comment by tilgovi** [comment]
> be liberal with what you accept and strict with what you send

Does that imply we should add some SHOULD language around it? If so, +1

**Comment by azaroth42** [comment]
+1 to SHOULD

**Comment by iherman** [comment]
fine with me 

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by fhirsch** [comment]
+1 to SHOULD

**Comment by cmbirk** [comment]
+1 to SHOULD

**Comment by pciccarese** [comment]
+1 to SHOULD

**Comment by azaroth42** [comment]
Noting https://tools.ietf.org/html/rfc6839#section-3.1 regarding requirements around *+json [from SocialWG discussion on content types]. Also in latest HTTP spec, the ability to provide a media type parameter is clarified as possible in the Accept header, thus making content negotiation using media types feasible. There was some statements that it's not necessarily implemented ... but neither is conneg :)

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/protocol/wd/#annotation-retrieval

**Comment by akuckartz** [comment]
:smile:
