### ISSUE TITLE
Fix SVG 1.0 to SVG 1.1 reference 

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#392]
Normative reference is to SVG 1.0 and should be to SVG 1.1.  Change the respec reference to SVG11 from just SVG.

**Comment by halindrome** [comment]
I verify that this change will work correctly in ReSpec (changing [[SVG]] to [[SVG11]]) and that such a reference is correct from the context of the overall specification - in other words, that there are no significant changes to the annotation model, vocabulary, or protocol implied by changing this reference.
