### ISSUE TITLE
oa:assessing missing from anno.jsonld context

### ISSUE THREAD

**Issue by musicog** [w3c/web-annotation#444]
When oa:reviewing was changed into oa:assessing (see issue #249) it appears that this update was omitted on the [anno.jsonld](https://www.w3.org/ns/anno.jsonld) context, which still lists:

`"reviewing": "oa:reviewing"`

but does not list

`"assessing": "oa:assessing"`

The change *has* been made in other places including the [data model recommendation document](https://www.w3.org/TR/annotation-model/#motivation-and-purpose) and in the [ontology specification](https://www.w3.org/ns/oa#assessing) (where `assessing` has replaced `reviewing`), but this appears to have been missed for the jsonld context.

**Comment by iherman** [comment]
The missing statement has been added.
