### ISSUE TITLE
Cloudflare is too afraid to grant me read access to w3.org

### ISSUE THREAD

**Issue by mk-pmb** [w3c/web-annotation#450]
Hi! This is probably not the right place to report it. I tried visiting the main page https://www.w3.org/ to find a better contact, but it seems I'm banned from the entire server. My original attempt was to read https://www.w3.org/TR/annotation-model/ .

It seems my criticism of Dublin Core from #446 now applies to W3, too.

I have no idea what misbehavior Cloudflare deems me suspicious of, but I think I should be granted mere read access (at a sane rate limit) unconditionally, independent of whether I'm "human" ([whatever that may mean](https://www.youtube.com/watch?v=fsF7enQY8uI)) or whether I'm using TOR.

**Comment by gosko** [comment]
Hi, this issue with the W3C site should be resolved, as of Oct 2023.

**Comment by mk-pmb** [comment]
Thanks!
I just tried and it works now. I'm too lazy to test multiple other exit nodes, so I'll close it for now and let's all hope that it's really solved.
