### ISSUE TITLE
add reference to Annotation Protocol to Model

### ISSUE THREAD

**Issue by fhirsch** [w3c/web-annotation#47]
Add Web Annotation Protocol informative reference to Model

see https://lists.w3.org/Archives/Public/public-annotation/2015Jun/0295.html

Specifically, update introduction 2nd to last paragraph from 

"A further specification will be written that standardizes the transport protocol, which may be adopted separately."

to

"See the Web Annotation Protocol [Web_Annotation_Protocol] for details."

and add reference

[Web-Annotation-Protocol] Sanderson, R. "Web Annotation Protocol", 2 July 2015 http://www.w3.org/TR/annotation-protocol/

I've also shared this proposal as an annotation , see https://lists.w3.org/Archives/Public/public-annotation/2015Jul/0024.html

(apologies I thought by replying the subject would be filled in automatically on the email etc)

**Comment by azaroth42** [comment]
+1 willfix

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#introduction
