### ISSUE TITLE
Absolute or relative URI's in examples

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#57]
Turtle uses relative:
https://github.com/w3c/web-annotation/blob/gh-pages/model/wd/examples/correct/anno_1.ttl

JSON-LD uses absolute:
https://github.com/w3c/web-annotation/blob/gh-pages/model/wd/examples/correct/anno_1.json

Which...at least in the context of those two specific files means they both have different meanings currently--as the Turtle doesn't map to `example.com` URIs.

Guessing whichever we pick they should be consistent, yeah?

@azaroth42 happy to submit a PR if you agree. :smile:

**Comment by azaroth42** [comment]
I can re-extract all of the turtle and add:

```
@base <http://example.org/> .
```

Which would do the trick, I think?

**Comment by BigBlueHat** [comment]
Fixed in https://github.com/w3c/web-annotation/pull/58
