### ISSUE TITLE
Allow Digitally Signed Annotations

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#6]
Being certain that a given annotation was indeed created by the asserted author is important in some disciplines.  For example, in scholarly communication it is important to know who reviewed a paper as a peer's criticism would be regarded more highly than a random individual from the internet.  In highly controlled environments this may be taken care of by authentication/authorization, but in a distributed system digital signatures could provide an alternative solution.

A pre Open Annotation implementation of signed annotations: [Fab4](https://code.google.com/p/fab4browser/)

**Justification**

Reputation attacks and other spoofing would be easy in an environment that does not have digitally signed content.  For trust networks to be built, the data needs to be both distributed and reliable.

**Proposal**

Requires further discussion.

**Background**

Digitally signed annotations were brought up and rejected as overly complex for the first iteration in the community group. 

**Links**
- [Tracker](http://www.w3.org/annotation/track/issues/4)

**Comment by shepazu** [comment]
I suggest that we defer this issue. 

I agree with the use case, but I'm concerned that this is too complex to solve for v1 of the spec. 

I also strongly feel that we should leverage a general web-platform-level digital signing approach, either existing or new, rather than create a mechanism specifically for web annotations.

For the present, I suggest that we do 2 things:
- document our use cases and requirements, to drive the creation or repurposing of a general digital signing mechanism
- leave a hook in place in the current data model, possibly in the provenance/author node, to plug in a digital signing mechanism later.

**Comment by iherman** [comment]
On 14 Oct 2014, at 24:26 , Doug Schepers notifications@github.com wrote:

> I suggest that we defer this issue.

+1

> I agree with the use case, but I'm concerned that this is too complex to solve for v1 of the spec.
> 
> I also strongly feel that we should leverage a general web-platform-level digital signing approach, either existing or new, rather than create a mechanism specifically for web annotations.
> 
> For the present, I suggest that we do 2 things:
> 
>   • document our use cases and requirements, to drive the creation or repurposing of a general digital signing mechanism
>   • leave a hook in place in the current data model, possibly in the provenance/author node, to plug in a digital signing mechanism later.

Yep. We can have an explicit hook to refer to a signature, without specifying what technology should be used.

I.

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me

**Comment by tilgovi** [comment]
> leave a hook in place in the current data model, possibly in the provenance/author node, to plug in a digital signing mechanism later.

I'm not even sure that much is necessary. Just as access control mechanisms can be considered out of scope and managed at a different layer, so too signatures.

**Comment by iherman** [comment]
On 14 Oct 2014, at 08:27 , Randall Leeds notifications@github.com wrote:

> leave a hook in place in the current data model, possibly in the provenance/author node, to plug in a digital signing mechanism later.
> 
> I'm not even sure that much is necessary. Just as access control mechanisms can be considered out of scope and managed at a different layer, so too signatures.

That may not be exactly the same. Access control is indeed outside the model in the sense that you do not expect AC data to be part of the data you store, that may not be the same with the signature that may have to 'travel' with the data.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me

**Comment by ericprud** [comment]
- Doug Schepers notifications@github.com [2014-10-13 14:26-0700]
  > I suggest that we defer this issue. 
  > 
  > I agree with the use case, but I'm concerned that this is too complex to solve for v1 of the spec. 
  > 
  > I also strongly feel that we should leverage a general web-platform-level digital signing approach, either existing or new, rather than create a mechanism specifically for web annotations.

This is becoming a critical issue for me in clinical informatics where
everything's a speach act and there's a lot of legal need to record he
said-she said chains of assertions. I'm getting questions like "Is it
OK for a transform be run prior to signing if that transform isn't
isn't recorded in the signature's Reference element?"

It's in my best interest if you guys take on signatures and solve all
my problems for me. Barring that, who are the current experts in this
and who in annotations would be interested in working with me with the
expectation that this effort will benefit annotations (V2)?

> For the present, I suggest that we do 2 things:
> - document our use cases and requirements, to drive the creation or repurposing of a general digital signing mechanism
> - leave a hook in place in the current data model, possibly in the provenance/author node, to plug in a digital signing mechanism later.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/web-annotation/issues/6#issuecomment-58957286

## 

-ericP

office: +1.617.599.3509
mobile: +33.6.80.80.35.59

(eric@w3.org)
Feel free to forward this message to any list for any purpose other than
email address distribution.

There are subtle nuances encoded in font variation and clever layout
which can only be seen by printing this message on high-clay paper.

**Comment by fhirsch** [comment]
I agree with this.

We may wish to  record issues such as this with ‘wish’ for a wish list and maybe create a wiki so we do not lose track.

regards, Frederick

**Comment by azaroth42** [comment]
Discussion in the Social WG about:
  https://datatracker.ietf.org/doc/rfc7165/  
And related docs:
  https://datatracker.ietf.org/wg/jose/documents/

Also the Web Payments secure messaging:
  https://web-payments.org/specs/source/secure-messaging/

Which is to say I think we should close the issue as being solved elsewhere and out of scope for this WG.

**Comment by tilgovi** [comment]
> Which is to say I think we should close the issue as being solved elsewhere and out of scope for this WG.

:+1:

**Comment by shepazu** [comment]
+1 to mark this as solved elsewhere.

Do we still need to leave a hook in the model for the digital signature? Some part of the Provenance / author vocabulary? Even if we don't have a formal hook, we might have an informative note in the spec about where a digital signature should go, if there is one. http://w3c.github.io/web-annotation/model_fpwd/static.html#h3_provenance

**Comment by tilgovi** [comment]
I'm not sure we do. For instance, take JWS (from the JOSE spec[0]). With that, I would take an annotation, serialize it to JSON-LD, and then encode it and concatenate it as header.payload.signature. The header specifies the algorithms, etc. The payload is just a base64 encoding of the JSON, if I recall correctly, and I imagine there's some canonicalization of key order and whitespace.

However, what does this tell me? It tells me very little, unless I can associate the key used for signing with some aspect of the annotation, such as its author.

So, I sort of wonder whether we need anything additional beyond what we offer in our model and, maybe PROV. For what we have in our vocab, if the key can be discovered to belong to the annotatedBy or serializedBy agents, then we've managed to assert the integrity of the annotation as authored or as serialized.

I think there's always the question, "who signed it and why?" or the signature is rather meaningless. The relationship between the annotation and that signing agent is probably out of scope, and maybe discovered out of band, while the signed thing is actually a serialization and therefore not really part of the model.

That was maybe a bit confused, but here's a different take: I think we have enough in the model to relate the annotation to any agent that would likely be signing it, else other models can be added into the mix.

I hope that makes any sense.

[0] https://tools.ietf.org/html/draft-ietf-jose-json-web-encryption-36

**Comment by azaroth42** [comment]
I don't think we need a hook in the model, but do we need to make a decision as part of protocol?

**Comment by tilgovi** [comment]
I don't think so.

**Comment by azaroth42** [comment]
How would a client or server know that the content received was encrypted JSON (potentially using JOSE, as previously) rather than line noise? :)  Just rely on the external specifications to make that transparent, and write protocol in such a way as to allow it?  I'm thinking that when we have a test suite, it would reject any encrypted content ... so if we want to allow it, we need to be explicit somewhere?

**Comment by fhirsch** [comment]
We need to distinguish signing and encryption

Signed JSON would be JSON with some signature properties in addition to the content. Thus there would be additional information that could be ignored. That said, I'd suggest this is out of scope of the annotation work itself as JSON signatures can be applied to any JSON regardless of content and it would increase the testing significantly.

Encryption is a different matter; in that case the annotation content would not be visible. It would be recognizable JSON,  including encryption meta information as well as the encrypted content but that encrypted content would not be visible until decrypted.

**Comment by tilgovi** [comment]
If the annotations are encrypted such that the server cannot read them then they are blobs, not annotations. If the annotation is encrypted such that the server can decrypt them, then encryption is layered on top and I don't think it's our concern.

**Comment by stain** [comment]
This sounds out of scope. Provenance of who made the annotation is however important - but it should be up to the server if it enforces this based on authentication or trusts whatever the client claims. (This could be noted under Security aspects)

**Comment by fhirsch** [comment]
+1 to out of scope; similar to zip files in the sense that annotations might be contained within another JSON structure for encryption or signature, possibly consider as Note later if guidance needed.

**Comment by azaroth42** [comment]
Discussion both in the thread and on the telcon was that all of this was out of scope. Closing and marking as such.

**Comment by azaroth42** [comment]
Closed, out of scope, but for reference for people interested in this topic:
- https://web-payments.org/specs/source/ld-signatures/
- http://json-ld.org/spec/latest/rdf-dataset-normalization/

/ht @gkellogg
