### ISSUE TITLE
Newline escaping in embedded content

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#64]
How do newlines get serialized when used in:
- Literal bodies
- Embedded Content bodies

We should verify that serializations work as expected, especially JSON-LD.

(Separated from #63)

**Comment by azaroth42** [comment]
There seem to be two options here:
- New lines are not possible, as they're not possible in JSON. Instead you should use HTML with <br/> or other tags, or an external resource.
- The string "\n" MUST be interpreted as a newline character when included in the value of oa:text

**Comment by gobengo** [comment]
pretty sure new lines are in JSON

```
console.log(JSON.parse(JSON.stringify({ "foo": "sup\nsup2" })).foo)
sup
sup2
```

**Comment by BigBlueHat** [comment]
Yep. "\n" is valid and interpreted by JSON processors as expected (including JSON-LD):
http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf#page10

So...document? example? other?

**Comment by azaroth42** [comment]
Close, no action, works as expected? :)

**Comment by BigBlueHat** [comment]
:+1:
