### ISSUE TITLE
PROV-O Mapping

### ISSUE THREAD

**Issue by csarven** [w3c/web-annotation#65]
Question: Is the mapping between OA and PROV-O declared anywhere? That is, a file with the RDF mapping. Something beyond http://www.w3.org/TR/annotation-model/#mapping-to-provenance-model ?

**Comment by stain** [comment]
The RDF mapping to PROV is already part of the [OA ontology](http://www.w3.org/ns/oa/):

``` turtle
oa:annotatedBy rdf:type owl:ObjectProperty ;
               rdfs:subPropertyOf prov:wasAttributedTo .

oa:equivalentTo rdf:type owl:ObjectProperty ;
                rdfs:subPropertyOf prov:alternateOf .

oa:serializedBy rdf:type owl:ObjectProperty ;
                rdfs:subPropertyOf prov:wasAttributedTo .
```

The [PROV constraints](http://www.w3.org/TR/prov-constraints/) detail how `prov:wasAttributedTo` expands into activities and agents.

I still think that the PROV mapping could be broadened, e.g. `serializedAt` and `annotatedAt` is not mapped in the ontology.  

I don't think there's much more that can be added generally.. as even though say an annotation target is "about" an annotation body, we can't infer `prov:wasInfluenedBy`-kind of provenance here as the "aboutness" can be more abstract, depending on the motivation etc.

**Comment by azaroth42** [comment]
Propose to close the issue.

**Comment by iherman** [comment]
+1

**Comment by stain** [comment]
+1

**Comment by lucmoreau** [comment]
BTW, I have never seen a response to my proposal for the mapping to prov.

**Comment by stain** [comment]
@lucmoreau any links..? I can't find the proposal :(
