### ISSUE TITLE
Publish a temporary testing JSON-LD context doc for use with JSON-LD Playground (etc)

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/web-annotation#71]
While working on the [Roles note](http://w3c.github.io/web-annotation/model/wd/roles.html) I wanted to test the JSON-LD examples in the playground, however, the context referenced (`http://www.w3.org/ns/anno.jsonld`) in the examples in that document lack the new bits to make the examples actually "work."

I'd like us to consider hosting a testing-friendly JSON-LD context in this repo OR at least providing an `@context` object (as an appendix) for inclusion when testing.

Would be helpful. :smiley:

**Comment by iherman** [comment]
> On 26 Aug 2015, at 17:00 , BigBlueHat notifications@github.com wrote:
> 
> While working on the Roles note I wanted to test the JSON-LD examples in the playground, however, the context referenced (http://www.w3.org/ns/anno.jsonld) in the examples in that document lack the new bits to make the examples actually "work."
> 
> I'd like us to consider hosting a testing-friendly JSON-LD context in this repo OR at least providing an @context object (as an appendix) for inclusion when testing.

Better. The original of the context file _is_ on the repo:

https://github.com/w3c/web-annotation/blob/gh-pages/jsonld/anno.jsonld

I only pull this from the repo and move it, through CVS, to the W3C space. I see no problem if you test the context file (probably better to do it on a separate branch, though).

However… there might be CORS problems. Playground did not work at first; I had to set the CORS access manually on the W3C site. I am not sure whether github has that.

Ivan

> Would be helpful.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by azaroth42** [comment]
Agreed that a CORS enabled context document would be very useful for evaluating this proposal, and doubtless further similar ones in the future. From looking around, it doesn't seem possible to enable CORS with gh-pages, so it would need a webhook to pull the updated context document to another system that does have it enabled.  

This seems like a general issue that could be useful for many working groups if solved? Is there a temporary space within w3.org that could listen for callbacks from github (or other systems)?

**Comment by iherman** [comment]
> On 26 Aug 2015, at 19:35 , Rob Sanderson notifications@github.com wrote:
> 
> Agreed that a CORS enabled context document would be very useful for evaluating this proposal, and doubtless further similar ones in the future. From looking around, it doesn't seem possible to enable CORS with gh-pages, so it would need a webhook to pull the updated context document to another system that does have it enabled.
> 
> This seems like a general issue that could be useful for many working groups if solved? Is there a temporary space within w3.org that could listen for callbacks from github (or other systems)?

Unfortunately (at this moment) there isn't. It may come, because this issue (not CORS but getting the github content backed up somehow) is important, but it is not yet solved.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by BigBlueHat** [comment]
Remember when Cross-Origin Resource Sharing was a thing the Web was actually designed to do? ...those were the days... :stuck_out_tongue_closed_eyes: 

I can put up a JSON-LD context file in a [Cloudant](http://cloudant.com) (based on [Apache CouchDB](http://couchdb.apache.org/) account (free, fwiw, if the W3C wants one) and enable CORS on it. It's pretty easy to setup a webized database there that can also receive a Webhook from GitHub, so updates would propagate.

Not sure how that fits with process and such, but easy enough for me to do if I can help. :smile:

**Comment by BigBlueHat** [comment]
So, I just pasted this URL (the raw .jsonld file in this repo) within the JSON-LD Playground and it worked!
https://raw.githubusercontent.com/w3c/web-annotation/gh-pages/jsonld/anno.jsonld

Maybe we just need to document that?

It's an "ugly" enough URL that hopefully know one will intend to keep it around. ;)

The one (foreseeable) negative, is that there's no way to redirect...unless following embedded `@context` URLs inside a context file is standard. Probably just needs some testing.

Are we OK with using the raw github URL for testing? Do we think documenting that (in drafts, etc) is sufficient?

**Comment by iherman** [comment]
> On 03 Sep 2015, at 15:46 , BigBlueHat notifications@github.com wrote:
> 
> So, I just pasted this URL (the raw .jsonld file in this repo) within the JSON-LD Playground and it worked!
> https://raw.githubusercontent.com/w3c/web-annotation/gh-pages/jsonld/anno.jsonld
> 
> Maybe we just need to document that?
> 
> It's an "ugly" enough URL that hopefully know one will intend to keep it around. ;)
> 
> The one (foreseeable) negative, is that there's no way to redirect...unless following embedded @context URLs inside a context file is standard. Probably just needs some testing.
> 
> Are we OK with using the raw github URL for testing?

I think that is the best approach. It keeps us from version hell…

Whenever we feel it is stable, you ping me, and I push it onto /ns on W3C

Ivan

> Do we think documenting that (in drafts, etc) is sufficient?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by azaroth42** [comment]
Close? (Another issue on me is to provide a new context doc for the model, but this one was pre Oct 2015 WD, no?)

**Comment by BigBlueHat** [comment]
Eagerly wanting this (again) as I keep building stuff based on the newest things we've discussed (mostly implemented :wink:), but my output's always "wrong" on [JSON-LD's Playground](http://json-ld.org/playground).

@azaroth42 or are you just waiting until I get annoyed enough by that to do it myself? :grin:

**Comment by azaroth42** [comment]
It would be lovely to have some sort of per-branch continuous deployment system where we could see the effects of different changes on the specs and technical resources (ontology, context, frames, examples, tests, etc)

The reticence has been due to the degree of flux recently, and not wanting to get ahead of the discussions on calls or list.

**Comment by hugomanguinhas** [comment]
Hi all, just wanted to ping about this issue... 

We would like to include on our public alpha release of the AnnotationAPI (which is due btw for the end of this month) the changes related to provenance but also refer to the context as defined in the spec.

**Comment by azaroth42** [comment]
We should just deploy the context when it changes.  It makes a mess of any implementations when they're out of sync, and the rate of change is not fast.  Propose close, if that process is acceptable.

**Comment by iherman** [comment]
@azaroth42 sorry, I am a little bit lost by now on what exactly you propose to do. Can you explain? Thx

**Comment by BigBlueHat** [comment]
@iherman if I understand @azaroth42's proposal it's to change the context file whenever the prose spec changes something about the JSON structure. I'm :+1: for that as it's more confusing (for me at least) that they've been (and stay) out of sync.

Cool? :sunglasses:

**Comment by iherman** [comment]
> On 19 Feb 2016, at 15:44, BigBlueHat notifications@github.com wrote:
> 
> @iherman https://github.com/iherman if I understand @azaroth42 https://github.com/azaroth42's proposal it's to change the context file whenever the prose spec changes something about the JSON structure. I'm  for that as it's more confusing (for me at least) that they've been (and stay) out of sync.
> 
> Cool? 

Sure. Of course, that means that the context file has to change on /www.w3.org/ns http://www.w3.org/ns every time it changes on the repo, and only Doug or I can do that. But you guys can bribe me in doing that:-)

**Comment by azaroth42** [comment]
I think the number of times that we'll need is relatively low.  Let's clear out the editor_action queue, hopefully before the next call, then republish WDs and the context document.

**Comment by hugomanguinhas** [comment]
Hi again, also wanted to ping about the Web Annotation Protocol which still refers to the Open Annotation context (http://www.w3.org/ns/oa) and not the new one (http://www.w3.org/ns/anno.jsonld)... but I understand this will also have an impact on the examples.

**Comment by azaroth42** [comment]
The protocol is waiting for me to update the lists in the model, so I can then refer to them. But yes, it will come together soon :)

**Comment by azaroth42** [comment]
Okay, I think we're ready to go :) @iherman if you could do the honors of pushing anno.jsonld over to the /ns/ space, it should be up to date with the latest drafts, which cover all of the issues raised.

**Comment by iherman** [comment]
Done.
