### ISSUE TITLE
Clarify TextQuoteSelector without prefix/suffix

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#76]
Clarify in the model whether a TextQuoteSelector with an exact property but no prefix or suffix, that matches more than once in the target resource selects all of the matches, or if not, which one.

Proposal:  Selects all of the matches.  If more specificity is required, then use longer prefix/suffix.

**Comment by BigBlueHat** [comment]
:+1: for adding language to clarify this text.

**Comment by shepazu** [comment]
I agree with your proposal for TextQuoteSelector in isolation.

I'd expect that multiple selectors might be in play at once, and that they all selectors for a target work together to refine a selection (e.g. some combination of the TextQuoteSelector and DataPositionSelector might narrow down to a specific instance of an exact text match).

I'm still unsure if this description belongs in the data model or another spec, but it should go in the Data Model for now.

**Comment by tilgovi** [comment]
This may be the only selector that's ambiguous right now, but it would be good to answer in the general definition of a selector.

It also might be that this is for the client API to specify and not the model.

**Comment by jjett** [comment]
+1

**Comment by azaroth42** [comment]
Resolved in Oct 2015 WD
