### ISSUE TITLE
typo in Protocol: rdf:label

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/web-annotation#77]
http://w3c.github.io/web-annotation/protocol/wd/#container-retrieval-requirements: "human readable label using the rdf:label predicate".
Should be rdfs:label.

**Comment by azaroth42** [comment]
Fixed in protocol (now just json `label`):  http://w3c.github.io/web-annotation/protocol/wd/#responses-without-annotations
Fixed equivalent in vocab: http://w3c.github.io/web-annotation/vocab/wd/#rdfs-label

**Comment by BigBlueHat** [comment]
@azaroth42 do you recall why `label` was chosen over `name`--which is what AS2 is using?

**Comment by BigBlueHat** [comment]
Ah....think I found it in their [vocab document](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-name):

> The name MAY be expressed using multiple language-tagged values.

...for which one can also substitute their unique `nameMap` thing...

**Comment by azaroth42** [comment]
rdfs:label is more widely used than as:name (obviously, as AS hasn't even gone into CR yet) so in terms of stability and likelihood that it will be understood, rdfs:label seems more appropriate.

Unless you mean the JSON-LD key for rdfs:label as `label`?

**Comment by BigBlueHat** [comment]
@azaroth42 I suppose I meant both...actually. :smile: The `rdfs:label` selection makes sense over `as:name`, but I'm curious ('cause I don't remember) if we discussed using `schema:name` instead. 

As far as the JSON-LD level keys...`label` vs. `name` vs. `title` (from Atom or HTML for instance)...I'm not sure it matters terribly. Preference being to surface the friendliest version of whatever term is used underneath--so in this case `label` is perfect as `rdfs:label` is underneath.

**Comment by iherman** [comment]
Propose to leave this as `label`
