### ISSUE TITLE
typo in Model: "Core document"

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/web-annotation#78]
http://www.w3.org/TR/annotation-model/#selectors: "the Core document". But there's no "Core document" anymore, it's a section in the same document.
http://www.w3.org/TR/annotation-model/#specifiers: "the core data model".

For both instances, I think its better to add a reference to the specific section http://www.w3.org/TR/annotation-model/#fragment-uris

**Comment by azaroth42** [comment]
Resolved in Oct 2015 WD.
