### ISSUE TITLE
Allow pool of "tags" on Annotation

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#86]
For example, annotator's "tags" or for location / subject / etc.  A generic bag of extra "stuff".

**Comment by tilgovi** [comment]
What would this mean for the model? The Annotation itself is already a bag for this stuff. What are the specific things, other than tags, that we might want?

**Comment by azaroth42** [comment]
Is anyone willing to champion this issue and make a concrete proposal, or shall we close it?

**Comment by azaroth42** [comment]
Proposal:  Close, wontfix

**Comment by jjett** [comment]
+1 to closing

**Comment by iherman** [comment]
+1

**Comment by iherman** [comment]
Closed via the telco, http://www.w3.org/2016/01/27-annotation-irc#T16-27-28
