### ISSUE TITLE
Emerging best practice is to use id/type aliases for @id/@type

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#88]
From @msporny: Emerging best practice is to use id and type, not @id and @type.  There has been agreement from schema.org (@danbri), and Social Web (@tantek) 

This issue is to revert to the previous state where we did this.

**Comment by azaroth42** [comment]
And schema.org issue: https://github.com/schemaorg/schemaorg/issues/854

**Comment by azaroth42** [comment]
And more, already accepted: https://github.com/hbz/lobid-organisations/issues/51

**Comment by tilgovi** [comment]
:+1:

**Comment by danbri** [comment]
Just to clarify --- I felt I could reasonably add this into schema.org's context file implementation, in the spirit of https://en.wikipedia.org/wiki/Robustness_principle .... for people working with generic context-file JSON-LD tooling. However this is not the same as getting commitment from e.g. google/yahoo/microsoft/yandex that they'll accept this syntax variation, that is a longer conversation to have. I think it makes sense though. I'll continue investigating, and perhaps we'll see a stronger endorsement of this syntax style from the schema.org project.

**Comment by jasnell** [comment]
Would happily work to get this into the Activity Streams 2.0 `@context` also. It would be a welcome change.

**Comment by akuckartz** [comment]
:+1:

**Comment by BigBlueHat** [comment]
@jasnell :+1: happy to help make that happen.

**Comment by BigBlueHat** [comment]
Also, this is "closed" via #89 & #90 -- list conversation not withstanding. We can reopen (imo) if/when there are reasons to revisit.

Hope that's copacetic @azaroth42 :smile_cat:

**Comment by azaroth42** [comment]
For reference, the AS document with the mapping (and maintaining @context):

> http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-core/

Thanks to @jasnell :)
