### ISSUE TITLE
Do we need modules for the specification?

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#9]
A question was whether or not we need to use modules (ala CSS) for the specification.  

**Proposal**

Defer until we have a specification large enough to need splitting up!

**Background**

The CG originally had two modules, core and extension, and for the second draft collapsed them into one.  This was due to confusion of which features belonged in the core and which in a module, and the namespace issues that were generated by separating them.

**Links**
- [Tracker](http://www.w3.org/annotation/track/issues/6)

**Comment by iherman** [comment]
I do not think that splitting is only a matter of size. The specific issue I have is the 'selector' part. I believe that this structure gives an overall extensibility framework that would be useful for the robust anchoring work where, e.g., media-specific anchoring mechanisms can be plugged in. Combined with a dedicated API this 'module' would be useful beyond the goals of annotation (e.g., to attach metadata to content although some could argue that this is a special form of annotation...), and that could justify having it as a separate module, in its own namespace et al.

Thanks

Ivan

On 08 Oct 2014, at 24:39 , Rob Sanderson notifications@github.com wrote:

> A question was whether or not we need to use modules (ala CSS) for the specification.
> 
> Proposal
> 
> Defer until we have a specification large enough to need splitting up!
> 
> Background
> 
> The CG originally had two modules, core and extension, and for the second draft collapsed them into one. This was due to confusion of which features belonged in the core and which in a module, and the namespace issues that were generated by separating them.
> 
> Links
> 
>   • Tracker
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me

**Comment by azaroth42** [comment]
That's a good point, Ivan.  If there are clear rules (all selectors or perhaps specifiers go here) then the modularization would be a much easier proposition. I think we should keep it in mind until we have a better understanding of the full set of requirements and scope.

**Comment by shepazu** [comment]
Another thing I'd like to see from modules is separation of the data model from the formal RDF serialization and SPARQL queries.

**Comment by iherman** [comment]
On 14 Oct 2014, at 24:35 , Doug Schepers notifications@github.com wrote:

> Another thing I'd like to see from modules is separation of the data model from the formal RDF serialization and SPARQL queries.

Yep. More specifically: the document may have to be re-formatted so that all the examples should be in JSON, namely in a format that is compatible (or can be made compatible by adding a "@context" section to JSON-LD) thereby making it bona fide RDF. But for those who do not care about RDF, the Turtle parts in the specification should not be in the way.

(A Turtle serialization can be presented in an informal appendix or a separate note.)

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
GPG: 0x343F1A3D
WebID: http://www.ivan-herman.net/foaf#me

**Comment by azaroth42** [comment]
I propose, given the recent WD, to close the issue of splitting the spec up into modules.  We can always reopen it later if it would be useful.

**Comment by azaroth42** [comment]
Closing as extraneous noise.

**Comment by iherman** [comment]
Noting, just for admin: #110 is closely related to this issue, and the discussion is going on there
