### ISSUE TITLE
Split model into vocab and model+json-ld

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#97]
A proposal discussed at TPAC was to split the documentation that currently is instantiated in annotation-model into two pieces, one for the basic model and the JSON-LD serialization of that model, and a second for the vocabulary/ontology.

Rationale:
- This is what ActivityStreams does and the Social Web WG have very similar goals to us in terms of making the outcomes of the group accessible.
- It helps with testing -- if we only normatively specify the JSON-LD profile, then that's all we need to test.  The ontology can then be tested separately, without worrying about JSON-LD or any particular serialization.  We would not need to test turtle representation of the model, for example, as it's just turtle.
- It makes it easier to be specific in both -- the vocab doc can say things like rdfs:subPropertyOf and give domain and range, whereas the model and JSON-LD serialization can take out things that are acceptable-to-no-one like "URI" in the tables, the turtle serialization, and so forth.

**Comment by azaroth42** [comment]
The proposal at TPAC was to auto-generate the documentation using the ontology plus a tool like [LODE](http://www.essepuntato.it/lode). There are several issues with this:
-  There is a distinction between the terms we define in the ontology, and the terms that we use in the model.  This documentation should cover both, and the ontology would only cover our own.
-  The result would still need to be respec'd to ensure presentation and process consistency.
-  It separates concerns of publication of spec documents from publication of technical artifacts such as ontologies.  Editors (present and future) should not be required to write OWL to update the specification, the OWL should be derived from that specification.
-  Given the above, it's unclear that there would be significant savings, nor that the result would be more readable than what we have today.

My proposal instead is to intentionally mimic the familiar style, but that the process should be manual.

**Comment by azaroth42** [comment]
The first section of my proposed vocab split:
    http://w3c.openannotation.org/add_vocab/vocab/wd/

Assuming that there are no :-1:s to the approach, I'll continue with the rest of the properties.

**Comment by akuckartz** [comment]
:+1:

**Comment by gobengo** [comment]
> The proposal at TPAC was to auto-generate the documentation using the ontology plus a tool like LODE http://www.essepuntato.it/lode.

@azaroth42 I have a tool that renders [some HTML](https://livefyre.github.io/activity-vocabulary/) from a JSON-LD document describing [the underlying vocabulary](https://github.com/gobengo/livefyre-activity-vocabulary/blob/master/livefyre.jsonld) (borrowing some rdfs and [hydra](http://www.hydra-cg.com/spec/latest/core/) props).

The script is a little overfit for my use case, but perhaps a good starting point to something more generalizable. I just published it at [gobengo/livefyre-activity-vocabulary](https://github.com/gobengo/livefyre-activity-vocabulary) for you to peruse.

Basically
[This script](https://github.com/gobengo/livefyre-activity-vocabulary/blob/master/bin/make-public-data.js) reads the jsonld and uses node 'jsonld' lib to mash it into a more customer JSON structure using JSON-LD framing. It also renders some markdown files to html to use as descriptions.

The structure is like

``` bash
⚡ bin/make-public-data.js | jq '[(keys - ["data"])[] as $key | { ($key): .[$key] | keys }] | add'
{
  "classes": [
    "activities",
    "objects",
    "properties"
  ]
}
```

Then it uses that as template context to some HTML templates (using [`harp compile`](https://www.npmjs.com/package/harp))

The [Makefile](https://github.com/gobengo/livefyre-activity-vocabulary/blob/master/Makefile#L38) makes it all explicit.

You may find it useful.

**Comment by azaroth42** [comment]
All,

As this involves sweeping changes to the document(s), it makes it difficult to progress other issues as the documentation/split would need to be re-done.  Please give a quick +1/-1 to the split, and lets move on.

**Comment by jjett** [comment]
+1

**Comment by BigBlueHat** [comment]
:+1:

**Comment by shepazu** [comment]
+1

**Comment by iherman** [comment]
+1

**Comment by cmbirk** [comment]
+1

**Comment by davis-salisbury** [comment]
+1

**Comment by iherman** [comment]
Closing with acceptance at the call http://www.w3.org/2015/12/02-annotation-irc#T16-21-25

**Comment by azaroth42** [comment]
Done: 
http://w3c.github.io/web-annotation/model/wd2/
http://w3c.github.io/web-annotation/vocab/wd/
